### ISSUE TITLE
Api using give [object ojbect] in response

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1027]
### Actual behavior
`(api|https://decapi.me/twitch/subscriber_emotes/soge__) (api._response)`
will give in chat [object object]
### Steps to reproduce
Use that in command
### Additional informations

7.6.0 snapshot, mongodb

**Comment by sogehige** [comment]
That api is returning { emotes: [ 'sogeFAIL', 'sogeYES' ] }

although I will update that object to print out correctly as a string

**Comment by sogehelper** [comment]
Hm, I do not understand, you will change what would be a string?

**Comment by sogehige** [comment]
No, I will just update `[object object]` to be proper stringified object `{ emotes: [ 'sogeFAIL', 'sogeYES' ] }`

this is not a bug, you need to use `(api.emotes)`, which is an array, so I would rather use eval variable
