### ISSUE TITLE
Price isn't removing points...

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#1030]
When using Price for say 

!queue join (costs 50) and when using the command points aren't removed. Also feel it should say when/if points are removed and when they are.

**Comment by sogehelper** [comment]
if you run that command as owner, you will not lose points
also there is no message about lost points

**Comment by ic3dr460n** [comment]
RIP. I did do it as myself. I will have to find someone in the stream to test I guess.
