### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#1089]
<--- Last few GCs --->

[3968:00000000003532E0] 648051592 ms: Mark-sweep 1352.9 (1423.0) -> 1352.9 (1422.0) MB, 758.7 / 0.0 ms  allocation failure GC in old space requested
[3968:00000000003532E0] 648052340 ms: Mark-sweep 1352.9 (1422.0) -> 1352.9 (1418.5) MB, 747.5 / 0.0 ms  last resort GC in old space requested
[3968:00000000003532E0] 648053091 ms: Mark-sweep 1352.9 (1418.5) -> 1352.9 (1418.5) MB, 751.3 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000008FA5D04281]
Security context: 00000342427A06A9 <JSObject>
    1: recursive [C:\sogeBot\libs\timeout.js:~18] [pc=0000008FAC8E73BB](this=0000009C5CFE8B91 <Timeout map = 000002E996A103F1>,opts=0000009C5CFE8BA9 <Object map
 = 000002E996A0EFA1>)
    2: sendRequest [C:\sogeBot\libs\databases\master.js:~42] [pc=0000008FACE35C46](this=0000003D4EDAB831 <Interface map = 000002E996A59E11>,resolve=0000009C5CFE
89F1 <JSFuncti...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::DecodeWrite
 2: node_module_register
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::FatalProcessOutOfMemory
 5: v8::internal::Heap::MaxHeapGrowingFactor
 6: v8::internal::Factory::NewFixedArrayWithMap
 7: v8::internal::HashTable<v8::internal::SimpleNumberDictionary,v8::internal::SimpleNumberDictionaryShape>::ToKey
 8: v8::internal::StringTable::LookupString
 9: v8::internal::StringTable::LookupString
10: v8::internal::Logger::TimerEvent
11: v8::internal::Logger::TimerEvent
12: 0000008FA5D04281
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sogebot@7.5.1 start: 'node ./tools/migrate && npm-run-all --parallel build:css copy:dist && cross-env NODE_ENV=production node ./main || true'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sogebot@7.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2018-07-08T10_58_34_359Z-debug.log

### Additional information

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v10.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sogebot@7.5.1~prestart: sogebot@7.5.1
6 info lifecycle sogebot@7.5.1~start: sogebot@7.5.1
7 verbose lifecycle sogebot@7.5.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle sogebot@7.5.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\sogeBot\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Ray\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Ray\AppData\Local\Programs\Python\Python36\;C:\Users\Ray\AppData\Roaming\npm
9 verbose lifecycle sogebot@7.5.1~start: CWD: C:\sogeBot
10 silly lifecycle sogebot@7.5.1~start: Args: [ '/d /s /c',
10 silly lifecycle   'node ./tools/migrate && npm-run-all --parallel build:css copy:dist && cross-env NODE_ENV=production node ./main || true' ]
11 silly lifecycle sogebot@7.5.1~start: Returned: code: 1  signal: null
12 info lifecycle sogebot@7.5.1~start: Failed to exec start script
13 verbose stack Error: sogebot@7.5.1 start: `node ./tools/migrate && npm-run-all --parallel build:css copy:dist && cross-env NODE_ENV=production node ./main || true`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:957:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
14 verbose pkgid sogebot@7.5.1
15 verbose cwd C:\sogeBot
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.1.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error sogebot@7.5.1 start: `node ./tools/migrate && npm-run-all --parallel build:css copy:dist && cross-env NODE_ENV=production node ./main || true`
22 error Exit status 1
23 error Failed at the sogebot@7.5.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

`2018-07-08T16:29:16.685 DEBUG: ======= COPY DEBUG MESSAGE FROM HERE =======
2018-07-08T16:29:16.686 DEBUG: GENERAL | OS: npm/5.6.0 node/v10.1.0 win32 x64 | DB: nedb | Bot version: 7.5.1 | Bot uptime: 22990.208 | Bot lang: en | Bot mute:
 false
2018-07-08T16:29:16.686 DEBUG: SYSTEMS | timers, customcommands, keywords, points, price, alias, moderation, ranks, bets, raffles, queue, cooldown, gambling, hi
ghlights
2018-07-08T16:29:16.687 DEBUG: WIDGETS | raffles, twitter, chat, eventlist
2018-07-08T16:29:16.687 DEBUG: OAUTH | BOT true | BROADCASTER true
2018-07-08T16:29:16.688 DEBUG: ======= END OF DEBUG MESSAGE =======`

Hopefully it helps in narrowing down the issue.

**Comment by sogehige** [comment]
Hopefully fixed in 8.0.x, feel free to reopen if same issues occurs again
