### ISSUE TITLE
(random.online.viewer) return bot username

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1096]
### Actual behavior
(random.online.viewer) sometimes return bot username
so it's not exclude bot from this random.
### Steps to reproduce
use (random.online.viewer)

**Comment by Satont** [comment]
Also in code ```javascript
var users = (await global.db.engine.find('users.online')).map((o) => o.username)
var randomuser = _.sample(users)
```
return bot username too
so bot write himself to online users lol

**Comment by sogehelper** [comment]
Also in my own code
```javascript
var users = (await global.db.engine.find('users.online')).map((o) => o.username)
var randomuser = _.sample(users)
```
return bot username too
so bot write himself to online users lol
