### ISSUE TITLE
moderation blacklist not working

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1106]
### Actual behavior
i have *word* in blacklist but it's not working
Bot not catch this word in chat and not ban
### Additional informations

7.5.1, mongodb

**Comment by sogehelper** [comment]
I have created `*word*` so it's step to reproduce

**Comment by sogehige** [comment]
No, againts what it is checking that word? Is it mod or regular user?

**Comment by sogehelper** [comment]
just user type in chat `word` but i have it blacklisted and bot not ban him

**Comment by sogehige** [comment]
I cannot reproduce with `fixes` branch. Can you recheck with that branch? (it may be fixed there already as I did some updates etc.)

**Comment by sogehelper** [comment]
Ok, on `fixes` branch working.

**Comment by sogehelper** [comment]
How i can help reproduce it? It's not working on master
