### ISSUE TITLE
process send timeout give timeout to 5 minutes instead of seconds

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1127]
### Actual behavior
process.send({type: 'timeout', reason: '', duration: 5, username: opts.sender.username}) in my own system give user 5 minutes timeout instead of 5 seconds.
it's bug or excepted behavior?

### Steps to reproduce
process.send({type: 'timeout', reason: '', duration: 5, username: opts.sender.username})
### Additional informations

Latest master, nedb

**Comment by sogehige** [comment]
Expecting `timeout`, not `duration`

**Comment by sogehelper** [comment]
Changed to `timeout` and it's still bad for 300 seconds instead 5 seconds
`process.send({type: 'timeout', reason: 'qqq', timeout: 5, username: opts.sender.username})`
