### ISSUE TITLE
Messages sended to process not appears in logs

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#1129]
### Actual behavior
All process.send, for example, `process.send({type: 'say', message: 'qwe'})`, not appears in bot logs
In my own system I send to process messages, timeouts, and this not appears in logs
### Steps to reproduce
Create system and try process.send something

**Comment by sogehelper** [comment]
I know but maybe it's fixeble?
Because i like process.send more then sendMessage
And why we need process.send if we have sendMessage then

**Comment by sogehelper** [comment]
It's can be fixed if i'll change ```javascript
else if (msg.type === 'say') {
      global.commons.message('say', config.settings.broadcaster_username, msg.message)
    }
```
to
``javascript
else if (msg.type === 'say') {
    global.log.chatOut(msg.message, {username: msg.sender})
      global.commons.message('say', config.settings.broadcaster_username, msg.message)
}
```
Or it will not fix that?

**Comment by sogehige** [comment]
Well, its not a bug....use sendMessage

**Comment by sogehelper** [comment]
I understant, but does it will appears in logs if i'll add this line what i'm sended?
