### ISSUE TITLE
UI Bug: abbr does not expand

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1131]
### Actual behavior
I have an event, open him for edit, and i see that 
![img](https://i.imgur.com/zYKhKEs.png)
abbr for that operation input wasn't expanded

**Comment by sogehige** [comment]
Possibly same issue with custom commands, height is notp roperly propagated to form-control

**Comment by sogehelper** [comment]
Chrome.

**Comment by sogehige** [comment]
Cannot reproduce with events, will fix with commands
