### ISSUE TITLE
Several GUI Field issues

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#1144]
Bot Version: Latest Master 8/7/18

Soundboard: When changing sound or attempting to drag causes the widget to also move. Workaround is to just click which volume you'd like. (Not a big deal.)

Wheel of Fortune: When adding 'Responses' it overlaps with other fields. When editing the box should be in front of all others.
Example:
![image](https://user-images.githubusercontent.com/32691495/43774995-15812286-9a19-11e8-8b0b-b8275cf1b98c.png)
![image](https://user-images.githubusercontent.com/32691495/43774881-b08a40f6-9a18-11e8-82e4-4c0bcd27f572.png)

These are the ones I've notice thus far.

**Comment by sogehige** [comment]
Browser? Browser version?

**Comment by ic3dr460n** [comment]
Google Chrome
Version 68.0.3440.84 (Official Build) (64-bit)
