### ISSUE TITLE
Loading from server...

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#1145]
Bot Version: Latest Master 8/7/18
DB: NEDB

Unsure if this could be optimized to load faster or not. Heists seems to take the longest (10 seconds) to load. Could just be slow loading from server but unsure.

Exmaple:
![image](https://user-images.githubusercontent.com/32691495/43775087-6de480bc-9a19-11e8-85b6-0cf9278c9280.png)

**Comment by sogehige** [comment]
Its under 1s for me on nedb

**Comment by ic3dr460n** [comment]
It could just be my server. Not sure.
