### ISSUE TITLE
CPU usage on 8.0.0 snapshot, mongodb

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1152]
### Actual behavior
I tryed run 1 bot with different verions.
7.5.1 use 0.20avg CPU
8.0.0 1.5-2.0avg cpu
node_modules cleared, different folders, same systems.
Poolsize is same (default 5)
no more bots runned under test

### Additional informations

8.0.0 latest master. at commit https://github.com/sogehige/sogeBot/commit/82480f5b18c5358ec50edf2212e5ba1c71ab275b
7.5.1 release.
Both mongodb

**Comment by sogehelper** [comment]
I can provide DB dump if you want

**Comment by sogehelper** [comment]
where i need run that?
1) mongo
did i need `use database`
or where?

**Comment by sogehige** [comment]
run it on mongodb, in compass or whatever mongodb gui you are using

**Comment by sogehelper** [comment]
i try in in just console, after `mongo`, and got this
root@home:~# mongo
MongoDB shell version: 3.2.11
connecting to: test
> db.currentOp({“secs_running”: {$gte: 3}})
2018-08-08T04:26:06.425+0300 E QUERY    [thread1] SyntaxError: illegal character @(shell):1:14

**Comment by sogehige** [comment]
`db.currentOp({"secs_running": {$gte: 3}})`

**Comment by sogehige** [comment]
If its empty, lower it to 2 or 1

**Comment by sogehelper** [comment]
{ "inprog" : [ ], "ok" : 1 }

**Comment by sogehige** [comment]
Are you running affected bots? Did you try 2, 1?

**Comment by sogehelper** [comment]
And affected bots is runned.
Yes, same response.
i have 4 bots on latest master now.

**Comment by sogehige** [comment]
Please enable profiling on mongodb `db.setProfilingLevel(2)`, it should create `system.profile` collection. Let it run and send it to me tomorrow

**Comment by sogehige** [comment]
You can disable profiling after with `db.setProfilingLevel(0)`

**Comment by sogehelper** [comment]
i did, but not see that collection
` 
db.setProfilingLevel(2)
{ "was" : 0, "slowms" : 100, "ok" : 1 }
 use system
switched to db system
 db.getCollectionInfos()
[ ]
 db.getCollectionNames()
[ ]
>
`
it's ok?

**Comment by sogehige** [comment]
It should Oo

https://docs.mongodb.com/manual/tutorial/manage-the-database-profiler/

Are you enabling profiler on affected dbs?

**Comment by sogehelper** [comment]
oh no, ok i did it.
also i can't keep runned all bots, because 8cpu make crash my mongo service
how i can fix that? maybe only 1 bot?
Can i downgrade others?

**Comment by sogehige** [comment]
Please check master after PR #1156 is merged
