### ISSUE TITLE
Can't open cooldowns list

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1176]
### Actual behavior
Cooldown list is empty for me, for that console errors
[Vue warn]: Error in render: "TypeError: Cannot read property 'toUpperCase' of undefined"
(found in <Root>)
warn @ vue.js:597
logError @ vue.js:1739
globalHandleError @ vue.js:1734
handleError @ vue.js:1723
Vue._render @ vue.js:4537
updateComponent @ vue.js:2788
get @ vue.js:3140
run @ vue.js:3217
flushSchedulerQueue @ vue.js:2981
(anonymous) @ vue.js:1839
flushCallbacks @ vue.js:1760
Promise.then (async)
microTimerFunc @ vue.js:1808
nextTick @ vue.js:1852
queueWatcher @ vue.js:3068
update @ vue.js:3207
notify @ vue.js:703
reactiveSetter @ vue.js:1020
proxySetter @ vue.js:3298
socket.emit @ VM386:36
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
vue.js:1743 TypeError: Cannot read property 'toUpperCase' of undefined
    at eval (eval at createFunction (vue.js:10667), <anonymous>:3:3592)
    at Proxy.renderList (vue.js:3699)
    at Proxy.eval (eval at createFunction (vue.js:10667), <anonymous>:3:1456)
    at Vue._render (vue.js:4535)
    at Vue.updateComponent (vue.js:2788)
    at Watcher.get (vue.js:3140)
    at Watcher.run (vue.js:3217)
    at flushSchedulerQueue (vue.js:2981)
    at Array.<anonymous> (vue.js:1839)
    at flushCallbacks (vue.js:1760)

**Comment by sogehige** [comment]
Can you share your cooldown collection?

**Comment by sogehelper** [comment]
Yes i can, i'll share in discord PM

**Comment by sogehige** [comment]
After PR is merged, cleanup cooldown collection
