### ISSUE TITLE
sender emote parameter is object not array 

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#1211]
### Actual behavior
I create my own system right now, and i try to found an solution. I need count emotes in message.
So, i'm gonna moderation.js, and copy 
```javascript
 var count = 0
_.each(opts.sender['emotes'], function (value, index) {
      count = count + value.length
    })
```
From `async emotes` function.
My code is:
```javascript
  _.each(opts.sender['emotes'], function (value, index) {
            console.log(value.length)
})
```
I go to chat, send some emotes, after this output is:
```
2018-08-17T19:45:36.495 <<< Kappa Kappa Keepo RuleFive [sogehelper]
undefined
undefined
undefined
```
i think here is possible issue (bug)
If i'm wrong correct me
Possible moderation system works same as my code

**Comment by sogehige** [comment]
Current emote parameter is object and not array

twitch-js/#142

**Comment by sogehige** [comment]
Fix should be done on twitch-js lib
