### ISSUE TITLE
Give user subage when receive community gift

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1220]
When users got community gift insert their subage.

**Comment by sogehige** [comment]
Actually I didn't have chance to test community gifts, but afaik I cannot get who receive subscriptions, unless I poll for API or, correct me if I am wrong, there should be subgift event (x user gifted sub to y user) for each user which should handle that.

**Comment by sogehige** [comment]
What version of bot? Use template please :)

**Comment by Banonevar** [comment]
It was not like issue, it more more like amendment.
But I can not attribute this to ideas.
I think when user give community gift, he emit 2 events
First: USERNOTICE/SUBSCRIPTION_GIFT_COMMUNITY
Second: all users who got gift emit USERNOTICE/SUBSCRIPTION_GIFT
But i'm not sure
https://twitch-apis.github.io/twitch-js/docs/reference/class#usernotice-subscription-gift

**Comment by Banonevar** [comment]
But this is only an assumption

**Comment by sogehige** [comment]
Yes that should be correct #1194 is needed for not sending too many alerts although user should have subage after that. So you have logs for that?

**Comment by sogehige** [comment]
No new comments, closing
