### ISSUE TITLE
Default ignored users

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1233]
### Actual behavior
I have blocked fider.io, so i cant post it to fider.
What you think add some bots to default ignore list?
Like commanderrot, moobot, e.t.x

**Comment by sogehige** [comment]
No default ignore list :)

**Comment by Banonevar** [comment]
Why not?

**Comment by sogehige** [comment]
What if someone doesn't want to have some default ignore list? You are free to add anyone to ignore list, that's not too much work

**Comment by Banonevar** [comment]
Idk who not want have stupid afk bots like decafsmurf, 1111azazel1111, electricallongboard e.t.c
They are just afk

**Comment by sogehige** [comment]
What if I add Banonevar or any other user? Or it slip through some PR? I don't really see any additional value for this, those bots are AFK, harmless and you can ignore them in few simple clicks.

**Comment by Banonevar** [comment]
Ofc few simple clicks on each bot.
Ok, thx.
