### ISSUE TITLE
2 days left, but user got like 700 hours in 2 days

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1257]
### Actual behavior
yesterday user was 709h
2018-08-29T00:18:02.752 >>> @user | 709.0h | 42 points | 30649 messages [user]
But now, he have 1444
Bot: @user | 1444.0h | 2 points | 32349 messages | 0.00 RUB
His time is counting, like this ^ log was ~1h ago, now he have 1444.4h
Also i send all user objects from db.users.watched in discord.
### Steps to reproduce

Update of bot between

### Additional informations

Mongodb, latest master (https://github.com/sogehige/sogeBot/commit/e118b9ee40fc10bb3e8075c932d9d034b1c80e8c)

**Comment by sogehige** [comment]
Migration issue after you tried to save #1256, which used old db table (another 700h) , which was migrated again -> + 700h

**Comment by sogehige** [comment]
Its not a bug, its correct behavior of migration
