### ISSUE TITLE
bot respond with parametr

### ISSUE THREAD

**Issue by Satont** [sogehige/SogeBot#129]
Example:
have custom command like:
**test** with **respond**: qweewq (received.parametr.test.)
**Satont**: !test yeah, hello
**Bot**: qweewq yeah, hello

**Comment by sogehige** [comment]
Added (param) filter

**Usage for custom commands:**
Command: !test
Response: Something (param) something

!test
_bot will not repond (no param is given)_
!test dark side
Bot: Something **dark side** something
