### ISSUE TITLE
Next song in songs widget not start play

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1298]
### Actual behavior
When previos song is ended, next song not start to autoplay, and need click play for fix that
### Additional informations

Mongodb, master (https://github.com/sogehige/sogeBot/commit/d13ec03d41c964f2eccccf80881221d0c6feee39)

**Comment by sogehige** [comment]
Cannot reproduce, browser?

**Comment by Banonevar** [comment]
Chrome. I'm always need alt-tab from game and click play button :(

**Comment by sogehige** [comment]
do you have song requests, playlist enabled?

**Comment by sogehige** [comment]
what play button do you click?

**Comment by Banonevar** [comment]
Play

**Comment by Banonevar** [comment]
I need have enabled requests, yes. Does i need have enabled playlist?

**Comment by sogehige** [comment]
> Does i need have enabled playlist?
No.

So if I understand it correctly
1. You have enabled song requests
2. Clicked play
3. Song plays
4. After while new song request
5. Doesn't play automatically

**Comment by Banonevar** [comment]
Yes you understand correctly, next time i'll try describe like you

**Comment by Banonevar** [comment]
Still sometimes not playing next song.
It can be 3-4 songs load normally, not need to alt-tab, but 5th requires alt-tab and click play
