### ISSUE TITLE
Sogebot gives error message at "npm start"

### ISSUE THREAD

**Issue by retroday** [sogehige/SogeBot#130]
![sogeboterror](https://cloud.githubusercontent.com/assets/26395454/23880749/b38fd792-0866-11e7-9d7f-714cf6dcbd75.png)

How can I fix this?

**Comment by sogehige** [comment]
You have old nodejs version, 7.0+ is needed

**Comment by retroday** [comment]
But it says it is the newest version on my raspberry pi... How do I install 7.0 when upgrade doesn't work?

**Comment by sogehige** [comment]
I really don't know what distro are you using on your raspberry
http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/

**Comment by sogehige** [comment]
Also
https://nodejs.org/en/download/current/

**Comment by retroday** [comment]
Thank you!

**Comment by retroday** [comment]
Same error again, version 7.7.2 npm :/ 

![46530f2cc54e790b03f708bd6983fb95](https://cloud.githubusercontent.com/assets/26395454/23897792/89b97118-08bf-11e7-8aa0-1a8658bd20bf.png)

**Comment by sogehige** [comment]
Can you provide npm-debug.log?

**Comment by sogehige** [comment]
Also, full error would be helpfull

Did you install all dependencies?
**npm install** before npm start

**Comment by retroday** [comment]
[npm-debug.txt](https://github.com/sogehige/SogeBot/files/841070/npm-debug.txt)

**Comment by retroday** [comment]
Yes I did npm install beforehand, let me get the full error: 

![4a2b493fb80dd6bce7257f865c4393c5](https://cloud.githubusercontent.com/assets/26395454/23897999/5fe42260-08c0-11e7-959d-b50e5567a6e5.png)

**Comment by sogehige** [comment]
Just to be sure, was npm install successfull?

**Comment by retroday** [comment]
![f03b98d05956eca09512e24089cbc004](https://cloud.githubusercontent.com/assets/26395454/23898151/00066af0-08c1-11e7-946f-454b2c73bdf2.png)

It showed a few progress bars like this, didn't say it was successful or failed.

**Comment by sogehige** [comment]
Ok, its strange because it cannot find 'request' module

Q1: Did you do npm install after node update?
Q2: If it doesn't work, can you run npm install request
Q3: npm install success should look like this 
![screenshot_2017-03-14_12-21-22](https://cloud.githubusercontent.com/assets/19549652/23898271/c314142c-08b0-11e7-82b1-83d27e5d17a2.png)

**Comment by retroday** [comment]
npm install request fixed it. Thanks!

**Comment by retroday** [comment]
On an offtopic, how can I run this in the background at boot?

**Comment by sogehige** [comment]
I am using pm2 - https://github.com/Unitech/pm2
You can add pm2 to startup init

**Comment by sogehige** [comment]
Added request to package.json as dependency to fix this issue, not sure why raspberry doesnt picked it up as dependency
