### ISSUE TITLE
Users got overpointed

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1302]
### Actual behavior
For some reason users start get thouthands points, but in settings it setted lower then they got
I sent you some db's in discord PM
### Additional informations

Mongodb, latest master (https://github.com/sogehige/sogeBot/commit/d13ec03d41c964f2eccccf80881221d0c6feee39)

**Comment by sogehige** [comment]
What you sent is definitely not latest master as you said in discord

**Comment by Banonevar** [comment]
It was for that moment, but its still exists, so problem are same on master

**Comment by sogehige** [comment]
Cannot reproduce, tried online/offline stream, messages, and points intervals

**Comment by Banonevar** [comment]
What i can do then? Maybe i can remove some settings, collections.. it's anoying problem for me

**Comment by Banonevar** [comment]
[new.zip](https://github.com/sogehige/sogeBot/files/2409370/new.zip)
Can you check that? it's latest master

**Comment by sogehige** [comment]
Maybe send users, users.online, users.points when under load

**Comment by Banonevar** [comment]
[users.online.zip](https://github.com/sogehige/sogeBot/files/2409377/users.online.zip)
it's users online then.

**Comment by sogehige** [comment]
Still cannot reproduce, please try latest master, I did some changes to interval, although it was not direcly fixing this issue

**Comment by sogehige** [comment]
Fixed by cfb718a304ff6cf2621fe4f87ef1192c3f59af6a
