### ISSUE TITLE
Sometimes event widget is empty

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1312]
### Actual behavior
Sometimes its blank and after refreshing a few times it will show up correctly, sent an DB in discord pm
### Steps to reproduce
Here is no console errors for me, so i just not know how it can be reproduced
### Additional informations

Master latest commit is https://github.com/sogehige/sogeBot/commit/613b4f16822bdc91c1c85c548bb6fff04a930cb3, mongodb

**Comment by Banonevar** [comment]
[widgetsEventList.zip](https://github.com/sogehige/sogeBot/files/2383231/widgetsEventList.zip)

**Comment by Banonevar** [comment]
https://i.imgur.com/MpOxudG.gifv

**Comment by sogehige** [comment]
You mean everything is set as red?

**Comment by sogehige** [comment]
Any errors in chrome inspector?

**Comment by Banonevar** [comment]
Yea and i can't switch that

**Comment by sogehige** [comment]
Can you please test https://github.com/sogehige/sogeBot/pull/1360 ?

**Comment by Banonevar** [comment]
Not fixed

**Comment by sogehige** [comment]
Can you show me what is wrong?

**Comment by Banonevar** [comment]
Can i send an video to discord? it will be better then gif..

**Comment by sogehige** [comment]
sure

**Comment by Banonevar** [comment]
Now every time when i open dashboard eventlist widget set 0px font size, and 0 events in widget settings

**Comment by Banonevar** [comment]
And if i change set settings, it will be setted to 0 for next load

**Comment by Banonevar** [comment]
Hm ok got 1 time it's loaded correctly, but next time again 0 lol

**Comment by Banonevar** [comment]
OK, after rebuilded UI and bot, it's working!
