### ISSUE TITLE
Empty response after adding command

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1316]
### Actual behavior
If i'll try add some command, and will not add more then 1 response, and will type something in default response #1, when i'll `Save` it, then this response will not be saved
### Additional informations

8.1.0 snapshot, mongodb

**Comment by Banonevar** [comment]
if i'll edit in future that command (after i added that command), then here will be 0 responses and i'll need add this.

**Comment by sogehige** [comment]
can you add images or proper steps? Not sure what you mean

**Comment by Banonevar** [comment]
1) add command with some response (type something in that response)
2) checkout commands list, here will be your commands w/o any responses

**Comment by sogehige** [comment]
Thanks, can you add response through edit later?

**Comment by Banonevar** [comment]
![8zmwu3x](https://user-images.githubusercontent.com/42677896/45568294-eb605700-b864-11e8-9309-0f25e6b3e88b.gif)

**Comment by sogehige** [comment]
Ok thanks, at least it have workaround, its probably issue with _id handling

**Comment by Banonevar** [comment]
Fixed in https://github.com/sogehige/sogeBot/pull/1317 PR
