### ISSUE TITLE
Announce next song wrong username

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1319]
### Actual behavior
I have enabled announce on next track, and message shows **@null** username
### Additional informations

MongoDB, snapshot 8.1

**Comment by sogehige** [comment]
Cannot reproduce, song requests show correct username

**Comment by Banonevar** [comment]
song requests? did you test next song announce? it's happens in announce message

**Comment by sogehige** [comment]
yes, usernames are correctly shown when next song is announced and it is songrequest, playlists songs doesn't have usernames

**Comment by Banonevar** [comment]
Then something weird, also i add songs to playlist via my system, here is code for that:
```javascript
global.systems.songs.addSongToQueue({parameters: opts.parameters, sender: opts.sender.username})
```
guess it's correct?

**Comment by sogehige** [comment]
sender: opts.sender.username => sender: opts.sender

**Comment by Banonevar** [comment]
Ok, thx
