### ISSUE TITLE
Viewers list infinity load loop

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1340]
### Actual behavior
I have infinity load loop of viewers list 
### Steps to reproduce
In console i have only `[Vue warn]: Cannot find element: #coreViewersApp` error
### Additional informations

Mongodb, master (https://github.com/sogehige/sogeBot/commit/ce454f9bfe7f51b6cf51c67f7ffaaa6a9dd40db4)

**Comment by sogehige** [comment]
do you have proper commits?

**Comment by Banonevar** [comment]
Yes, got them all.

**Comment by Banonevar** [comment]
Oh it's loaded after 10 minutes of waiting :D 
Why it's so slow..

**Comment by Banonevar** [comment]
I have good proccessor on this server, it can't be processor limitation i guess (just mean he is not slow)

**Comment by sogehige** [comment]
Because paging is done on client and not on server, I will be updating that in future

**Comment by Banonevar** [comment]
Ok.
