### ISSUE TITLE
Forgottent filters

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1351]
### Actual behavior
You forgot make possible sort users by messages,points,time.
It's important for me.
### Additional informations

Master (https://github.com/sogehige/sogeBot/commit/9ab853ab6935f0f103e354e49cf60ec387a5e7b3)

**Comment by sogehige** [comment]
It's already in a bot

Dne so 22. 9. 2018 13:29 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
I'm not see that

**Comment by sogehige** [comment]
Čas sledování, body and zprávy

Dne so 22. 9. 2018 13:37 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Oh lol.. here is button for switch them, not really intuitive. Maybe highlight this button, or better add icon dropdown, for understantind that this button in dropdown https://fontawesome.com/icons/sort-down?style=solid
