### ISSUE TITLE
High parse time

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1378]
### Actual behavior
I have an issue, some of mine bots take to much response time (25000+, was 40000 once), at happens on all mine bots, and i don't know why it happens. It's start after that commits 
![img](https://i.imgur.com/SD1nLny.png). Maybe problem in next commit after that, but this problem exists.
When parse time is high, my CPU isn't overloaded.
And:
1) bot #5 take 25000ms to parse
2) on same server runned bot #10, where parse time is 78ms
### Additional informations

Mongodb, right now on (https://github.com/sogehige/sogeBot/commit/b9e06964a795a41ba887476041057c662593f044) commit

**Comment by sogehige** [comment]
Is this still issue? Cannot reproduce though

**Comment by Banonevar** [comment]
Nope.
