### ISSUE TITLE
Incorrect  command points give, when !points renamed

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1379]
### Actual behavior
I have renamed points to mp in panel
![img](https://i.imgur.com/SuQVKRi.png)
user: !mp give user2 1000
bot: Sorry, @user, this command incorrect, use !points give [username] [amount]
### Steps to reproduce
Try this on your channel: !points give moobot 1

**Comment by Banonevar** [comment]
Also i check other bot, where !points give not renamed, and same issue
user: !points give user2 100
bot: Sorry, @user, this command incorrect, use !points give [username] [amount]

**Comment by Banonevar** [comment]
Ok seems like all `!points` commands not working 
!points add, e.t.c

**Comment by Banonevar** [comment]
it's still not working for !points add username amount

**Comment by Banonevar** [comment]
i think you not understand issue case, issue case is i can't use that commands, it always `this command incorrect`
You can try it on your channel, use !points add username 5

**Comment by sogehige** [comment]
Also you can edit your initial ticket and not have relevant information across a board
