### ISSUE TITLE
Got doabled variable on save

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1381]
### Actual behavior
When i save variable, it doubles (2 same variables after save)
### Additional informations

master (https://github.com/sogehige/sogeBot/commit/b9e06964a795a41ba887476041057c662593f044), mongodb

**Comment by Banonevar** [comment]
Steps to reproduce: just save existed variable

**Comment by Banonevar** [comment]
Type: script
script: let song = '$currentSong';
var api = url('/song?vk=-119675803&dj=20436');
api.data = api.data !== '' ? api.data : 'Ничего не играет';
return `Песня вк, dj: ${api.data}. Песня в боте: ${song}`;
Command: !song -> response $_song
UI
How i'm checking? i'm see doubled variable in list

**Comment by sogehige** [comment]
In what list?

**Comment by Banonevar** [comment]
Variables

**Comment by sogehige** [comment]
What list of variables, what do you mean by that?

**Comment by sogehige** [comment]
Also not sure how you can double save variable, scripts cannot be saved, their value is changing on variable call or every x hours

**Comment by Banonevar** [comment]
I mean registry of variables
![img](https://i.imgur.com/UrUNhGJ.gif)

**Comment by Banonevar** [comment]
IT happans not only on script variable, i just was in game and it was fast issue, but now i tested it with outhers, text variable same behavior
