### ISSUE TITLE
Can't set title and game on some bot

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1391]
### Actual behavior
I can't set title and game on 1 bot (others working)
bot is channel editor, scopes is ok too
![img](https://i.imgur.com/9Hiz7G4.png)
No errors in console, how i can help reproduce?
### Additional informations

latest master (https://github.com/sogehige/sogeBot/commit/bf4a35d77a307ad4d6d3425ca2fd9e8804471703)

**Comment by Banonevar** [comment]
hm, 
```
2018-09-29T03:58:09.312 >>> https://vk.com/public123123123 [ownernickname]
2018-09-29T03:58:09.313 !!! ERROR !!! TMI: channel is not defined, message cannot be sent
```
but, commands like !uptime, and others working.. and messages from chat appearing in logs

**Comment by sogehige** [comment]
So, do you have channel set? Messages will appear in log even when they are not send if channel is not defined

**Comment by Banonevar** [comment]
yes channel is setted, i restart bot like 4 times, it's not helped

**Comment by sogehige** [comment]
Can you check if you have channelId set in `core.oauth.settings` collection?

**Comment by Banonevar** [comment]
Here is no channelid
