### ISSUE TITLE
Event donate wasn't sended

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1393]
### Actual behavior
got event and message wasn't sended
2018-09-29T06:21:09.317 !!! ERROR !!! TMI: channel is not defined, message cannot be sent
### Additional informations

master https://github.com/sogehige/sogeBot/commit/bf4a35d77a307ad4d6d3425ca2fd9e8804471703

**Comment by sogehige** [comment]
Cannot reproduce with latest master

**Comment by Banonevar** [comment]
Will keep 1 eye on that

**Comment by Banonevar** [comment]
Seems working
