### ISSUE TITLE
Doubled bot

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1407]
### Actual behavior
![img](https://i.imgur.com/tfe927c.png)
And he answer for commands 2 time
1) some1 use !command
2) bot send 2 responses
### Steps to reproduce
Idk
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/9f4c3ceb81f02c32befe026f8005db9d427cca69, mongodb

**Comment by Banonevar** [comment]
Seems like here is doubled chat connection, because follow event not doubled

**Comment by sogehige** [comment]
Possibly duplicate of #1401

**Comment by Banonevar** [comment]
Ok
