### ISSUE TITLE
!poinst param not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1433]
### Actual behavior
I use !points give username 5, but it not working and says me each time that mine command is incorrect
### Steps to reproduce
!points give moobot 1
### Additional informations

Latest master, mongodb (https://github.com/sogehige/sogeBot/commit/39754d5b6402c3a0c3932d713079a9348aacdfae)

**Comment by Banonevar** [comment]
Problem still exists, you can check it on your channel by !points give moobot 1

**Comment by sogehige** [comment]
Fixed by https://github.com/sogehige/sogeBot/commit/0e53c24152f9658051aa539e5a85b1e6dc8016cd
wrong issue link
