### ISSUE TITLE
no blacklisted words issue

### ISSUE THREAD

**Issue by mikkelkulk** [sogehige/SogeBot#145]
I'm having this issue where i typed !whitelist and it returned "no blacklisted words! [2 warnings left]"
And that issue keeps going everytime i type. Even when im just chatting. it counts down to 0 warnings, then back to 2.

This is the output from Putty:

**(node:12328) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec tion id: 1): bad_timeout_broadcaster**

**(node:12328) DeprecationWarning: Unhandled promise rejections are deprecated. In  the future, promise rejections that are not handled will terminate the Node.js pr ocess with a non-zero exit code.**

I know it has something to do with me being the broacaster. But the bot just keeps going with the "no blacklisted words! [2 warnings left]"

**Comment by sogehige** [comment]
Do you have any blacklisted words in settings->moderation->blacklist?

**Comment by sogehige** [comment]
Reproduced issue with steps
# Add some blacklist words to blacklist
# Remove everything from blacklist form
# Bot will try to timeout user

**Comment by sogehige** [comment]
As workaround exists, will be included in next major release
