### ISSUE TITLE
!points give NaN issue

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1450]
### Actual behavior
Bot: @TheGreatZahar_q gives NaN points to @user2
And both users have no changes in points (first not lost points, seconds not recive)
### Steps to reproduce
Also what it weird TheGreatZahar_q not exists in !top points, maybe only TheGreatZahar_q bugged.
I attach mine collections, pls check it.
### Additional informations

[Desktop.zip](https://github.com/sogehige/sogeBot/files/2460130/Desktop.zip)

**Comment by sogehige** [comment]
Closing for now, this issue may be probably fixed
