### ISSUE TITLE
CPu usage after stream gonna offline

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1456]
### Actual behavior
I noticed an thing. When stream go to offline, bot process start use 100% of 1 CPU, and mongodb same.
But after i did restart, it got fixed.
### Steps to reproduce
Maybe try use mongodb on your bots
### Additional informations

Mongodb, master https://github.com/sogehige/sogeBot/commit/cfb718a304ff6cf2621fe4f87ef1192c3f59af6a

**Comment by sogehige** [comment]
Is this still issue?

**Comment by Banonevar** [comment]
Yes

**Comment by Banonevar** [comment]
Thats why i have script what do autorestart bots each 6 hours
