### ISSUE TITLE
Lang for ignorelist not shown

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1466]
### Actual behavior
![img](https://i.imgur.com/uh7k5oU.png)
missed lang, or wrong path to lang
### Steps to reproduce
open #core page -> users
### Additional informations

master https://github.com/sogehige/sogeBot/commit/f496700d9e8fb12dbd980ddf8cd33fd8d5de3903

**Comment by sogehige** [comment]
both langs have correct files
https://github.com/sogehige/sogeBot/blob/master/locales/en/ui/systems/users.json
https://github.com/sogehige/sogeBot/blob/master/locales/cs/ui/systems/users.json

**Comment by Banonevar** [comment]
Yes but i setted bot lang to en (!set lang en) and i got this (on screen)

**Comment by sogehige** [comment]
No issues on en lang

![screenshot 18](https://user-images.githubusercontent.com/19549652/46905241-be997100-cef0-11e8-915c-b30e0c1c7a61.png)

**Comment by Banonevar** [comment]
Ok for some reason file wasn't created on `git cherry-pick`, problem solved.
