### ISSUE TITLE
!subs always show 0 active subs in chat

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1478]
### Actual behavior
If i use !subs on any channel, it always show that right now 0 active subs in chat.
So here is some bug, and possible it same for !followers
### Steps to reproduce
Use !subs
### Additional informations

Mongodb, master (https://github.com/sogehige/sogeBot/commit/300360a14a6856815db28d8274694ccd4c8c74d6)

**Comment by sogehige** [comment]
Cannot reproduce, added tests to cover this
