### ISSUE TITLE
Bot purges for Blacklisted words which are not Specified

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#1485]
### Expected behavior
zero, blacklisted words includes in moderation settings: 
[https://imgur.com/a/HWOqtXi](url)

### Actual behavior
[https://imgur.com/a/IPMlfZI](url)
Blacklists words such as "Brotha" 
### Steps to reproduce
type " have a good night brotha" in chat with bot included

### Additional informations

Latest Master Branch

**Comment by sogehige** [comment]
Updating to latest master branch fixed problem
