### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1487]
### Expected behavior
Must not timeout this whitelisted link `osu.ppy.sh`
### Actual behavior
1) i added `osu.ppy.sh` in whitelist
2) bot still timeout this link
### Steps to reproduce
Try add this link ti whitelist and send message
### Additional informations

Master (300360a14a6856815db28d8274694ccd4c8c74d6), mongodb

**Comment by sogehige** [comment]
Dont really have issue with this.

Add ``(https?:\/\/)?(www\.)?example.com([\/A-z0-9_]+)?`` to your whitelist and it should work -> documented

**Comment by Banonevar** [comment]
Thx.
But i guess regexp not really user friendly

**Comment by Banonevar** [comment]
Bot keeo banning

**Comment by sogehige** [comment]
Ok

**Comment by Banonevar** [comment]
My regexp is (https?:\/\/)?(www\.)?osu.ppy.sh([\/A-z0-9_]+)?

**Comment by Banonevar** [comment]
Maybe problem is https? Link can be http right

**Comment by sogehige** [comment]
No, this `(https?:\/\/)?` means http and https as well
You should share messages where its timeouting

**Comment by Banonevar** [comment]
Ok, my issue is: 
1) it's banning for `osu.ppy.sh/p/2131231231`
2) `osu.ppy.sh` is fine and not banned

**Comment by sogehige** [comment]
Use `(https?:\\/\\/)?osu.ppy.sh(*)?`

**Comment by Banonevar** [comment]
Still timeouting

**Comment by sogehige** [comment]
Because PR is not commited yet

**Comment by Banonevar** [comment]
![img](https://vk.com/photo174008245_456242949)
This message was banned

**Comment by sogehige** [comment]
Yes, best way to share some text is by image, which doesn't work 😆

**Comment by Banonevar** [comment]
Sorry, this screenshot was by my client
![img](https://pp.userapi.com/c848632/v848632765/a5d02/uAiCSKcdK-4.jpg)

**Comment by sogehige** [comment]
Fixed in https://github.com/sogehige/sogeBot/pull/1493

**Comment by Banonevar** [comment]
Did i need change my regexp? or it's still `(https?:\\/\\/)?osu.ppy.sh(*)?`

**Comment by sogehige** [comment]
Same
