### ISSUE TITLE
!command add not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1497]
### Actual behavior
 1) !command add viewer !test test-response
2) bot say this command incorrect
### Steps to reproduce
!command add viewer !test test-response
### Additional informations

master (https://github.com/sogehige/sogeBot/commit/ec8805cf3f0a89a3acbe40c3bb60ce2c0c6fdff0)

**Comment by sogehige** [comment]
Thats not correct command http://sogehige.github.io/sogeBot/#/8.1.x/commands/custom-commands
