### ISSUE TITLE
Highlights not displaying in UI

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#1527]
### Expected behavior
click highlight button next to stream uptime or !highlight in chat
creates highlight
check manage > highlight
highlight displayed
### Actual behavior
click highlight button next to stream uptime or !highlight in chat
creates highlight
check manage > highlight
highlight not displayed but record in systems.highlight.db
### Steps to reproduce
click highlight button next to stream uptime or !highlight in chat
creates highlight
check manage > highlight

### Additional informations
Ubuntu server 16.03 VM - newly installed

**Comment by sogehige** [comment]
Is there any errors in logs?
