### ISSUE TITLE
Uptime not initiated unless Bot is restarted

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#1528]
### Expected behavior
Start stream while bot is on
uptime is visually displayed on top left
### Actual behavior
start stream while bot is on
uptime is not visually displayed on top left
restart bot to enable uptime to visually show
### Steps to reproduce
go live
check uptime

### Additional informations
Ubuntu server 16.03 VM - newly installed

**Comment by sogehige** [comment]
How long you are waiting after stream started? Sometimes it may take up to 10minutes

**Comment by sogehige** [comment]
You can check if bot is polling correct api, you should see in api stats this calls
![untitled](https://user-images.githubusercontent.com/19549652/48285660-98b9aa80-e463-11e8-8913-60f682576cf7.png)
