### ISSUE TITLE
Points give issue

### ISSUE THREAD

**Issue by mikkelkulk** [sogehige/SogeBot#155]
I ran into another issue with the !points give [username] [amount].
Even though i ran the command as i should:

**!points give [username] [amount]** 

it returns:
 **Sorry, @hurtwolf, but this command is not correct, use !points give [username] [amount]**

**Comment by sogehige** [comment]
Fixed, for workaround please update https://raw.githubusercontent.com/sogehige/SogeBot/master/libs/systems/points.js in your libs/system directory
