### ISSUE TITLE
Song widget not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1563]
### Actual behavior
For me my song widget not working, songs not starting to play, and i see error in dev console 
```
Uncaught TypeError: Cannot read property 'play' of undefined
    at o.play (main.js:27)
    at e (main.js:27)
    at HTMLButtonElement.t._withTask.t._withTask (main.js:27)
```
### Additional informations

8.2.0 snapshot, mongodb

**Comment by Banonevar** [comment]
still name error for me

**Comment by sogehige** [comment]
Tested again, ok

**Comment by Banonevar** [comment]
It's ok for you? Idk, maybe i can help with something?

**Comment by sogehige** [comment]
Yes its working

**Comment by Banonevar** [comment]
How i can help reproduce?

**Comment by sogehige** [comment]
Try to reproduce it by properly updating and compiling bot

**Comment by Banonevar** [comment]
I'm do it properly i think. Each time rm -rf node_modules; compile files, e.t.c

**Comment by Banonevar** [comment]
noticed some logs in console (think you forgot remove that)
{player: vue-plyr}
main.js:27 play
main.js:27 undefined
