### ISSUE TITLE
Eventlist lost tiers of subscribtion

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1617]
### Actual behavior
I see eventlist not contain tier of subscribtion/resubscribtion, but on dashboard->viewers page it's have tier 
### Steps to reproduce
check eventlist after some subscribtion/resubscribtion
### Additional informations

Mongodb, master https://github.com/sogehige/sogeBot/commit/5abb058365760132f16abe14ee35f380826e0f23

**Comment by sogehige** [comment]
Cannot reproduce

**Comment by Banonevar** [comment]
you check widget?

**Comment by Banonevar** [comment]
Okay, on english locale it's working. But on mine custom locale it's not.
