### ISSUE TITLE
Checklist button is not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1672]
### Actual behavior
when i open panel, i got Uncaught TypeError: Cannot read property 'length' of undefined
and my checklist button is not working.
Guess it relevant
### Steps to reproduce
Not sure how..

**Comment by sogehige** [comment]
I cannot reproduce, what exact error do you have and what are your steps of checklist use?

**Comment by Banonevar** [comment]
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at r.socket.emit (main.js:27)
    at r.onack (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
    at r.ondecoded (index.js:83)
    at a.<anonymous> (index.js:83)
    at a.r.emit (index.js:83)
    at a.add (index.js:83)
    at r.ondata (index.js:83)

**Comment by sogehige** [comment]
I'll fix that error, its something on mongodb, although checklist button is working, did you set your checklist in system settings?

**Comment by Banonevar** [comment]
My checklist is clear, nothing here. Guess thats why i got that error?

**Comment by sogehige** [comment]
Error should be already fixed, do you have properly set your checklist?
