### ISSUE TITLE
[BUG/Missing] yt-main.html to play YouTube Musics.

### ISSUE THREAD

**Issue by ChisdealHD** [sogehige/sogeBot#1679]
there is missing yt-main.html on 'C:\Users\username\Desktop\sogeBot-master\public\pages\yt-main.html'

This will not make YouTube Player to Execute Music since missing this file.

Error im getting 

Error: ENOENT: no such file or directory, stat 'C:\Users\Chisd\Desktop\sogeBot-master\public\pages\yt-main.html'

BOT Version: SOGEBOT 8.1.5

Issue: YouTube Player not Working or Missing file to make to Work

**Comment by sogehige** [comment]
I can see that ytplayer is not working, fixing for 8.2.0.
Although your error suggest that bootstrap javascript is not loaded properly
