### ISSUE TITLE
!top subage show wrong subs

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1721]
### Actual behavior
I see wrong subscribers in !top subage
What collections you need for reproduce?
i think it's bug
Some users not subscribers, but they are in this list.
If i find this user in dashboard->viewers->user, then he is not subscriber
![img](https://i.imgur.com/NcEDr8X.png)
### Additional informations

master https://github.com/sogehige/sogeBot/commit/b8e2a00ef7fb2a7949755e894174b1b2658984c9

**Comment by sogehige** [comment]
It's currently sorted by subscribed_at although it's not checking if it is
currently sub, will fix

so 12. 1. 2019 6:09 odesílatel Banonevar <notifications@github.com> napsal:
