### ISSUE TITLE
iOS YouTube auto play not working properly.

### ISSUE THREAD

**Issue by ipodtouchdude** [sogehige/sogeBot#1722]
When I play my song playlist it should play the next song after it finishes. But once it finishes it will just stop with the next video loaded and with the YouTube Play button over it. I've tried Safari, Chrome and Firefox and every iOS browser does the same thing.

I've tired on iOS 11.13.1 and 12.1.1

BOT Version: SOGEBOT 8.2.1

**Comment by sogehige** [comment]
Unfortunately I don't have way to test on iOS...I am not sure if I'll be able to fix this

**Comment by sogehige** [comment]
Closing this issue as I don't have way to verify its validity
