### ISSUE TITLE
Chat as bot not sending to chat

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#1748]
Bot is logged in as mod. When using the 'chat as bot' box on dashboard nothing is sent to twitch chat.

**Comment by sogehige** [comment]
Cannot actually reproduce, do you have all correct scopes for bot?

**Comment by chiefstank** [comment]
channel:moderate
chat:edit
chat:read
whispers:read
whispers:edit
channel_editor
channel_commercial
clips:edit
user:edit:broadcast
user:read:broadcast

**Comment by Banonevar** [comment]
may stupid question by me, but does you click enter or big button?

**Comment by chiefstank** [comment]
I click the button

**Comment by sogehige** [comment]
Does bot answering your commands? don't you have enabled debug console in config,json?
