### ISSUE TITLE
Twitter Integration Not Working

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#1749]
Added all Twitter API information and sending a tweet doesn't work. There are no messages anywhere except for the following in the log.

```
2019-01-17T11:56:49.317 | TWITTER: Client connected to service
2019-01-17T11:56:49.317 | ENABLED: Twitter (integrations)
```

**Comment by sogehige** [comment]
Are you trying to send tweet with links? This may be issue and may be just removed by twitter

**Comment by chiefstank** [comment]
I tried sending a tweet only with the word 'TEST BOT'

I can't try again because the widget is gone and missing from ADD WIDGET menu.

**Comment by sogehige** [comment]
There is no Twitter widget anymore

pá 25. 1. 2019 19:16 odesílatel chiefstank <notifications@github.com>
napsal:

**Comment by chiefstank** [comment]
How am I to test again then?

**Comment by sogehige** [comment]
You can send tweets through events

pá 25. 1. 2019 19:24 odesílatel chiefstank <notifications@github.com>
napsal:

**Comment by chiefstank** [comment]
Ahh, okay. Didn't know about that. You can close this then. May bad.
