### ISSUE TITLE
!me shows nothing

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1770]
### Actual behavior
Bot just not show any data
chat:
```
user: !me
bot: $rank
```
### Steps to reproduce
I have custom langs, maybe it can cause my problem.
### Additional informations

Mongo/nedb no difference, master https://github.com/sogehige/sogeBot/commit/c3262c2c44a99828ad4bc4434e50571940a0faed

**Comment by Banonevar** [comment]
I know what is issue. 
Issue is i have disabled rank system.
So need check does system enabled.

**Comment by sogehige** [comment]
Disabled rank system should not disabled !me

pá 1. 2. 2019 5:42 odesílatel Banonevar <notifications@github.com> napsal:
