### ISSUE TITLE
Terser v3.16.0 breaks terser-webpack-plugin

### ISSUE THREAD

**Issue by sleeplesscoder** [sogehige/sogeBot#1784]
### Expected behavior
Project builds cleanly
### Actual behavior
Project build borks on Terser minify step
### Steps to reproduce
clean checkout and build
### Additional informations
The latest terser update breaks terser-webpack-plugin plugin.

Link to plugin bug report:
https://github.com/webpack-contrib/terser-webpack-plugin/issues/66

**Comment by sleeplesscoder** [comment]
A temporary work around until Terser fix the breaking change:
npm install terser@3.14.1 --save-dev

**Comment by sogehige** [comment]
Yeah thanks, I added it in known issues on discord, we can keep it here as well
