### ISSUE TITLE
Make subs immune for links timeouts

### ISSUE THREAD

**Issue by Satont** [sogehige/SogeBot#184]
Make subs will not be moderated for links

**Comment by sogehige** [comment]
Will be toggable in moderation configuration

**Comment by Satont** [comment]
Missed for blacklist

**Comment by sogehige** [comment]
Missed for blacklist what?

**Comment by Satont** [comment]
subcribers punishment

**Comment by sogehige** [comment]
Blacklist currently doesn't have option to enable/disable (enabled by default) subscribers timeout, if you want that feature, create new issue
