### ISSUE TITLE
crush 

### ISSUE THREAD

**Issue by Satont** [sogehige/SogeBot#188]
Bot version: latest

Node.js version: 7.7.4

Npm version: 4.1.2

Does node_modules folder remove and npm install solved issue?: nope

Issue description: crush

![img](https://satont.xyz/s/s21.png) 
[exceptions.txt](https://github.com/sogehige/SogeBot/files/924123/exceptions.txt)

**Comment by sogehige** [comment]
How much ram is used by a bot? How much ram is available?
