### ISSUE TITLE
Tips NaN issue

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1939]
### Actual behavior
I have got 500rub for last stream, and bot dashboard shows it like 
![img](https://i.imgur.com/32ReGVU.png)
### Steps to reproduce
Tell me what you need for that and i will send
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/61bd658ce243c8d5a831086d0f627418ea1853a1, mongodb

**Comment by sogehige** [comment]
Can you share stats collection?

**Comment by Banonevar** [comment]
[stats.zip](https://github.com/sogehige/sogeBot/files/2899354/stats.zip)
