### ISSUE TITLE
Wrong watched time count

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1947]
### Actual behavior
Before stream i flushed users.watched time (not from dashboard, i droped this collection)
And after 7h of stream some users have not normal watched time, like 
``` 
1. @user - 201.5h, 2. @user -
187.3h, 3. @user - 136.8h, 4. @user - 134.0h, 5. @user - 134.0h, 6. @user - 119.5h, 7. @user - 94.0h, 8. @user - 82.3h, 9. @user - 80.8h, 10. @user - 67.3h
```
### Additional informations

Mongodb, master https://github.com/sogehige/sogeBot/commit/61bd658ce243c8d5a831086d0f627418ea1853a1

**Comment by Banonevar** [comment]
```
first user from top: { "_id" : ObjectId("5c70d6967da491fd05dc911b"), "id" : "", "watched" : 1066500742 }
second: { "_id" : ObjectId("5c70e20a7da491fd051ef07c"), "id" : "173251445", "watched" : 1086300000 }
```

**Comment by sogehige** [comment]
No idea what problem is from that description, please use steps to reproduce and describe problem step by step.

**Comment by Banonevar** [comment]
I removed `users.watched` collections, restarted bot, stream online 7 hours, i just check !top time, and i see that situation, after flush this collection users have not normal wachted time
I not really steps to reproduce, but it happens after i update bot to workers instead of clusters

**Comment by Banonevar** [comment]
Problem is: user have to much time for 7h of stream.. as i said i flushed this collection before stream, and 7 hours left, i check top time, users have more then 100h

**Comment by sogehige** [comment]
When you were removing users.watched was bot stopped?

**Comment by Banonevar** [comment]
I think its possible bot was runned at this moment, gues it was my issue
