### ISSUE TITLE
Give points on event not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1953]
### Actual behavior
1) i have renamed !points add to !some add
2) i have an event, and i add operation `!some add $username 100`
3) i click test on event, and i see message in chat, bot says this command incorrect, use !some add [username] [amount]
4) also not on tested (i mean on real users) users not got points
So, by this steps, it's just not working correctly
### Steps to reproduce
Add some `!points add $username 100` on some event and test it
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/92b0bd4709d58503b3933f8a85cb4954a52afeca

**Comment by sogehige** [comment]
What event are you using?

**Comment by Banonevar** [comment]
sub, resub, subgift

**Comment by Banonevar** [comment]
hm, now it working, but please hold my issue, i will close it by myself, because i not sure it's 100% working
