### ISSUE TITLE
\n in (api) request not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1989]
### Actual behavior
Bot not understand \n in (api) filter request
For example i use it like:
1) i have event stream started
2) operation: send message in chat
3) in this message i use api filter:
`(api|https://url.com/?param=$title\nanother string`
And bot not send api request, he just send whole text of operation in chat
### Steps to reproduce
Create some event, and try send api request with \n
### Additional informations

Master 9078f82dd4518386e50b7427af4879839106b35e

**Comment by sogehige** [comment]
You must escape your param, like

`(api|https://url.com/?param=$title\\nanother string`
