### ISSUE TITLE
Use huminizeDuration for any duration of time in bot

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2022]
My issue more like feauture request, or suggestion, idk.
Check out this package https://www.npmjs.com/package/humanize-duration, this one awesome package, what do the best translation for duration, it can be very useful for us, example  for russian, czech languages, because in russians we have many translations for minutes, days, hours, and this package did nice stuff.
I leave it here, but i can move it to ideas.sogebot.xyz, pls, check out this package

**Comment by sogehige** [comment]
No, we are using luxon

**Comment by Banonevar** [comment]
Then not sure you implement this everywhere
