### ISSUE TITLE
403 on !title set

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2051]
### Actual behavior
i trying to use `!title set` but i can't, i see that error
`!!! ERROR !!! API: https://api.twitch.tv/kraken/channels/123456789- Request failed with status code 403`
My bot is channel editor, all scopes is green
![img](https://i.imgur.com/vIr6OI0.png)

**Comment by sogehige** [comment]
Is any other titles set? Sometimes twitch doesn't allow certain titles. Is
bot editor?

Dne čt 21. 3. 2019 5:49 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
1) others not 
2) yes, bot editor

**Comment by sogehige** [comment]
Then check error in API stats

Dne čt 21. 3. 2019 9:36 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Seems like it was some twitch error, now it's works
