### ISSUE TITLE
Some weird behavior with permissions

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2054]
### Actual behavior
I use command some command, what setted for viewers
```2019-03-23T13:39:09.077 <<< !hug дауна [username]
2019-03-23T13:39:10.340 !!! ERROR !!! Error: User undefined doesn't exist
at Permissions.Error (/root/bots/bot/src/bot/permissions.ts:125:15)
```
but bot give me that error
### Steps to reproduce
I have no idea..
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/55e880404d90ed6ba2fc0409216d155a939c3f67, nedb

**Comment by Banonevar** [comment]
u found me in db, and i have id, but i noticed im twice in db

**Comment by sogehige** [comment]
Is it still relevant?
