### ISSUE TITLE
More Response Filter commands: Age 

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#206]
would be great to have a way to have viewers to check their age (user can check streamer account age) via custom command which i can just simply add "(age)".

**Comment by sogehige** [comment]
So, to clarify this. You want to have returned when (or how long) was channel created, right? I am thinking if it is not better to use and create !age command for this

**Comment by Ayysir** [comment]
That as well. Similar to how you have !followage

**Comment by sogehige** [comment]
I will not add (age) filter (doesn't have followage filter as well)
although added `!age <optional-username>` where user can check age of his account or account of <optional-username>
