### ISSUE TITLE
UI Bug on Timers

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#2075]
sogeBot Version: 8.4.1

On the UI under Timers and then I select my timer group to edit. I have about 8 responses and the "Add a response" button is covered by the other responses and makes it difficult to add new ones.

**Comment by sogehige** [comment]
Can you post a screenshot please?

**Comment by sogehige** [comment]
What browser?

**Comment by ic3dr460n** [comment]
Sorry, browser is firefox. I will also test in Chrome since I know it works better there. Firefox just works better since I can mute by the tab.

Also when editing the top response I can't read the full thing. 

![image](https://user-images.githubusercontent.com/32691495/55281152-aa162d00-5306-11e9-8bd2-b6f72cf6ed88.png)

**Comment by sogehige** [comment]
I can reproduce it on FF, CHrome is OK, will try to fix it though
