### ISSUE TITLE
Run script every variable every X not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2085]
### Actual behavior
I setted an variable script run every 1h, but seems like this variable was never runned 
![img](https://i.imgur.com/7Bfe40A.png)
### Steps to reproduce
Create some script variable and set it run every X

**Comment by sogehige** [comment]
Try to set proper permission if it will work

Dne pá 5. 4. 2019 18:01 uživatel Banonevar <notifications@github.com>
napsal:
