### ISSUE TITLE
Event Listener chat responses being appended with " contenteditable="false

### ISSUE THREAD

**Issue by wgomeringer** [sogehige/sogeBot#2098]
### Expected behavior
When setting up an Event Listener to welcome users to chat, the response should be in the format: {text string} $username

### Actual behavior
When setting up an Event Listener to welcome users to chat, the message is appended with " contenteditable="false. So for example if I set the chat message to Welcome $username I get

Welcome to the chat @{username}" contenteditable="false

### Steps to reproduce
1. On the Web UI navigate to Manage->Event listeners and click the + sign to add a new Event listener. Give it a name, in this case I named it Viewer Welcome
2. The event should be "user joined a channel," though it seems any event displays this behavior
3. Operation should be "send a chat message"
4. Message to send: Welcome $username
5. Save Changes
6. Go back into the Viewer Welcome listener and note the Message To Send field. It has appended " contenteditable="false to $username. Sending a test message results in something similar to:
bot: Welcome to the chat @BoringPepperonis" contenteditable="false

### Additional information

I'm not getting any debug info. I've set in config.json

 "debug": {
    "__COMMENT__": "DON'T ENABLE THIS UNTIL YOU KNOW WHAT YOU ARE DOING!",
    "all": true,
    "console": true
  }

and also enabled in chat with !_debug. All I'm seeing in the logs is:

2019-04-09T11:34:37.968 >>> !_debug [emperordessbot]
2019-04-09T11:36:21.522 >>> Welcome @someFreakingLongUsername" contenteditable="false [someFreakingLongUsername]

I've been trying to debug this myself, but I haven't gotten far. I'm focusing on

$ grep -R -i "fire: this.fireSendChatMessage"
src/bot/events.ts:      { id: 'send-chat-message', definitions: { messageToSend: '' }, fire: this.fireSendChatMessage },
dest/events.js:      fire: this.fireSendChatMessage

Let me know if there is anything else I can look at/provide. Willing to do the work and create a pull request if I can figure out what's going on. 

I updated today to the latest from git: 
$ git describe --tags
8.4.1-64-gd9aec3bc

It's also entirely possible that I am just setting this up incorrectly... Thanks for your time and your work on sogeBot.

**Comment by sogehige** [comment]
Thanks for detailed issue!!!

This is known issue for Firefox, use **Chrome** please. Note that Chrome is *only* supported browser for now.

Also I am (slowly) redoing UI elements to not use contenteditable causing this, e.g. new event listeners UI in upcoming 9.0.0.

Let me know if Chrome solved your issue.

**Comment by sogehige** [comment]
As part of workaround, try to create new event solely in Chrome, not sure how it will behave with contenteditable=false when saved before in firefox

**Comment by wgomeringer** [comment]
Ah, excellent. Glad to know it's a simple fix. Thanks for the quick update. Tested in Chrome, simply edited the event to remove " contenteditable="false, saved, and fired off a test message, response was:

Welcome @someFreakingLongUsername [someFreakingLongUsername]

Works for me. Thanks!

**Comment by sogehige** [comment]
Closing, 9.0.0 released with new UI
