### ISSUE TITLE
When gambling $pointsName will print out the amount of points and Name, e.g. "You now have 4000 4000Name"

### ISSUE THREAD

**Issue by wgomeringer** [sogehige/sogeBot#2100]
### Expected behavior
When gambling the message printed out for your winnings/losings should be in the format

>>>@username, you WON/LOST! You now have 4000 {whatever you named your points}

In my case, being from Philly, I named my points jawn|jawns (https://www.urbandictionary.com/define.php?term=Jawn)

Here is what a sample run should look like:

emperordesslok: !gamble 20
emperordessbot: you LOST! You now have 4650 jawns

### Actual behavior

emperordesslok: !gamble 20
emperordessbot: you LOST! You now have 4650 4650Name

### Steps to reproduce
I used Chrome this time, though it was previously setup in Firefox. I disabled points and gambling in Chrome, shut down and restarted the bot, went back into Chrome and re-enabled points and gambling just to make sure it wasn't something left over from using Firefox. 

1. In the WebUI go to Settings -> Games and enable Gamble
2. Set your Minimal Bet and Chance to win, save
3. Next go to Settings -> Systems -> Points and set that up, save

### Additional information

Again, I'm not getting anything with the !_debug command for some reason. However, to debug this I ended up just changing the variable name of $pointsName to $NameOfPoints everywhere using:

$ find . -type f | xargs sed -i 's/pointsName/NameOfPoints/g' 

then shutting down and restarting the bot. On my next run I got this:

emperordesslok: !gamble 100
emperordessbot: @emperordesslok, you LOST! You now have 4550 jawns

So at first glance this seems to be related to responses that are in the format of $points $pointsName where for some reason the points in $pointsName is picking up the actual value of $points and then just appending Name, if that makes sense. Willing to perform more debug if needed. I also created a diff of the patch, but I figure if it turns out that my bug report is valid (and not a case of once again using the wrong browser, originally.. my bad) then you could simply run the find command I ran above. 

Thanks again for an awesome bot

**Comment by sogehige** [comment]
Thanks for report!

**Comment by sogehige** [comment]
Will be fixed in 9.0.0
