### ISSUE TITLE
makefile requires some fix

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2123]
https://github.com/sogehige/sogeBot/blob/a9d16de41c29e6272f61fa4f9532b31ea05ac9f2/Makefile#L6

If user will run `make` w/o installed node_modules in folder, then `tslint` will not work

Need update it for something like that
```make
all : clean prepare dependencies tslint shrinkwrap ui bot info
```

**Comment by sogehige** [comment]
https://github.com/sogehige/sogeBot/pull/2126
