### ISSUE TITLE
every-x-minutes-of-stream not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2124]
### Actual behavior
For some reason, i noticed `every-x-minutes-of-stream` event not working
I have 2 events, one setted every 20 minute, other every 60 minute. Both not working
### Additional informations

possible test that event

Mongodb, master https://github.com/sogehige/sogeBot/commit/a9d16de41c29e6272f61fa4f9532b31ea05ac9f2

**Comment by sogehige** [comment]
Can you provide affected events collections?

**Comment by Banonevar** [comment]
[Desktop.zip](https://github.com/sogehige/sogeBot/files/3083871/Desktop.zip)
