### ISSUE TITLE
!points add not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2134]
### Actual behavior
I have renamed !points add to !mp add, and this command always sayd me that i use it incorrect:
!mp add username 123
### Steps to reproduce
Rename `!points add` to something another and test it
### Additional informations

master https://github.com/sogehige/sogeBot/commit/b2b52347c5eab31965e19afa36cf39e521ebcf25

**Comment by sogehige** [comment]
Cannot reproduce
```
2019-04-20T14:33:38.026 <<< !mp add [soge__]
2019-04-20T14:33:38.572 >>> Promin, @soge__, ale tento prikaz neni spravne, pouzij !mp add [username] [amount] [soge__]
2019-04-20T14:33:44.231 <<< !mp add soge__ 100 [soge__]
2019-04-20T14:33:44.374 >>> @soge__ ziskal 100 UEC! [soge__]
```

**Comment by sogehige** [comment]
is user which you want to send points in db?

**Comment by Banonevar** [comment]
Yes

**Comment by Banonevar** [comment]
I can attach affected db

**Comment by Banonevar** [comment]
[Desktop.zip](https://github.com/sogehige/sogeBot/files/3100164/Desktop.zip)
id: 149941274

**Comment by sogehige** [comment]
What user is affected?

**Comment by Banonevar** [comment]
id: 149941274

**Comment by sogehige** [comment]
Is this still an issue? I cannot reproduce it

**Comment by Banonevar** [comment]
Seems like not.
