### ISSUE TITLE
Song request volume resetting on next song

### ISSUE THREAD

**Issue by hypertjs** [sogehige/sogeBot#2154]
When you add a song to the queue and change the volume, all is good.
However, if you skip the song or it goes to the next one, the volume level resets.

Would like for it to stay the same if possible.

**Comment by sogehige** [comment]
Volume is changing by track loudness which should ensure that songs plays
with same volume

Dne ne 28. 4. 2019 0:43 uživatel hypertjs <notifications@github.com> napsal:
