### ISSUE TITLE
Remove bots from !top commands

### ISSUE THREAD

**Issue by hypertjs** [sogehige/sogeBot#2155]
Since sogeBot tracks everyone, it's going to track other bots as well.
I would like an option to disable certain bots (maybe a list?) so they don't gain points/time or not show up on the !top commands.

**Comment by sogehige** [comment]
You can add users to ignore list

Dne ne 28. 4. 2019 2:45 uživatel hypertjs <notifications@github.com> napsal:

**Comment by hypertjs** [comment]
You are right, that works!

I thought the ignore section was to ignore commands from people.
