### ISSUE TITLE
warning twitch-js > uws@10.148.2: New code is available at github.com/uNetworking/uWebSockets.js

### ISSUE THREAD

**Issue by gOOvER** [sogehige/sogeBot#2173]
On install / Upgrade i get this warning:

warning twitch-js > uws@10.148.2: New code is available at github.com/uNetworking/uWebSockets.js

see also: https://npm.taobao.org/package/uws

https://github.com/uNetworking/uWebSockets.js

**Comment by sogehige** [comment]
This is not a problem or an issue. Also this is twitch-js dependency, so if needed you should create issue there
