### ISSUE TITLE
Vytváření skupin a jejich oprávnění

### ISSUE THREAD

**Issue by Bazimek** [sogehige/sogeBot#218]
Vytváření uživatelských skupin, které by šli zobrazit za příkazu !skupina (!group). Do těchto skupinby šlo přidávat lidi a nebo by se to tam přidávalo automaticky po bitech třeba a vytváření příkazů pro určité skupiny.

**Comment by sogehige** [comment]
I am thinking about this feature, if it is worth to have. What is use case for this?

**Comment by sogehige** [comment]
We have dynamic permissions for 9.0.0
