### ISSUE TITLE
Improvement price system

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2198]
My issue more like Improvement request, not feature reqeust.
I suggest do something, we have one thing right now.
Right now if command on cooldown, and command have price, user will lost points anymore on command call. It's not good, doesnt right?
I just suggest `friend` that systems, so that they understand each other

**Comment by sogehige** [comment]
It's planned to have rollback if cooldown fails

Dne ne 19. 5. 2019 16:15 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Or yea, rollback is good too
