### ISSUE TITLE
Give points on tip not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2219]
### Actual behavior
I have tip event with `send command` operation
But my `points add` renamed to `mp add`
I use it like `!mp add $username (math.3*$count)`
But it's not working, just nothing happens on tip.
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/754d2eb698ff23e7724fc897b6ca259586525810

**Comment by sogehige** [comment]
yes, `$count` is not supported, its `$amount`

**Comment by Banonevar** [comment]
Oops, sorry, my mistake.
