### ISSUE TITLE
Need help with messaging viewers each minute

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2226]
Hi, does it possible?
16:10 Bot: VIEWERS: 50 (+5)
16:11 Bot: VIEWERS: 45 (-5)

Where +5 -5 it's difference beetwen previous check

**Comment by sogehige** [comment]
Yes, it is possible, you can use
`_.get(await global.db.engine.findOne('api.current', { key: 'viewers' }), 'value', 0)` to get viewers value

**Comment by Banonevar** [comment]
Well, i want it throught variables or something like that, i not want write system for that

**Comment by sogehige** [comment]
No, you cannot do that

Dne st 29. 5. 2019 15:59 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by sogehige** [comment]
Maybe through custom variables, you should be able to access current
viewers and you can access old variable value

Dne st 29. 5. 2019 16:00 uživatel Soge Hige <sogehige@gmail.com> napsal:

**Comment by Banonevar** [comment]
But how i can change variable in script variable?

**Comment by sogehige** [comment]
something like that should work for you
```
let diff = 0
if (_current && _current.length !== 0) {
  const match = _current.match(/VIEWERS\((?<viewers>\d+)\)/)
  diff = stream.currentViewers - match.groups.viewers
}

return 'VIEWERS(' + stream.currentViewers + '): ' + diff;
```

**Comment by sogehige** [comment]
Then add variable to timer system

**Comment by Banonevar** [comment]
Sometimes it shot 
```
TypeError: Cannot read property 'groups' of null
    at evaluation (evalmachine.<anonymous>:14:40)
    at evalmachine.<anonymous>:17:62
    at Script.runInContext (vm.js:134:20)
    at Script.runInNewContext (vm.js:140:17)
    at Object.runInNewContext (vm.js:306:38)
    at safeEval (/root/bots//node_modules/safe-eval/index.js:24:6)
    at CustomVariables.safeEval [as runScript] (/root/bots//src/bot/customvariables.js:240:13)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at Socket.<anonymous> (/root/bots//src/bot/customvariables.js:59:27)
```

**Comment by sogehige** [comment]
sometimes is when? what is var value before script run

**Comment by Banonevar** [comment]
first normal second not
https://i.imgur.com/SwdcAG2.gifv

**Comment by sogehige** [comment]
Because you added space...

**Comment by sogehige** [comment]
You need to update regexp if you are changing output

**Comment by Banonevar** [comment]
Oh lol it's really working w/o space.. 
But it seems hard to customize

**Comment by Banonevar** [comment]
And seems like when viewers change in the positive side, here is no `+` symbol
i mean if if it negative it has `-`
If positive it has only number `1` (for example)

**Comment by sogehige** [comment]
Well it's example

Dne st 29. 5. 2019 17:58 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Well, now i know about _current, and i can do whatever i want, thanks
