### ISSUE TITLE
var bags if in 1 string mroe then 1 var

### ISSUE THREAD

**Issue by Satont** [sogehige/SogeBot#223]
if i have 2 vars in 1 string then its working like:
me: !howmmr
Bot: mmr mmr
but i have respone like (var.mmr1) (var.mmr2)
it should be like
Bot: mmr mmr2

**Comment by sogehige** [comment]
Hmm, cannot reproduce

**COMMANDS**
1	!test	(var.mmr1) (var.mmr2)	
2	!mmr1	(set.mmr1)	
3	!mmr2	(set.mmr2)

**CHAT**
10:10  soge__ : !mmr1 100
10:10  soge__ : !mmr2 test
10:10  soge__ : !test
10:10  SOGE__BOT : 100 test
