### ISSUE TITLE
Some bug with my own systems

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2242]
I noticed one thing..
In system "first" i have something like that
```
const settings = {
      enabled: false,
      token: ''
}
```
And i use `await this.settings.token` for get this token.
So, in system named `second` i have same property name 
```
const settings = {
      enabled: true,
      token: ''
}
```

And, when i set token in second system, first system want to use this token, so bot trying use it by property name.

**Comment by Banonevar** [comment]
For reproduce you need create 2 similar systems with same settings i think

**Comment by sogehige** [comment]
That should not happen unless you have same name in both systems

**Comment by Banonevar** [comment]
You mean class names? No, they are not same

**Comment by sogehige** [comment]
Ok, I'll try to reproduce it then, thanks

**Comment by sogehige** [comment]
Also just sidenote: you don't need to use `await`

**Comment by Banonevar** [comment]
Once you said me use `await property` if i want get value of property, and use just `property = 'newvalue'` if i want assign

**Comment by sogehige** [comment]
long time ago ;)

**Comment by sogehige** [comment]
As expected, this is working ok, two systems with same settings, original value of second system is not changed

#################
        32fdc587-041d-4606-ba39-abbcbae085a8
        original value

#################
        fef41797-ab57-439d-a00b-02ec5527a806
        original value

#################
        fc8557cf-04bb-4efe-bcc0-1aa22a4698d0
        original value

#################
        d3c949a6-68f1-4f14-ab7d-8b5a7554c7d9
        original value

#################
        1cff9425-f39f-4143-8948-9c7951770bbb
        original value

#################
        2c8b1490-b3a6-4fa3-b9a0-494ee6ade00b
        original value

#################
        71a7e69b-57ba-484a-9e73-6501f1403ded
        original value

#################
        d020e93f-cf36-4f59-bb53-135b3b090fe6
        original value

#################
        6dad6057-e808-4f52-bfe1-673d49336a61
        original value

#################
        a89259e3-2d10-41cd-b49e-76fcbde59418
        original value

#################
        f8edf2a2-8b31-4b54-8040-409410b67534
        original value

#################
        20342055-56f6-4469-bccc-e66bee130e1a
        original value

#################
        5736d665-e1d4-40a0-8c3d-3cc494d8e0ed
        original value

#################
        4bea40af-f657-4366-8e5b-b8e6b15a398d
        original value

2019-06-11T10:28:34.149 | EMOTES: Fetched global emotes
#################
        5e9b1003-65f7-4d54-af3a-33808ed5c629
        original value

#################
        7b6956e8-0874-4f3b-81c1-17eadf6d93df
        original value

#################
        2533c946-37e8-4e57-a71d-6dc75057d907
        original value

#################
        05123a28-ae35-4e57-8d88-9077b6e5a4e3
        original value

#################
        faedee1a-cc29-4e1b-b736-a05cb5d71486
        original value

#################
        827dab59-97ad-4f60-b4d0-e3a267e7bffa
        original value

#################
        225978e2-fe63-4c71-a416-892cb764ede5
        original value

#################
        45458ab9-7092-41b9-9f65-751993f17017
        original value

#################
        5a8ddfb6-672d-4c73-aa89-db17aecc4fa9
        original value

#################
        8bfae702-02a5-4429-82b0-42068977e7e1
        original value

#################
        c70603eb-47dd-4ca7-8fb8-faede4afd841
        original value

#################
        eb7e12f2-116e-4361-a1b7-d6e6f318583c
        original value

#################
        cefa4a34-3f55-4f1c-96ab-6cb361eb7483
        original value

#################
        59e6cf65-8981-4629-a447-2d62e2ec12b3
        original value

#################
        5c88f516-086f-41cc-b085-3b1886f9e588
        original value

#################
        00becddc-5062-4d10-8c1c-1700b2ef29d0
        original value

#################
        071f0cf3-49be-4ff3-ba2d-d1d9c6c83978
        original value

#################
        75668359-f17c-4a41-8d79-a848fa1b03a2
        original value

#################
        99113242-485e-4c5f-a0eb-4b2e0c697582
        original value

**Comment by Banonevar** [comment]
I not said it change for both systems, i said first system read property from second system

**Comment by sogehige** [comment]
example? No idea what you mean

**Comment by Banonevar** [comment]
I attached same settings in first message, and `first` system use `token` from `second` system

**Comment by sogehige** [comment]
Well, thats not enough to understand a problem. tokens are not overwritten by each other aand each system have own token...

**Comment by Banonevar** [comment]
First system
```
const settings = {
      enabled: false,
      token: ''
    }
```
and i got token by `let token = await global.db.engine.findOne(this.collection.settings, { key: 'token' })`

In second system, what is itegration btw, not system.
```
const settings = {
      enabled: false,
      token: ''
    }
```
And i got token by `let token = await this.settings.token`

**Comment by sogehige** [comment]
well yes, thats not correct `settings` collections are shared. This is not correct way. You should just use `this.settings.token` or `global.systems.seconds.settings.token`

**Comment by Banonevar** [comment]
ok, thx for helping :)
