### ISSUE TITLE
List of bots to add to global ignorelist

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#2244]
Please, add here bots which will be in bot ignorelist

**Currently ignored bots:**
_none_

**Comment by sogehige** [comment]
commanderroot
martinnemibot
electricallongboard
lurxx
apex_pro_community

**Comment by Banonevar** [comment]
P0lizei_
Anotherttvviewer
Cachebear
Cyclemotion

**Comment by sogehige** [comment]
freddyybot

**Comment by Banonevar** [comment]
communityshowcase
decafsmurf
stay_hydrated_bot
xanbot
nowsongbot
streamelements
thronezilla
electricallongboard
moobot
nighbot
electricalskateboard
commanderroot
host_giveaway
p0sitivitybot
slocool
p0lizei_
inagawasenpai
soulemptiness
bananennanen
teyyd
vivbot
unixchat
lurxx
apricotdrupefruit
avocadobadado
s1faka
jodja1337
anotherttvviewer
undefined_ninja
freddyybot
konkky
bloodlustr
cyclemotion
zanekyber
cachebear

**Comment by hypertjs** [comment]
nightbot
hnlbot
ohbot
wizebot
coebot
branebot
monstercat
curseappbot
revlobot
muxybot
faegwent
fatmanleg
wormy_official
virgoproz
v_and_k
0_applebadapple_0
skinnyseahorse
lanfusion
PretzelRocks
philderbeast
not47y
mwmwmwmwmwmwmwmmwmwmwmwmw
stayhealthybot
yghosttown
alphaduplo
jacksere
21wolv
Energyzbot
Poklimane
woppes
uhhhspike
aislinnsatu
d__u__c__k__e__r__z
bears_party
ddwithers1
dittys14
feuerehr
streamjar
feuerwehr

**Comment by tarumes** [comment]
https://github.com/tarumes/twitch-ban-list/blob/master/ignore_list.json

**Comment by xTunio** [comment]
> https://github.com/tarumes/twitch-ban-list/blob/master/ignore_list.json

https://github.com/tarumes/twitch-ban-list/blob/master/public_ban.json
fixing invalid link

**Comment by tarumes** [comment]
> > https://github.com/tarumes/twitch-ban-list/blob/master/ignore_list.json
> 
> https://github.com/tarumes/twitch-ban-list/blob/master/public_ban.json
> fixing invalid link

thx missed it to change it here but i think its better to use the repository link because spliting lists in a few days to bots / spam_bots and regular_ban and also keep a combined list

**Comment by sogehige** [comment]
I am closing this issue, if someone is interested, you can create PR for https://github.com/sogehige/sogeBot/blob/master/src/bot/data/globalIgnoreList.ts
