### ISSUE TITLE
Ownsystem bug, emit of null

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2249]
I have my own system with widget and backend system, everything working fine except `this.socket.emit()`

For example in system.js i have:
```javascript
this.socket.on('connection', (socket) => {
      socket.on('slots.get', async (cb) => {
        let items = _.sortBy(await global.db.engine.find(this.collection.slots), 'timestamp')
        cb(null, items)
      })
})
```
And it's working! Widget get data on this cb fine.
But, i can't emit any event to my widget, when i use `this.socket.emit` in some function, for example in command function 
```javascript
@command('!test')
  @default_permission(permission.VIEWERS)
  async test(opts) {
   this.socket.emit('test', { username: opts.sender.username })
  }
```
I got `<rejected> TypeError: Cannot read property 'emit' of null`
So i think something in interface is bugged.

**Comment by Banonevar** [comment]
Still have this issue after https://github.com/sogehige/sogeBot/commit/d437a0a9d6d4bc84bef947637b1203c0681d84d6 refactor

**Comment by sogehige** [comment]
Thats because it should not fixed it

**Comment by sogehige** [comment]
@Banonevar please share your full code

**Comment by Banonevar** [comment]
I has like 1000 strings in code

**Comment by Banonevar** [comment]
PM'ed in discord

**Comment by sogehige** [comment]
socket may be initialized later, to overcome this

```
    if (this.socket === null) {
      return setTimeout(() => this.yourFnc(opts), 100)
    }
```

on start of your command function

**Comment by sogehige** [comment]
After PR merge you should use in your commands `this.emit` instead of `this.socket.emit`

**Comment by Banonevar** [comment]
Now sometimes just nothing happens on `this.emit`
