### ISSUE TITLE
systems/bets: refactor bets

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#227]
- Add support for multiple words as a bet
`!bet open option | second option | third option`
`!bet 1 100` where 1 is option index
- Add widget graph how many users are betting on each option
- bets should have adjustable starting bet message #143
- possibility to create bet from widget
- bets overlay - make games overlay?

**Comment by Satont** [comment]
maybe bets must contain bet title? 
!bet open (i will win?) [no yes]
