### ISSUE TITLE
Custom Variable user() function invalid data

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#2271]
`2019-06-18T14:43:54.493 DEBUG: undefined ======= COPY DEBUG MESSAGE FROM HERE ======= 2019-06-18T14:43:54.494 DEBUG: undefined GENERAL | OS: npm/6.9.0 node/v12.3.1 win32 x64 2019-06-18T14:43:54.516 DEBUG: undefined | Bot version: 9.0.3 2019-06-18T14:43:54.517 DEBUG: undefined | DB: nedb 2019-06-18T14:43:54.518 DEBUG: undefined | Threads: 1 2019-06-18T14:43:54.519 DEBUG: undefined | HEAP: 39.99 MB 2019-06-18T14:43:54.519 DEBUG: undefined | Uptime: 1406.0319461 seconds 2019-06-18T14:43:54.520 DEBUG: undefined | Language: en 2019-06-18T14:43:54.520 DEBUG: undefined | Mute: false 2019-06-18T14:43:54.521 DEBUG: undefined SYSTEMS | customCommands, moderation, points, timers, top, userinfo 2019-06-18T14:43:54.522 DEBUG: undefined GAMES | 2019-06-18T14:43:54.523 DEBUG: undefined INTEGRATIONS | streamlabs, twitter 2019-06-18T14:43:54.524 DEBUG: undefined WIDGETS | eventlist, chat 2019-06-18T14:43:54.524 DEBUG: undefined OAUTH | BOT true | BROADCASTER true 2019-06-18T14:43:54.525 DEBUG: undefined ======= END OF DEBUG MESSAGE =======`

While trying to create a custom variable using the user() command, I noticed that all values in the IS object  are false. Every user I've tested shows the same. I edited the sogebot files to output to the console the user object when the command is entered and have attached that as well. Again, user is a follower, online, and in the viewer DB. This is also with every chat user that has tested the command.

![2019-06-18 14_48_22-SCVODARCHIVESBOT 9 0 3](https://user-images.githubusercontent.com/6421187/59722513-b9579900-91d8-11e9-8508-29f9314acfb0.png)
![2019-06-18 14_50_02-SCVODARCHIVESBOT 9 0 3](https://user-images.githubusercontent.com/6421187/59722517-bb215c80-91d8-11e9-82a2-02f4026fe6e8.png)
![2019-06-18 14_52_15-npm](https://user-images.githubusercontent.com/6421187/59722519-bc528980-91d8-11e9-8a2b-d652a2ad0bdd.png)

**Comment by sogehige** [comment]
you need to use `await user(sender)` It is returning Promise

**Comment by sogehige** [comment]
Although I can reproduce only online state, which is always false, others seems to be working correctly

**Comment by chiefstank** [comment]
I have tried the await in tests days ago, but forgot to add it in issue.

Ok, I've been testing the ONLINE mostly, so that makes sense. Now, I tested again, here are the results. No response in chat due to error.

![2019-06-18 15_06_42-SCVODARCHIVESBOT 9 0 3](https://user-images.githubusercontent.com/6421187/59723251-ce352c00-91da-11e9-8386-cdb8ca81ed8b.png)
![2019-06-18 15_07_09-npm](https://user-images.githubusercontent.com/6421187/59723252-ce352c00-91da-11e9-8c63-5e00113bc848.png)

**Comment by sogehige** [comment]
problem is

`let userInfo` -> `user.is.follower` => `userInfo.is.follower`

**Comment by chiefstank** [comment]
JESUS..... delete this sh!t. Sorry... With the whole online always being false, it was messing with me as that was the main one I was checking.

**Comment by sogehige** [comment]
np, common mistake at work, so I developed good eye for this :P
