### ISSUE TITLE
Moderation system not saved settings

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2283]
### Steps to reproduce
I setted some moderation system, restart bot, and they flushed
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/f6238db375e7912da7ffa77900ae9af8aee64cc2

**Comment by Banonevar** [comment]
It flush whole of settings of this system, not only disabled/enabled

**Comment by sogehige** [comment]
Working correctly after fix commits on nedb/mongodb
