### ISSUE TITLE
Need restart of bot when rename command

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2288]
### Actual behavior
When we rename some command in systems, then we need restart bot
And well, it happens on my own system, not sure about default systems
### Additional informations

Master (https://github.com/sogehige/sogeBot/commit/2ccc2b8ea837899908a755feaaae979dcb623083)

**Comment by sogehige** [comment]
Still seems like to be an issue

**Comment by sogehige** [comment]
First command update OK - second command update is not working
