### ISSUE TITLE
Feature Request: Gifs with mp3 sounds overlay with commands

### ISSUE THREAD

**Issue by Bazimek** [sogehige/SogeBot#229]
Possible for upload a small gif with a mp3 to bot and then make a command which start this gif with same name of mp3 right on the stream overlay for example command !jellybeam = (jellybeam.gif,jellybeam.mp3,10) will start a jellybeam.gif with jellybeam.mp3 for 10 seconds and then dissapear.

**Comment by sogehige** [comment]
Thinking of something more advanced

type - image or audio
time - when should dissapear in seconds
delay - delay of show/play in seconds
position - top-left, top-right, left, center, right, bottom-left, bottom-right

`!overlay type=image url=jellybeam.gif time=10 position=top-left | type=audio url=jellybeam.mp3 time=10`

This can be possibly extended with message type etc (for followers alerts, etc)

**Comment by Deanosim** [comment]
Sorry to bump this old issue, but I can't seem to work out how to get audio commands to work, I just want to be able to make commands that play audio files on stream when people use the commands, is this something that can be done in the webui? Or it is command only? I tried that alias add command you listed as an example above but it just tells be it's not correct.

**Comment by sogehige** [comment]
Can you join our discord server to be able to help you? https://discord.gg/muxZhM Would be good to have more information.
