### ISSUE TITLE
Keywords not doing tolowercase

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2293]
### Actual behavior
Keywords system not doing tolowercase, it's just not trigget 
### Steps to reproduce
Add keyword `test`
Type in chat `TesT`
### Additional informations

master (https://github.com/sogehige/sogeBot/commit/6a14e703513cbd985f85fb70f6180a3ed7ac1a4b)

**Comment by sogehige** [comment]
cannot reproduce, keywords are case insensitive -> see https://github.com/sogehige/sogeBot/pull/2296
