### ISSUE TITLE
Seems like opts wasnt shared beetwen keywords and (!command) filter

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2294]
### Actual behavior
```javascript
@command('!f')
  @default_permission(permission.VIEWERS)
  async f(opts) {
    await sendMessage(opts.sender.displayName, getOwner())
  }
```
I have an keyword, with response `(!f)`
And i got:
`Bot: undefined` in chat
### Additional informations

Master (https://github.com/sogehige/sogeBot/commit/6a14e703513cbd985f85fb70f6180a3ed7ac1a4b)

**Comment by sogehige** [comment]
not sure if I understand

**Comment by Banonevar** [comment]
on keyword fire sender username wasn't transfered to my command

**Comment by sogehige** [comment]
It's not a bug, displayName is not available in sender object, will add it though
