### ISSUE TITLE
Bug: Songs widget doesnt work

### ISSUE THREAD

**Issue by Bazimek** [sogehige/SogeBot#231]
!songrequest -ZWMzn6_SYk .. for example working fine but when i click on a green arrow for play nothing happened. And music dont start playing. But !song show a correct name of song.

**Comment by sogehige** [comment]
it does work for me, do you have song requests enabled?

**Comment by Bazimek** [comment]
Yes i can use !songrequest but i can play them via widget.

**Comment by sogehige** [comment]
I mean in settings->modules

**Comment by Bazimek** [comment]
Yes

**Comment by sogehige** [comment]
Did you removed node_modules? Please for next bugs use https://github.com/sogehige/SogeBot/wiki/How-to-report-an-issue

**Comment by Bazimek** [comment]
Its a clean npm install i cant rewind in widget music too

**Comment by sogehige** [comment]
Browser?

**Comment by Bazimek** [comment]
Still the same chrome

**Comment by sogehige** [comment]
Ok, there is bug with clicking on play button, if dashboard is loaded, click once on play and it should look like ||, then it will play music, several click will cause bug when button is not responding, so I'll fix that
