### ISSUE TITLE
ytplayer widget not workig

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2314]
### Actual behavior
Idk, here is to much issues, you can just try it and you will know everything.. Here is to much bugs
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/96a2fb35b0fb0b7a74f1c771ae2772d6df773cac

**Comment by Banonevar** [comment]
I recorded some video if you want https://www.sendspace.com/file/kuv6gg

**Comment by tarumes** [comment]
this happen only once from a single video in my playlist and i tested it with my own videos. it happen if the uploader uncheck the Allow embedding checkbox in his videos

**Comment by sogehige** [comment]
If it's restricted to play embedded videos it will fail, it's not a bug
it's just natural behaviour from YouTube

Dne so 22. 6. 2019 21:25 uživatel tarumes <notifications@github.com> napsal:

**Comment by Banonevar** [comment]
It's happaning for each video, can you provide some not restricted embedded video for test?

**Comment by Banonevar** [comment]
Yea, i uploaded some video to YT for test, same behavior, also noticed
![img](https://i.imgur.com/BQVficr.png)
