### ISSUE TITLE
Request feature: Different notices for online, offline stream

### ISSUE THREAD

**Issue by Bazimek** [sogehige/SogeBot#233]
Different notices for stream when is online and for stream when is offline without needs messages.

**Comment by sogehige** [comment]
You can do it with (onlineonly), (offlineonly) filters

**Comment by Bazimek** [comment]
Oh filters can be used in notices too? Ok nice! Thank you

**Comment by sogehige** [comment]
For record, all response filters can be used in everything bot is responding, except (set.#) and (var.#) which need arguments -> so it can be used only in custom commands

Also in 1.5.2 I made a fix for notices exactly for this purpose to skip empty notices https://github.com/sogehige/SogeBot/issues/210
