### ISSUE TITLE
Command search for keywords in UI not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2336]
### Actual behavior
![img](https://camo.githubusercontent.com/61e8ef7441c4aed1d59d1531faec7daa2f5ea5e4/68747470733a2f2f692e696d6775722e636f6d2f6f76547944636f2e676966)

**Comment by sogehige** [comment]
I don't understand, seems ok, when you are searching for `kon`, its returning both items because you have `KonCha` in responses.
