### ISSUE TITLE
Opts in my custom system no more working 

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2344]
### Actual behavior
My commands in my own system stoped working with error 
```
 2019-06-28T09:22:39.384 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> ReferenceError: opts is not defined
at Parser.opts [as command] (/root/bots/src/bot/parser.js:228:110)
at processTicksAndRejections (internal/process/task_queues.js:89:5)
} reason: ReferenceError: opts is not defined
```
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/60941e04f21baf53ae65dc8d30802f8589ea9d59

**Comment by sogehige** [comment]
And what do you expect me to do?

**Comment by Banonevar** [comment]
It's stoped working after latest updates, before it was, just all my commands in that system stops working

**Comment by sogehige** [comment]
I am not sure, how can I fix any of this without any informations.

**Comment by Banonevar** [comment]
It's not my own system problem.. It's problem in bot, because i not change my system
