### ISSUE TITLE
[9.2.2] Subgifts is always 0

### ISSUE THREAD

**Issue by tarumes** [sogehige/sogeBot#2363]
Subgifts is always 0 in ViewerList
[Pic 1](https://cdn.discordapp.com/attachments/382927730175508481/595326088540848141/Unbenannt_1.png)
[Pic 2](https://cdn.discordapp.com/attachments/382927730175508481/595326129498488844/Unbenannt_2.png)

**Comment by Banonevar** [comment]
You can attach images via `![img-name](img-link)` hack
