### ISSUE TITLE
!top bits incorrect counting

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2369]
### Actual behavior
!top bits shows incorrect numbers
### Additional informations

master https://github.com/sogehige/sogeBot/commit/0454587099771272fd374900225cc2d109bc3726

**Comment by sogehige** [comment]
I don't see any issues with bits counting

**Comment by sogehige** [comment]
Although there might be possibility of mongodb issue with counting with string, as you didn't specify it is mongodb I assume this is your issue

**Comment by Banonevar** [comment]
Yea im on mongodb, can it be the issue?

**Comment by sogehige** [comment]
Yes, but should be fixed

Dne st 3. 7. 2019 12:34 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by Banonevar** [comment]
Yea fixed
