### ISSUE TITLE
[9.3.0] Change Tags API Error

### ISSUE THREAD

**Issue by tarumes** [sogehige/sogeBot#2371]
### Expected behavior
Set Tags
### Actual behavior
Nothing
### Steps to reproduce
Try to set Tags
### Additional informations
!!! ERROR !!! API: https://api.twitch.tv/helix/streams/tags?broadcaster_id=xxxxxxxxx - Object to update cannot be empty

**Comment by sogehige** [comment]
This error seems to be only when removing all tags, although this error should not be shown, it is working

**Comment by tarumes** [comment]
i try to set "No Backseat Gaming" and "First Playthrough" as Tags and got this error message

**Comment by sogehige** [comment]
That's not possible

**Comment by tarumes** [comment]
i try restarting the bot

**Comment by sogehige** [comment]
This error can happen only if your tags are empty

**Comment by tarumes** [comment]
can be closed after restart its working

**Comment by sogehige** [comment]
Also same error when no tags are changed/updated in ui
