### ISSUE TITLE
Dashboard menu wrong position, and 1 more problem

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2444]
### Actual behavior
Try to open some menu in dashboard, and after you opened this menu, try open another one, here is wrong position and another problem
### Additional informations

next https://github.com/sogehige/sogeBot/commit/15257b8975227b503a360c1acce7623830a92910

**Comment by sogehige** [comment]
What is another problem?

**Comment by Banonevar** [comment]
Well, everything is fine now
