### ISSUE TITLE
YTplayer can't play video

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2451]
### Actual behavior
video was loaded in widget, but cann't be started with that error
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`
### Additional informations

next https://github.com/sogehige/sogeBot/commit/c4f6ba62162a4f1750af2af690562631dcfd27ff

**Comment by sogehige** [comment]
I don't have such issue

**Comment by Banonevar** [comment]
Some extended error:
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at o.heightOfMenuUpdate (main.js:26)
    at main.js:26
```

**Comment by sogehige** [comment]
This is fixed by https://github.com/sogehige/sogeBot/pull/2453

**Comment by Banonevar** [comment]
I noticed when this error happens, then after that i can't order songs.
I type in chat `!songrequest song url` and just nothing happens, if i re-enable system, then i can order song, but got same issues

**Comment by sogehige** [comment]
Those are absolutely unrelated issues
