### ISSUE TITLE
keyword not triggering if match is not exact

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2502]
### Actual behavior
1) i created keyword test
2) it triggering only on `test` matching in chat
3) if i'll use `testq` or `test?` it will not triggered
### Additional informations

next https://github.com/sogehige/sogeBot/commit/c182bb85a1b0d42af839b281a57acec95eaa94e9

**Comment by sogehige** [comment]
`testq` should not match, although `test?` or any other sentence punctuation should

**Comment by Banonevar** [comment]
Ok, then here is:
1) bug with  sentence punctuation
2) question how to trigger on testq

**Comment by sogehige** [comment]
`test(.*)`? You can use regexp

**Comment by Banonevar** [comment]
Ok. You said any other sentence punctuation should, so here is bug? Does you will fix that bug?

**Comment by Banonevar** [comment]
Thx
