### ISSUE TITLE
UI bug of editing alerts

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2528]
### Actual behavior
I have two groups.
i.e names `first`, `second`
And when i trying to edit `first` it opening `second`, and load all `second` settings instead of `first`
### Additional informations

next https://github.com/sogehige/sogeBot/commit/1ed4fe99171794f049989f6a59da0b221dbd6cb6

**Comment by Banonevar** [comment]
URLs in browser is different

**Comment by sogehige** [comment]
Not sure if I understand what your issue is

**Comment by Banonevar** [comment]
It's loading incorrect group.
![](https://i.imgur.com/CW5KxNF.gif)
