### ISSUE TITLE
Alerts registry: not editable variants

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2538]
### Actual behavior
Cannot edit variants after they was created
### Steps to reproduce
1) create some group with Resub variant
2) save
3) open edit page and try to edit message template for that variant
4) you will see validation fails
### Additional informations

next https://github.com/sogehige/sogeBot/commit/4cbc158a00121b1e278177633401b600d48a7315

**Comment by sogehige** [comment]
This is already fixed
