### ISSUE TITLE
Alerts: custom message template broke alert

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2543]
### Actual behavior
1) setted message semplate for resub to `{name} <span class="amount">[{amount}]</span>`
2) setted css ```.amount { color: #ffffff }```
3) on test alert message {messageTemplate} just not exist
Yes i know, i can use {name} {amount} directly in html, but it's still be an issue
### Steps to reproduce
next https://github.com/sogehige/sogeBot/commit/2dca95f172cc2211200e1caaae867cb06ae9f906

**Comment by sogehige** [comment]
you cannot use html in message template
