### ISSUE TITLE
Custom command not triggering with custom variable

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#2598]
### Expected behavior
Custom command name: !requestvod
Custom command response: $_requestvod
Custom Variable name: $_requestvod
Permissions for both are set to VIEWERS. 

Custom variable script will process information and return a response but it is not triggered by chat command. If I test script within custom variable the proper response is set as the value.

### Actual behavior
Entering the command into chat does nothing. 

2019-09-22T08:33:00.003 >>> !_debug [scvo*******]
2019-09-22T08:33:15.604 <<< !_debug [scvo*******]
2019-09-22T08:33:15.676 DEBUG: undefined ======= COPY DEBUG MESSAGE FROM HERE =======
2019-09-22T08:33:15.677 DEBUG: undefined GENERAL      | OS: npm/6.9.0 node/v12.3.1 win32 x64
2019-09-22T08:33:15.716 DEBUG: undefined              | Bot version: 9.7.2
2019-09-22T08:33:15.718 DEBUG: undefined              | DB: nedb
2019-09-22T08:33:15.719 DEBUG: undefined              | Threads: 1
2019-09-22T08:33:15.720 DEBUG: undefined              | HEAP: 56.16 MB
2019-09-22T08:33:15.720 DEBUG: undefined              | Uptime: 51612.202849769 seconds
2019-09-22T08:33:15.721 DEBUG: undefined              | Language: en
2019-09-22T08:33:15.722 DEBUG: undefined              | Mute: false
2019-09-22T08:33:15.722 DEBUG: undefined SYSTEMS      |
2019-09-22T08:33:15.723 DEBUG: undefined GAMES        |
2019-09-22T08:33:15.724 DEBUG: undefined INTEGRATIONS |
2019-09-22T08:33:15.725 DEBUG: undefined WIDGETS      | chat, eventlist
2019-09-22T08:33:15.726 DEBUG: undefined OAUTH        | BOT true | BROADCASTER true
2019-09-22T08:33:15.727 DEBUG: undefined ======= END OF DEBUG MESSAGE =======

**Comment by sogehige** [comment]
Just sidenote: permission is for variable set, not view

**Comment by sogehige** [comment]
Can I have more info? I just have variable `$_csgomap` and that variable is properly and without issues used in custom command

**Comment by sogehige** [comment]
Also I am little confused, this https://github.com/sogehige/sogeBot/issues/2599 mean that you have working custom variable

**Comment by chiefstank** [comment]
Here are screenshots. Nothing changed with either of these two (variable & command) after the upgrade to 9.7.2 from 9.6.0. After the upgrade it stopped triggering.

Command
![2019-09-23 08_38_57-SCVODARCHIVESBOT 9 7 2](https://user-images.githubusercontent.com/6421187/65440595-d1454700-dddd-11e9-9fee-d9405b46d86c.png)

Variable
![2019-09-23 08_38_42-SCVODARCHIVESBOT 9 7 2](https://user-images.githubusercontent.com/6421187/65440596-d1454700-dddd-11e9-8c57-90f67a016768.png)

**Comment by sogehige** [comment]
Is this full screenshot? There are several things missing like variale type and its value

**Comment by sogehige** [comment]
Can you re-do your variable?

**Comment by sogehige** [comment]
Are there any errors in chrome

**Comment by chiefstank** [comment]
I created a new custom variable with the same script and the permissions was set to 'viewer'. Changed the custom command to use the new variable. 

This error in Chrome appeared.

![2019-09-23 09_12_00-DevTools - streampc_23456__id=Uh02z2rabyyijGNV](https://user-images.githubusercontent.com/6421187/65443087-4286f900-dde2-11e9-95c0-976da907a042.png)

**Comment by sogehige** [comment]
Oh I see, its a script....:) will check

**Comment by sogehige** [comment]
I was able to use scripted variable, is variable without slash working for you?

**Comment by chiefstank** [comment]
Another test.

If I send the command in chat with NO parameters, the custom variable script is triggered and returns values. If ANY parameter is added to the chat command nothing happens.

**Comment by sogehige** [comment]
But thats correct behavior of `command` response you have set

**Comment by sogehige** [comment]
actually I would need to check how is command behaving, but you can try default response

**Comment by chiefstank** [comment]
I don't understand. You could send parameters previously with commands with these settings. I'm really confused now.

**Comment by chiefstank** [comment]
My script right now ONLY returns the param value and nothing is returned. If I return a specific value ex. return 'hello' it works.

**Comment by sogehige** [comment]
> I don't understand. You could send parameters previously with commands with these settings. I'm really confused now.

It can be regression, I am just trying to understand what are you doing so I can reproduce

**Comment by chiefstank** [comment]
I get it. So if a parameter is added to the command in chat it doesn't trigger it seems.

**Comment by sogehige** [comment]
Great! https://github.com/sogehige/sogeBot/pull/2604 < this will be fixed

**Comment by sogehige** [comment]
Closing as script eval is working as expected
