### ISSUE TITLE
Alias Not working

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#2606]
I have an alias for the !points command as follows.

![2019-09-23 11_38_21-SCVODARCHIVESBOT 9 7 2](https://user-images.githubusercontent.com/6421187/65452747-a9aea880-ddf6-11e9-9651-17909554daa2.png)

Nothing happens when using !vodcoins, but !points works.

**Comment by sogehige** [comment]
aliases are working, what  permissions have you set?

**Comment by chiefstank** [comment]
Alias permission is set to viewers.

!points command set to viewers.

**Comment by chiefstank** [comment]
I've recreated the aliases I have, there are only two but they still don't work. Once again this was working in 9.6.0 and nothing changed with them after upgrading to 9.7.2. 

The !points command works fine but the alias does not. 

Is there something you can suggest I try?

![2019-09-25 08_47_08-SCVODARCHIVESBOT](https://user-images.githubusercontent.com/6421187/65617242-41380680-df71-11e9-8ccc-d9b1b168958f.png)
![2019-09-25 08_47_32-SCVODARCHIVESBOT](https://user-images.githubusercontent.com/6421187/65617243-41d09d00-df71-11e9-9703-48a8b8aff4d5.png)

**Comment by sogehige** [comment]
Any more info about what exactly are you calling in chat?

**Comment by chiefstank** [comment]
It's simple. I want to the user to be able to type !vodcoins to get their point balance. 

I type into chat !vodcoins and nothing happens. No variables, extra characters, nothing. Only !vodcoins.

**Comment by sogehige** [comment]
![ezgif-3-58f00487f54f](https://user-images.githubusercontent.com/19549652/65618778-2d1af600-dfbf-11e9-9dd5-1eb0626754f3.gif)

**Comment by sogehige** [comment]
other aliases are working? is alias system enabled?

**Comment by chiefstank** [comment]
(this is after the work we did on db btw)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6421187/65622240-1dc58980-df7a-11e9-8b47-75cb78555d01.gif)

no errors in console.

**Comment by sogehige** [comment]
Just checked your db :) just enable alias system :P

`{"system":"alias","key":"enabled","value":false,"_id":"IsBZUFGPCdp0d0e6"}`

**Comment by sogehige** [comment]
I guess we can have some error on manage when system is disabled

**Comment by sogehige** [comment]
btw: not sure if in your version is !_debug fixed, but `!_debug` in chat would show it instantly

**Comment by chiefstank** [comment]
well, wtf... sorry. is that new? i don't remember aliases being there. in any case of course it's working now.

**Comment by sogehige** [comment]
Closing 👍
