### ISSUE TITLE
Cannot create custom command

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2607]
### Actual behavior
Trying to create command through UI.
name: `vk`
response: `https://vk.com/` | permission: viewers
```
2019-09-23T21:08:36.853 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
<rejected> TypeError: Cannot read property 'command' of undefined
at Socket.command (/root/bots/src/bot/systems/customCommands.ts:107:68)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
} reason: TypeError: Cannot read property 'command' of undefined
```
### Steps to reproduce
I don't know.
### Additional informations

master (https://github.com/sogehige/sogeBot/commit/968eacf027eee94c644fd449b3c5bbe5c80f3aa8), mongodb

**Comment by sogehige** [comment]
Cannot reproduce, can create command on mongodb, nedb on latest master

**Comment by Banonevar** [comment]
Does creating of command has debug?

**Comment by Banonevar** [comment]
Can you try create one command, then create another command? seems like after restart i can create one, second bugged.

**Comment by Banonevar** [comment]
Hm, i cannot reproduce it on local machine too.
I can send you whole DB for testing, if you want.

**Comment by Banonevar** [comment]
Reproduced on local machine on mongodb, nedb fine.

**Comment by sogehige** [comment]
still no issue for me, tested like 10 commands with or without responses on mongodb

**Comment by Banonevar** [comment]
Sometimes response creating with null `id`
![](https://cdn.satont.ru/s/dajGeM.png)
And when i trying edit this response, it's moves to another command.
i.e i'm editing command `test1`, after save responses of `test1` moves to `test2`

**Comment by sogehige** [comment]
that mean you dont have latest master

**Comment by sogehige** [comment]
id was fixed 
https://github.com/sogehige/sogeBot/commit/bff131f14d1def6b5aa836982fb00c913044f461

**Comment by sogehige** [comment]
nevermind I've reproduced possibly issue with responses

**Comment by sogehige** [comment]
Fixed by https://github.com/sogehige/sogeBot/pull/2613
