### ISSUE TITLE
[9.8.0] Alerts not playing smooth in OBS Browser source

### ISSUE THREAD

**Issue by tarumes** [sogehige/sogeBot#2656]
### Actual behavior
mp4 video alerts not playing smooth in browser source
if link from media gallery is added direct playback is smooth
### Steps to reproduce
add an trigger a few alerts

**Comment by sogehige** [comment]
Can you give me example of such videos?

**Comment by tarumes** [comment]
https://drive.google.com/open?id=1-lhjDbpRm5W-YuGjIAzLNPC570v11kxn

**Comment by tarumes** [comment]
if i add the parameter duration=<videolength> then it plays without freezing but fades slowly out while playing

**Comment by sogehige** [comment]
Not sure if I understand your issue, you mean like freeze at the end of video?
If yes, that is not a bug, video is fading out **after** it is played. so you need to set lower duration in !alert or fade out in video (e.g. to green and key that out)

**Comment by sogehige** [comment]
And that video you sent me have like 1s freeze at the end itself

**Comment by tarumes** [comment]
if parameter duration=xxxx is missing video freeze at 50%

**Comment by sogehige** [comment]
can you record?

**Comment by sogehige** [comment]
Can you reproduce in chrome?

**Comment by tarumes** [comment]
with duration
https://drive.google.com/open?id=1_kq7xYsaicf1xdKxcRQRXN7lLfru6IDC
without duration
https://drive.google.com/open?id=1i0hUg7_oraCyWvSrw0vBQOiB8h--KI7E

**Comment by sogehige** [comment]
Can you try to reproduce in chrome? any errors?

**Comment by sogehige** [comment]
I had similar report before, but it was due OBS.live installed, do you have obs.live? can you try without it? https://streamelements.com/obslive

**Comment by tarumes** [comment]
OBS Studio 24.0.1

**Comment by sogehige** [comment]
I cannot reproduce, although I'll keep an eye on this as it was reported before to me. There is workaround, so thats good. Thanks for reporting this.

**Comment by tarumes** [comment]
tested with OBS-Studio 23.2.1 no issues looks like something is changed in 24.0.1 keep it open for a while

**Comment by sogehige** [comment]
They updated browser, but it is working for me, maybe something in cache

**Comment by tarumes** [comment]
clean install as always while testing for Bot & OBS

**Comment by sogehige** [comment]
Even clean install can have something in %appdata% cache

**Comment by sogehige** [comment]
Closing, moved resolution to https://community.sogebot.xyz/t/solved-alerts-not-playing-smooth-in-obs-browser-source/21
