### ISSUE TITLE
More functions for YT player

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#272]
Something like:
1) list of songs
2) prev and next song
3) simply del song from list (x) 
4) maybe control volume bar (if it possible)
And e.t.c (idk)

**Comment by Satont** [comment]
also more commands for songrequest
1) wrongsong
2) bot will not cd command if adding song was failure
3) nextsong

**Comment by sogehige** [comment]
Several features are already done, if there is still request for some features ideas.sogebot.xyz
