### ISSUE TITLE
Receiving "invalid csrf token"

### ISSUE THREAD

**Issue by JesseFST** [sogehige/sogeBot#2741]
So, after upgrading and trying to view my bot page (which is LAN accessible ONLY), I receive this after trying to authorize with Twitch.
"invalid csrf token"
I've never had this before, fix it.

**Comment by sogehige** [comment]
What exactly are you trying to do?

**Comment by JesseFST** [comment]
Login to the web dashboard (on port 20000).

**Comment by sogehige** [comment]
ok, what exact errors do you have? on what page? did you login on twitch?

**Comment by JesseFST** [comment]
I've figured it out.  It was on Twitch's oauth (login) page after logging into Soge Dashboard.  I got a json that read the error "invalid csrf token", and resolved it by using a different browser.  
I was using Firefox, and switched to Chrome.  Very odd.

**Comment by sogehige** [comment]
I am closing this issue, per my experience firefox have some tokens issue lately and we are supporting chrome only
