### ISSUE TITLE
commands can works with +,-, e.t.c

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#281]
commands can works with +,-, e.t.c
Example1

**Command**: +s; **response**: /subscriberson
Me: +s
bot using subscriberson

Example2
**Command**: ?mmr; **response**: (var.mmr)

Me: ?mmr
Bot: @me, hi, mmr = 8000

**Comment by sogehige** [comment]
https://community.sogebot.xyz/t/commands-can-works-with-any-leading-char-not-only/73
