### ISSUE TITLE
After update from 9.9.0 to 9.10.1 gambles not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2897]
### Actual behavior
After u did update from  9.9.0 to 9.10.1 my gamble games stop working.

For example i have renamed !gamble to !roll, and it's just not giving anything on command usage.
No console errors, nothing.
### Steps to reproduce
master https://github.com/sogehige/sogeBot/commit/0461377377cb5e66b193a245a73ae46dc7456ec6

**Comment by Banonevar** [comment]
Seems it relevant for all other gambles

**Comment by sogehige** [comment]
Fixed by https://github.com/sogehige/sogeBot/pull/2901
