### ISSUE TITLE
Join/part widgets not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2937]
### Actual behavior
For me join/part widgets just empty all the time.
### Additional informations

master https://github.com/sogehige/sogeBot/commit/26738c92d821f8f53d753d97fc0344ab3a0a7434, mongodb

**Comment by Banonevar** [comment]
Relevant not for all my bot instances.

**Comment by sogehige** [comment]
logs?

**Comment by Banonevar** [comment]
No any logs. No errors.

**Comment by sogehige** [comment]
Let me know if this issue is fixed with typeorm

**Comment by Banonevar** [comment]
Nope, not fixed.

**Comment by sogehige** [comment]
Can you try to add logs to https://github.com/sogehige/sogeBot/blob/master/src/bot/microservices/getChannelChattersUnofficialAPI.ts#L137 if those data are sent?

**Comment by Banonevar** [comment]
Added like
```js
console.log({ modStatus, partedUsers, joinedUsers })
    
if (!isMainThread) {
  parentPort?.postMessage({ modStatus, partedUsers, joinedUsers });
}
return { modStatus, partedUsers, joinedUsers };
```
Nothing happening in console.
