### ISSUE TITLE
!immune

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#295]
give immune for user from bans (bot), cooldowns

**Comment by sogehige** [comment]
Interesting, will do, I'll also add `!immune list` and `!immune unset`

**Comment by Banonevar** [comment]
And it will be good if i'll can choice what type of immune, i.e `!immune username 5 caps`

**Comment by Banonevar** [comment]
If type not setted then give immune to all types `!immune username 5` (whill immune all types for 5 times)

**Comment by Banonevar** [comment]
Also maybe possible will give lifetime immune
but here is something like https://ideas.sogebot.xyz/posts/5/add-users-to-moderation-whitelist-for-each-reason-of-ban, maybe here is was to combine issue and this idea

**Comment by sogehige** [comment]
https://community.sogebot.xyz/t/moderation-immune-system/71
