### ISSUE TITLE
!points all not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2951]
### Actual behavior
When i type `!points all 100` then bot send in chat about he gived all users 100 points, but when i check my points seems bot not added that points.
### Steps to reproduce
```
!me
!points all
!me
```
### Additional informations

master https://github.com/sogehige/sogeBot/commit/7f59a672bfdc647a1edc0c1241b5e2a0c5e83237

**Comment by sogehige** [comment]
Cannot reproduce on PR
