### ISSUE TITLE
TypeError: this.socketsTokenAuthList.map is not a function

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2994]
### Actual behavior
```
2019-11-18T15:31:56.655 !!! ERROR !!! TypeError: this.socketsTokenAuthList.map is not a function
    at Timeout._onTimeout (/app/src/bot/socket.ts:58:65)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
On bot start.

### Additional informations

Dockerized master https://github.com/sogehige/sogeBot/commit/2ed25744ff3e4036ea6e1c6de5aa6b5a630acfcb version.
Cannot reproduce in runned not in docker.

**Comment by sogehige** [comment]
Repository?

**Comment by sogehige** [comment]
What are values in `settings` 
nsp: /core/socket
name: socketsTokenAuthList

**Comment by Banonevar** [comment]
This nsp is not exists.

**Comment by Banonevar** [comment]
oh, no, it exists, i'll send that in pm.

**Comment by sogehige** [comment]
Please cleanup that row, should fix your issue
