### ISSUE TITLE
Alerts doesnt work

### ISSUE THREAD

**Issue by Bazimek** [sogehige/sogeBot#301]
Example i have an alias:
!banan - !alert type=image url=http://bazim.cz/bot/banana.gif time=22000 position=top-left | type=audio url=http://bazim.cz/bot/banana.mp3 duration=1000

If i type !banan nothing happened. If somebody else type !banan bot will timeout him for posting links. 

In previous version was working.

**Comment by sogehige** [comment]
Please check in manage/alias if you dont have `!!alias` instead of `!alert`
