### ISSUE TITLE
Permissions whispering doesnt working

### ISSUE THREAD

**Issue by Bazimek** [sogehige/sogeBot#302]
Hen i set a command !banan to a REGULAR only and somebody without REGUAL type that cmd bot in console say >w> Nemas dostatecne opravneni pro '!banan' , but it doesnt really sent a whisper to user.

**Comment by sogehige** [comment]
Bot should correctly send whisper message, please read
https://discuss.dev.twitch.tv/t/whitelisting-whispers-on-my-bot/7958/4

**Comment by sogehige** [comment]
Please read https://discuss.dev.twitch.tv/t/have-a-chat-whisper-bot-let-us-know/10651
