### ISSUE TITLE
UI(commands): cannot open dropdowns

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3022]
### Actual behavior
When i click command response dropdowns, then nothing happening.

Response permission, and other dropdowns broken.
### Additional informations

master https://github.com/sogehige/sogeBot/commit/1f778617919e40d809f7591a584e320ee2885476

**Comment by sogehige** [comment]
Cannot reproduce on 3514af6dc
![AwesomeScreenshot-2019-11-27-1574869670955](https://user-images.githubusercontent.com/19549652/69738268-1ff0c380-1136-11ea-968e-77f1a459eb07.gif)

**Comment by Banonevar** [comment]
It's relevant not for all my bots.

**Comment by Banonevar** [comment]
Nvm, it's was browser bug. Changed browser and got it working.
