### ISSUE TITLE
Webpanel drops my authorization to fast

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3040]
### Actual behavior
When i open panel and login, when after some idle time (~10m) bot drop my authorization.
### Steps to reproduce
Open webpanel for 10 minutes.
### Additional informations

master https://github.com/sogehige/sogeBot/commit/be2d25af08a3e8d6e36cbc6825aa98193e36b9a9

**Comment by sogehige** [comment]
Yes, seems like accessToken is not properly refreshed, you can set as workaround some high number to accessToken
