### ISSUE TITLE
Qiwi integration: 403 from docker when request api.

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3046]
### Actual behavior
When Qiwi integration doing request do api, then got 403, and it's relevant only for dockerized bot.
### Steps to reproduce
First you can test it w/o docker, after that try with docker.

Also i'll send you some `secret token` for tests.
### Additional informations

master https://github.com/sogehige/sogeBot/commit/744942b90d65eb6ef38ef29026ebf14d9b3481e3

**Comment by sogehige** [comment]
Can you try https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/ if it solves your issue?

**Comment by sogehige** [comment]
no followup from reporter -> closing
