### ISSUE TITLE
Cannot run bot as a service since 9.10.x

### ISSUE THREAD

**Issue by MoonlightAshe** [sogehige/sogeBot#3120]
### Expected behavior
The bot being able to run as a systemctl service continuously without disruption besides outer influences. This was possible before the 9.10.x update.

### Actual behavior
The bot cannot continuously run as a service unless it is set to restart on always. It stops after about a day and must be restarted for it to work again. There is no log information I can track down for this, and the process apparently ends cleanly which is resulting in the service stopping without restarting if set with on-failure.

### Steps to reproduce
This is setup similarily with Phantombot since it was the simplest thing to do and has been working flawlessly up until the update. Below are the modified and obscured settings for Sogebot that was working:

```
[Unit]
Description=Sogebot
After=network.target remote-fs.target nss-lookup.target

[Service]
User=user
Group=user
Restart=on-failure
RestartSec=30
ExecStart=/home/user/sogebot/bin/startup.sh
KillSignal=SIGTERM

[Install]
WantedBy=multi-user.target
```

**Comment by Banonevar** [comment]
It is because bot crashing for some reason, i noticed that too.

As current workaround you can use pm2 for that, or docker.

pm2 not really hard to use:
```bash
npm i pm2 -g
cd /home/user/sogebot
pm2 start bin/startup.sh --name BotName
pm2 startup # this will setup auto start pm2 daemon on your VDS reboot
pm2 save # this will save runned by pm2 processes 
```

**Comment by sogehige** [comment]
any errors?

**Comment by MoonlightAshe** [comment]
None that I can find. It doesn't seem to output any errors or anything when it stops. It also doesn't really last that long too, either a day or two before it shuts down.

I can probably set it to Restart=always or use pm2 in the meantime though.

**Comment by sogehige** [comment]
I believe it might be one of the heap errors, after 2+days I see

```
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory


#
# Fatal error in , line 0
# Check failed: context->IsNativeContext().
#
#
#
```

```
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x9da7c0 node::Abort() [node]
 2: 0x9db976 node::OnFatalError(char const*, char const*) [node]
 3: 0xb39f1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb3a299 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xce5635  [node]
 6: 0xce5cc6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xcf1b5a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xcf2a65 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xcf410f v8::internal::Heap::HandleGCRequest() [node]
10: 0xca30f4 v8::internal::StackGuard::HandleInterrupts() [node]
11: 0xff1af7 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x1374fd9  [node]
{}
{}
{}
{}
```

**Comment by sogehige** [comment]
One solution what comes to my mind is that I can do slightly different worker threads than before, where main program will be spawning automatically worker thread if bot crashes so it keeps running in background.

**Comment by sogehige** [comment]
Of course second solution might be to fix heap problem but...it is pretty hard to find what exactly might be wrong.

**Comment by sogehige** [comment]
Also I would set `Restart=always` to be sure bot is still running, by https://github.com/sogehige/sogeBot/pull/3168 I add graceful restart each X hours to at least lower chance of bot crashing during stream (basically something like maintenance restart)

**Comment by sogehige** [comment]
Also added proper `exit` to startup.sh, which now should help you to catch error with service https://github.com/sogehige/sogeBot/pull/3171

**Comment by sogehige** [comment]
I believe this issue is solved => closing
