### ISSUE TITLE
Langs

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#313]
1) missed "user triggered event" in events
2) missed langs for /playlist/ page

**Comment by Satont** [comment]
+make new point in settings:
"lang cz" (or others)
Bcoz sometimes bot load not correctly (load in en instead mine ru)

**Comment by sogehige** [comment]
> Bcoz sometimes bot load not correctly (load in en instead mine ru)

Refresh of dashboard should fix that

**Comment by Satont** [comment]
Nope, not fix

**Comment by sogehige** [comment]
So, whole bot is in english - responses, etc?
