### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#314]
How i can make
Satonthq: !botplsban soge
Bot: Okay, satonthq, i banned soge for 10 secs

**Comment by sogehige** [comment]
Please, can you add your images as we spoke on twitter?

**Comment by Satont** [comment]
![img](https://satont.xyz/s/s86.png)

**Comment by sogehige** [comment]
You should use alias for this

**Comment by Satont** [comment]
Not understand how it must be

**Comment by sogehige** [comment]
!alias add !timeout !test

**Comment by sogehige** [comment]
and set !timeout command without (param)

**Comment by sogehige** [comment]
It is working for me correctly, sorry for wrong advice, !timeout should be with (param)
so it should look like

#### Alias
![1](https://cloud.githubusercontent.com/assets/19549652/26624655/d6bf3d0c-45f1-11e7-84b0-f9e018b587e6.png)

#### Custom Command
![2](https://cloud.githubusercontent.com/assets/19549652/26624671/ddd72ed8-45f1-11e7-85d3-8f0aa99fa3c8.png)
