### ISSUE TITLE
Some users still marked as online even they not in chatters

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3222]
### Actual behavior
I noticed some users still marked as `online` (db and viewers UI), even they not in chat for couple of hours.

So they was marked somewhere as online and never marked as offline
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/fc2ae784ffedcd409625f598cd85bad8d1baae3d

**Comment by sogehige** [comment]
Please check if such users are seen as partedUsers with DEBUG=microservice after https://github.com/sogehige/sogeBot/pull/3229
