### ISSUE TITLE
Build fails after the "Building with webpack" step hangs for a long time

### ISSUE THREAD

**Issue by wgomeringer** [sogehige/sogeBot#3244]
### Expected behavior
Build should complete successfully 

### Actual behavior
Build fails after sitting at 

         ----- Bundling with webpack
 
for a long time

### Steps to reproduce
Starting with a new repo

- clone
$ git clone https://github.com/sogehige/sogeBot.git

- copy to a new directory so we don't build in the git repo
$ cp -a sogeBot temp

- cp config.json and ormconfig.json to temp directory and cd to that dir
$ cp config.json ormconfig.json temp/
$ cd temp 

- Current config.json
$ cat config.json
{
  "__README__": "https://github.com/sogehige/SogeBot/wiki/Install-and-Upgrade",
  "timezone": "system",
  "threads": 1,
  "settings": {
    "bot_color": "OrangeRed"
  },
  "panel": {
    "__COMMENT__": "set correctly your domain and to be safe, change your token",
    "username": "XXXXXXXXX",
    "password": "XXXXXXXXX",
    "port": 20000,
    "domain": "XXXXXXXXX, XXXXXXXXX, XXXXXXXXX",
    "token": "XXXXXXXXX"
  },
  "database": {
    "__README__": "https://github.com/sogehige/sogeBot/wiki/Database-configuration",
    "type": "nedb",
    "mongodb": {
      "poolSize": 5,
      "url": "mongodb://localhost:27017/your-db-name"
    }
  },
  "metrics": {
    "translations": true
  },
  "debug": {
    "__COMMENT__": "DON'T ENABLE THIS UNTIL YOU KNOW WHAT YOU ARE DOING!",
    "all": true,
    "console": true
  }
}

- Current ormconfig.json
# cat ormconfig.json
{
  "type": "sqlite",
  "database": "./sogebot.db",
  "logging": ["error"],
  "cache": true,
  "synchronize": false,
  "migrationsRun": true,
  "entities": [
    "dest/database/entity/*.js"
  ],
  "migrations": [
    "dest/database/migration/sqlite/*.js"
  ],
  "subscribers": [
    "dest/database/entity/*.js"
  ],
  "cli": {
    "entitiesDir": "src/bot/database/entity/",
    "migrationsDir": "src/bot/database/migration/sqlite/",
    "subscribersDir": "src/bot/database/entity/"
  }

$ make

         ----- Cleaning up compiled files

         ----- Cleaning up node_modules

         ----- Installation of production dependencies

..(build output omitted)..

         ----- Generating CSS themes
Rendering Complete, saving .css file...
Wrote CSS to /home/william/Twitch/sogeBot-nightly/temp/public/dist/css/light.css
Rendering Complete, saving .css file...
Wrote CSS to /home/william/Twitch/sogeBot-nightly/temp/public/dist/css/dark.css

         ----- Bundling with webpack

..(hangs for 12m41s on this box, see specs below)..

ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts
[tsl] ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts(29,14)
      TS2339: Property 'cluster' does not exist on type '{ __README__: string; timezone: string; threads: number; settings: { bot_color: string; }; panel: { __COMMENT__: string; username: string; password: string; port: number; domain: string; token: string; }; database: { ...; }; metrics: { ...; }; debug: { ...; }; }'.

ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts
[tsl] ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts(40,28)
      TS2339: Property 'cluster' does not exist on type '{ __README__: string; timezone: string; threads: number; settings: { bot_color: string; }; panel: { __COMMENT__: string; username: string; password: string; port: number; domain: string; token: string; }; database: { ...; }; metrics: { ...; }; debug: { ...; }; }'.

ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts
[tsl] ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts(43,20)
      TS2339: Property 'cluster' does not exist on type '{ __README__: string; timezone: string; threads: number; settings: { bot_color: string; }; panel: { __COMMENT__: string; username: string; password: string; port: number; domain: string; token: string; }; database: { ...; }; metrics: { ...; }; debug: { ...; }; }'.

ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts
[tsl] ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts(75,42)
      TS2339: Property 'cluster' does not exist on type '{ __README__: string; timezone: string; threads: number; settings: { bot_color: string; }; panel: { __COMMENT__: string; username: string; password: string; port: number; domain: string; token: string; }; database: { ...; }; metrics: { ...; }; debug: { ...; }; }'.

ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts
[tsl] ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts(75,79)
      TS2339: Property 'cluster' does not exist on type '{ __README__: string; timezone: string; threads: number; settings: { bot_color: string; }; panel: { __COMMENT__: string; username: string; password: string; port: number; domain: string; token: string; }; database: { ...; }; metrics: { ...; }; debug: { ...; }; }'.

ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts
[tsl] ERROR in /home/william/Twitch/sogeBot-nightly/temp/src/bot/cluster.ts(77,22)
      TS2339: Property 'cluster' does not exist on type '{ __README__: string; timezone: string; threads: number; settings: { bot_color: string; }; panel: { __COMMENT__: string; username: string; password: string; port: number; domain: string; token: string; }; database: { ...; }; metrics: { ...; }; debug: { ...; }; }'.
Child HtmlWebpackCompiler:
     7 assets
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_1 = __child-HtmlWebpackPlugin_1
    Entrypoint HtmlWebpackPlugin_2 = __child-HtmlWebpackPlugin_2
    Entrypoint HtmlWebpackPlugin_3 = __child-HtmlWebpackPlugin_3
    Entrypoint HtmlWebpackPlugin_4 = __child-HtmlWebpackPlugin_4
    Entrypoint HtmlWebpackPlugin_5 = __child-HtmlWebpackPlugin_5
    Entrypoint HtmlWebpackPlugin_6 = __child-HtmlWebpackPlugin_6
    [/LdF] ./node_modules/html-webpack-plugin/lib/loader.js!./src/oauth/spotify.html 851 bytes {HtmlWebpackPlugin_6} [built]
    [BB+M] ./node_modules/html-webpack-plugin/lib/loader.js!./src/panel/index.html 2.03 KiB {HtmlWebpackPlugin_1} [built]
    [HWBc] ./node_modules/html-webpack-plugin/lib/loader.js!./src/overlay/index.html 1020 bytes {HtmlWebpackPlugin_3} [built]
    [JfOz] ./node_modules/html-webpack-plugin/lib/loader.js!./src/login/index.html 1.09 KiB {HtmlWebpackPlugin_4} [built]
    [NrM3] ./node_modules/html-webpack-plugin/lib/loader.js!./src/oauth/index.html 1.31 KiB {HtmlWebpackPlugin_5} [built]
    [Uzvm] ./node_modules/html-webpack-plugin/lib/loader.js!./src/panel/popout.html 2.12 KiB {HtmlWebpackPlugin_0} [built]
    [rTUq] ./node_modules/html-webpack-plugin/lib/loader.js!./src/public/index.html 974 bytes {HtmlWebpackPlugin_2} [built]
make: *** [Makefile:43: ui] Error 2

### Additional information

!_debug not applicable in this case as I can't build the bot

Other information that may be important
$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       39 bits physical, 48 bits virtual
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  8
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               95
Model name:          Intel(R) Atom(TM) CPU C3758 @ 2.20GHz

$ cat /proc/meminfo
MemTotal:       32905180 kB
MemFree:        29332128 kB
MemAvailable:   32185912 kB

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ uname -r
4.19.0-6-amd64

I have a two working 9.10.2 bots on this box. I have not been able to move beyond that due to this webpack issue. Anything else that might be useful please let me know. Thank you

**Comment by sogehige** [comment]
You are missing cluster config in your config.json, see https://github.com/sogehige/sogeBot/blob/master/src/bot/data/config.example.json

**Comment by sogehige** [comment]
Also, it is normal for webpack to run around ~10minutes unfortunately. Also note that from 9x version you need to migrate your db to your new database (selected by correct ormconfig) http://sogehige.github.io/sogeBot/#/install-and-upgrade?id=upgrade-from-910x

**Comment by sogehige** [comment]
If migration failed, let me know, I surely tried to fix all edgecases on migration, but errors might still happen.

**Comment by wgomeringer** [comment]
Thank you very much. After adding the cluster config to config.json I was able to build successfully. Afterwards I migrated my database, which was successful, and started the bot. Everything is working as expected. Finally able to move to a new release. Thanks again.

**Comment by sogehige** [comment]
No problem, I am here to help (or at discord or at http://community.sogebot.xyz) :)
