### ISSUE TITLE
2 messages for roulette (iniciated, and > fireed or not)

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#326]
delay before
command trigger and die

**Comment by Satont** [comment]
add roulette moderator 
add roulette subscriber
like in moobot

**Comment by sogehige** [comment]
> add roulette moderator
> add roulette subscriber
> like in moobot

different request, make appropriate one

**Comment by sogehige** [comment]
I'll create switcher between 1 and 2 messages.
