### ISSUE TITLE
Some data about PG quries

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3285]
Based on https://www.cybertec-postgresql.com/en/detecting-performance-problems-easily-in-postgresql/ i enabled this, and got some data for analyze.

I imported .csv for you.

[file.zip](https://github.com/sogehige/sogeBot/files/4236349/file.zip)

### Notice:

You can skip queries which is lower cased. They not related to sogeBot.

**Comment by sogehige** [comment]
https://github.com/sogehige/sogeBot/pull/3286 should help with highest queries for subscribers. Would be nice to gather some data after that commit and create new csv

**Comment by Banonevar** [comment]
Some another payload

[sql.zip](https://github.com/sogehige/sogeBot/files/4240433/sql.zip)

**Comment by sogehige** [comment]
Looking better to me.
