### ISSUE TITLE
Some bot uses much cpu

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3288]
An my bot stacked on 200% cpu usage.

So did some profiling of CPU and heap dump

If you have time to check it i'll be ready appreciated.
Cannot upload it to forum/discord/github because it's to big.

https://mega.nz/#!Gx0TnYbA!hogtlgoLunpgs3E3loYLetI584FMw8QBAdqerVmma_Q

**Comment by sogehige** [comment]
Seems postgres related, but I cannot read from that nothing more

**Comment by sogehige** [comment]
Let me know of status of this issue on latest release, thanks!

**Comment by Banonevar** [comment]
Seems like it's gone after that https://github.com/sogehige/sogeBot/commit/0eedcc614fbea1b6b4e948412db00400cd9ba09b commit.

**Comment by Banonevar** [comment]
Issue is back.

**Comment by sogehige** [comment]
Fixed by reimporting db
