### ISSUE TITLE
something wrong with chat messages counter

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#341]
https://youtu.be/rVRGqo1DjmQ

**Comment by sogehige** [comment]
logs? stats.db? Does it starts after certain message count value?

**Comment by Satont** [comment]
Seems like yes, after certain  messages, but cant track of
https://satont.xyz/s/sogebot.log
https://satont.xyz/s/sogebot1.log
https://satont.xyz/s/sogeBot.db
https://satont.xyz/s/stats.db

**Comment by sogehige** [comment]
I probably found an issue, can you please try latest master with 4f554f4  ?

**Comment by Satont** [comment]
It fixed my issue.
