### ISSUE TITLE
 cooldown start works for mods

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#348]
So why for some reason cooldown start works for mods

**Comment by sogehige** [comment]
Whats an issue?

**Comment by Satont** [comment]
Cooldown works for mods

**Comment by sogehige** [comment]
Yes, only owner is cooldown free

**Comment by Satont** [comment]
maybe make it like swith mods/owner?

**Comment by sogehige** [comment]
Closing as it is same as #351
