### ISSUE TITLE
!anele

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#353]
Gamble - !anele
Bot will ban 10 random online users from chat for x seconds

**Comment by Satont** [comment]
Or more then 10

**Comment by alreadylostmyself** [comment]
var a = "";
var b;
var c;
var arr = _.map(_.sampleSize(_.filter(users, function(o) {
    return o.is.online
}), 9), 'username');
for (var i = 0; i < arr.length; i++) {
    b = '(!cban.' + arr[i] + ') ';
    a = a + b;
};
c = a + sender + " use anele and ban 9 users in chat";
return c;
