### ISSUE TITLE
Possibility: Virtual Store?

### ISSUE THREAD

**Issue by kyroskoh** [sogehige/sogeBot#369]
Implement a virtual store for users to claim their rewards such like more to RevloBot concept with virtual item, sfx, commands. If adding a command reward like !makeitrain, !tempbonus feature will be better.

**Comment by sogehige** [comment]
I like it, need to think about it how I will implement it, but I will do it

**Comment by sogehige** [comment]
https://community.sogebot.xyz/t/shop-system/69
