### ISSUE TITLE
Getting a 404 nginx error when I go to http://oauth.sogebot.xyz/

### ISSUE THREAD

**Issue by SeaWolfos** [sogehige/sogeBot#3690]
### Actual behavior
404 error
### Steps to reproduce
go to URL, click authorize, throws error

**Comment by SeaWolfos** [comment]
I suppose it would help:
Firefox Private mode
v 75.0
Ubuntu 18.04

**Comment by sogehige** [comment]
Thanks for report

**Comment by sogehige** [comment]
Ok, what are you trying to do? you should not go directly to http://oauth.sogebot.xyz/

**Comment by sogehige** [comment]
Login from bot is working ok for me, direct access is not working but it shouldn't even work
