### ISSUE TITLE
trigger for roulette, seppuku for mods, owner?

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#372]
"tiggeredbymod": "sry u cant roulette, bcoz u r very good guy with a green sword"
"triggeredbystreamer": "are ur sick? why u want roulette urself.. ur viewers will.."
for seppuku make same things

**Comment by Satont** [comment]
In "broadcaster" used owners list, there must by "channel" 
bcoz if owner run !roulette, i got trigger as broadcaster

**Comment by sogehige** [comment]
Should be fixed now
