### ISSUE TITLE
401 twitch error on new bot

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3759]
### Expected behavior
Shoudn't be any logging, it must access me and show error `owners not setted`
### Actual behavior
Trying setup new bo on `localhost` (pc), but it forcing me login from twitch.
### Additional informations

master https://github.com/sogehige/sogeBot/commit/f31249a4d590330d6feab0027318830b1ba7f6ed

**Comment by sogehige** [comment]
There should be login, logged user have owner permission until you add your owners. Login working OK for me on new bot.
