### ISSUE TITLE
Public page loading forever

### ISSUE THREAD

**Issue by liadala** [sogehige/sogeBot#3763]
### Expected behavior
Public page is shown
### Actual behavior
Endless loading animation
### Steps to reproduce
open public page
### Additional informations
bot version is 11.2.0
tested with firefox and chrome

Console log shows only 1 entry

Getting translations

**Comment by TheSoulrester** [comment]
nothing in console log - vivaldi browser
bot version 11.2.0

![image](https://user-images.githubusercontent.com/7083599/82146720-84225380-984c-11ea-8b96-70040387cbe3.png)
