### ISSUE TITLE
Alias Group Feature dont show objects inside

### ISSUE THREAD

**Issue by liadala** [sogehige/sogeBot#3803]
Bot Version:
  11.3.1
Database:
  SQLite
Affects:
  WebUI Manage > Aliases
Description:
  New Group Feature dont show objects inside
Bot-OS:
  Linux
Expected Behaviour:
  Group is still empty but has assigned objects
Steps to Reproduce:
  - Create Group in Alias
  - Assign Alias to Group
![2020-05-23 (1)](https://user-images.githubusercontent.com/62029150/82723695-fe315d00-9cd0-11ea-86da-ef460cc05704.png)

**Comment by sogehige** [comment]
Did you click on that Alert(7)? it is showing only one group
