### ISSUE TITLE
Problem with Windows

### ISSUE THREAD

**Issue by H4nSolo** [sogehige/sogeBot#382]
Hi guys,

i have a Problem to start or to install the Bot.

Everytime when i start the bot with "npm start" i get this:

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sogebot@5.6.1~prestart: sogebot@5.6.1
6 silly lifecycle sogebot@5.6.1~prestart: no script for prestart, continuing
7 info lifecycle sogebot@5.6.1~start: sogebot@5.6.1
8 verbose lifecycle sogebot@5.6.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle sogebot@5.6.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;G:\sogeBot\node_modules\.bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Skype\Phone\;C:\Windows\system32\wbem;C:\Program Files (x86)\IVT Corporation\BlueSoleil\Mobile;C:\Program Files\Git\cmd;C:\Program Files\OpenVPN\bin;C:\Program Files\nodejs\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Users\H4nSolo\AppData\Roaming\npm
10 verbose lifecycle sogebot@5.6.1~start: CWD: G:\sogeBot
11 silly lifecycle sogebot@5.6.1~start: Args: [ '/d /s /c', 'npm run copy:dist && node ./main || true' ]
12 silly lifecycle sogebot@5.6.1~start: Returned: code: 1  signal: null
13 info lifecycle sogebot@5.6.1~start: Failed to exec start script
14 verbose stack Error: sogebot@5.6.1 start: `npm run copy:dist && node ./main || true`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid sogebot@5.6.1
16 verbose cwd G:\sogeBot
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error sogebot@5.6.1 start: `npm run copy:dist && node ./main || true`
22 error Exit status 1
23 error Failed at the sogebot@5.6.1 start script 'npm run copy:dist && node ./main || true'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sogebot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run copy:dist && node ./main || true
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sogebot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sogebot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can someone Help oder fix the Bug in the Parser.js for windows Systems?

Thx

**Comment by sogehige** [comment]
Hi, you need node 8.x to run a bot

Dne 1. 8. 2017 4:23 odpoledne napsal uživatel "H4nSolo" <
notifications@github.com>:
