### ISSUE TITLE
Moderation: bot uses default values, instead of actual values

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3848]
### Actual behavior
Bot uses default values for moderate, instead of db values.

How i understand that? Bot timeout users for caps, uses 3 warnings, instead of my setted 1 warning and disabled caps moderation
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/78e1e1dea9a13426ee1629e805809e5ba64db18a

**Comment by Banonevar** [comment]
Disabling whole of moderation system is working. I mean disable/enable toggle of system is actually working and bot stops moderate the chat.

**Comment by sogehige** [comment]
I don't see any issues regarding loading of permission based settings 
```
{
  '0efd7b1c-e460-4167-8e06-8aaf2c170311': true,
  'c168a63b-aded-4a90-978f-ed357e95b0d2': true,
  'e8490e6e-81ea-400a-b93f-57f55aad8e31': true,
  'e3b557e7-c26a-433c-a183-e56c11003ab7': false,
  'b38c5adb-e912-47e3-937a-89fabd12393a': true,
  '4300ed23-dca0-4ed9-8014-f5f2f7af55a9': '%%%%___ignored___%%%%'
}
```

And also by testing at https://github.com/sogehige/sogeBot/tree/3848 I don't see any issues as well.

**Comment by Banonevar** [comment]
Can you please add debug in moderation system, so i can debug it and possible find a problem?

**Comment by sogehige** [comment]
`npm run debug`?
