### ISSUE TITLE
completly disable whispers in bot

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#385]
add new string in config.ini:
whispers = true/false

**Comment by sogehige** [comment]
Why do you want to disable whispers at all? You mean all whispered messages should be sent as normal messages?

**Comment by Satont** [comment]
Disable notices about changed settings.
And it will be helpfull when i send any request to discuss.dev.twitch.tv/t/have-a-chat-whisper-bot-let-us-know/10651/
bcoz if i run bot before twitch stuff accept him, then bot got ban, bcoz he send whispers before it
so main reason its disable notices about changed settings, and disable any whisper futures (like commands in whispers)

**Comment by sogehige** [comment]
I can add several bot settings (take names with grain of salt)

disableWhisperListening: true/false - bot will not respond to whispered commands
disableSettingsWhispers: true/false - bot will not send whispers after setting change
disableRaffleWhispers: true/false - bot will not send whisper after raffle join
disablePermissionWhispers: true/false - disable whisper warning about insufficient permissions
disableCooldownWhispers: true/false - disable whisper warning about cooldown

But I don't see a point to disable whole whispers setting for everything.

**Comment by Satont** [comment]
Ok, yes, it will be better.
If its possible it will be very good future

**Comment by sogehige** [comment]
I can add it today/tomorrow :) not hard to do
