### ISSUE TITLE
How to change the global command ! thingo

### ISSUE THREAD

**Issue by Deanosim** [sogehige/sogeBot#3943]
I don't know if this has been asked before and if so I'm sorry I couldn't find anything while searching.

But is their a way to globally change the ! at the start of all the commands instead of 1 by one? I'd like to be able to easily change it all over the place to something else like ? or whatever so it doesn't conflict with other bots.

**Comment by sogehige** [comment]
This is currently not possible, although it is already requested in https://community.sogebot.xyz/t/commands-can-works-with-any-leading-char-not-only/73
