### ISSUE TITLE
Sogebot is fetching StreamLabs TEST tips and displaying as it was a real tip.

### ISSUE THREAD

**Issue by JustAzul** [sogehige/sogeBot#3949]
### Expected behavior
i believe this was not supposed to be displayed at $toptip.overall.amount, $latestTip, also i have not tested the $latestSubscriber..
### Actual behavior
it fetch those test actions and shows in $toptip.overall.amount, $latestTip as it was a real tip, not a test one.
### Steps to reproduce
tried in text overlay..

**Comment by sogehige** [comment]
Thanks, will take a look
