### ISSUE TITLE
Heist discord message: #test: Test message with @soge and @esl_csgo 

### ISSUE THREAD

**Issue by katasuno** [sogehige/sogeBot#3971]

**Comment by sogehige** [comment]
Haha lol :)

**Comment by katasuno** [comment]
I'm sorry but this isn't it. The does not send announcement messages.

**Comment by katasuno** [comment]
function announce(messageToAnnounce) {
    var _a, _b;
    return __awaiter(this, void 0, void 0, function* () {
        messageToAnnounce = (yield new message_1.Message(messageToAnnounce).parse({}));
        sendMessage(messageToAnnounce, {
            username: oauth_1.default.botUsername,
            displayName: oauth_1.default.botUsername,
            userId: Number(oauth_1.default.botId),
            emotes: [],
            badges: {},
            'message-type': 'chat',
        }, { force: true, skip: true });
        if (discord_1.default.sendGeneralAnnounceToChannel.length > 0 && discord_1.default.client) {
            for (const [id, channel] of discord_1.default.client.channels.cache) {
                if (channel.type === 'text') {
                    if (id === default.sendGeneralAnnounceToChannel || channel.name === discord_1.default.sendGeneralAnnounceToChannel) {
                        const ch = discord_1.default.client.channels.cache.find(o => o.id === id);
                        messageToAnnounce = 'Test message with @soge and @esl_csgo';
                        if (ch) {
                            let match;
                            const usernameRegexp = /@(?<username>[A-Za-z0-9_]{3,15})/g;
                            while ((match = usernameRegexp.exec(messageToAnnounce)) !== null) {
                                if (match) {
                                    const username = (_a = match.groups) === null || _a === void 0 ? void 0 : _a.username;
                                    const userId = yield users_1.default.getIdByName(username);
                                    const link = yield typeorm_1.getRepository(discord_2.DiscordLink).findOne({ userId });
                                    if (link) {
                                        messageToAnnounce = messageToAnnounce.replace(`@${username}`, `<@${link.discordId}>`);
                                    }
                                }
                            }
                            log_1.chatOut(`#${ch.name}: ${messageToAnnounce} [${(_b = discord_1.default.client.user) === null || _b === void 0 ? void 0 : _b.tag}]`);
                        }
                    }
                }
            }
        }
    });
}

**Comment by sogehige** [comment]
Yes, I forgot to uncomment actual sending of messages, sorry! Should be fixed in 11.9.1
