### ISSUE TITLE
Discord general announce doesn't work

### ISSUE THREAD

**Issue by katasuno** [sogehige/sogeBot#3976]
![General Announcement Channel](https://user-images.githubusercontent.com/62215083/87103295-4c88c400-c25d-11ea-82e3-d8c536a0e038.png)
![Announcement](https://user-images.githubusercontent.com/62215083/87103339-65917500-c25d-11ea-84cd-046777f9ca88.png)

**Comment by sogehige** [comment]
Thanks for issue!
