### ISSUE TITLE
cooldowns for gamble games

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#398]
duel, fight me, and others in future
after gamble end it can got cooldown for use
___
user1: !duel 5
user2: !duel 5
-> 5 mins later
Bot: Congtatz, user2, u won 10 points win chance 50%
user3: !duel 5
Bot: sry, user3, u cant start duel 10 more minutes
____
And so for all gamble

**Comment by sogehige** [comment]
I removed !gamble, as it can be have cooldown by cooldown system
