### ISSUE TITLE
cooldown on gabmles working for owners

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#402]
cooldown on gambble games working for owners, broadcaster
there is no cooldowns for it, or have settings like customcommands

**Comment by sogehige** [comment]
Not sure what you mean with cooldowns

I like `!fightme` improvement, will add

**Comment by Satont** [comment]
owners and mods cant use !fightme when this gamble on cooldown

**Comment by sogehige** [comment]
Oh you mean to bypass cooldown for them?

**Comment by Satont** [comment]
Yes

**Comment by sogehige** [comment]
Ok, I'll add new settings for that
