### ISSUE TITLE
Giveaway overlay / Timer

### ISSUE THREAD

**Issue by Digiw0lf** [sogehige/sogeBot#415]
Giveaway overlay -- Show that you can win, how many points it costs if points giveaway or the keyword if raffle giveaway and time left on giveaway

Add a giveaway timer so we can set how long until the giveaway is closed but a mod would need to draw it

**Comment by Digiw0lf** [comment]
Also !claim for users to claim the giveaway on they have won... This command would only work for the winner of the giveaway and would flag mods that the person has responded and to tell the user to check twitch inbox in a few moments for a message from the streamers mods

**Comment by sogehige** [comment]
Closing this as we don't have currenty time based raffles
