### ISSUE TITLE
crash for some reason

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#433]
Bot version: 5.7.2
Node.js version: 8.6.0

Npm version: 5.3.0

Does node_modules folder and package-lock.json remove and npm install solved issue?: no

Issue description: crash 
[exceptions-2017-09-27T12_47_50.log](https://github.com/sogehige/sogeBot/files/1340130/exceptions-2017-09-27T12_47_50.log)
[exceptions-2017-09-27T13_18_01.log](https://github.com/sogehige/sogeBot/files/1340131/exceptions-2017-09-27T13_18_01.log)
[exceptions-2017-09-27T13_27_26.log](https://github.com/sogehige/sogeBot/files/1340129/exceptions-2017-09-27T13_27_26.log)
[exceptions-2017-09-27T13_29_47.log](https://github.com/sogehige/sogeBot/files/1340128/exceptions-2017-09-27T13_29_47.log)

Attach your logs/exception.log file if bot crashes

**Comment by sogehige** [comment]
This is some issue with twitchbot.ga url
Error: Error: Hostname/IP doesn't match certificate's altnames: \"Host: twitchbot.ga. is not in the cert's altnames: DNS:mail.protectionlaw.ru, DNS:pop.protectionlaw.ru, DNS:protectionlaw.ru, DNS:smtp.protectionlaw.ru, DNS:www.protectionlaw.ru

What is that url used for? request should not kill bot on error but would need to track it down

**Comment by sogehige** [comment]
Last exception is from clips system...just disable clip system, will not be anymore in next version

**Comment by Satont** [comment]
crash because clips? or crash because DNS?
so solution its disable clips, right?

**Comment by sogehige** [comment]
You posted two different crashes, disabling clips will fix one of those crashes, I need you to answer https://github.com/sogehige/sogeBot/issues/433#issuecomment-332938841

**Comment by Satont** [comment]
twitchbot.ga using to some api
(api|https://twitchbot.ga)

**Comment by sogehige** [comment]
Closing as api cannot be tested again
