### ISSUE TITLE
Add obs-websocket

### ISSUE THREAD

**Issue by Jose76Tron** [sogehige/sogeBot#437]
Can you add something like obs-websocket? for example a command for save replay or stop streaming, it can be very nice for streamers that using 2 computers cant press the hotkey for save replay so mods can save a replay or stuff

**Comment by sogehige** [comment]
Yes, this is planned :) but still in R&D

**Comment by sogehige** [comment]
I don't think this is currently actual. sogeTicker is basically abandoned now, although I am open for any PRs for obs-websocket

**Comment by sogehige** [comment]
Closing for now, if this feature is still wanted, please log it in http://ideas.sogebot.xyz
