### ISSUE TITLE
Viewers List

### ISSUE THREAD

**Issue by Kazanka101** [sogehige/sogeBot#448]
Is there a way to view who is in your chat as a widget? One of the features I like best about the previous bot I've used was seeing who leaves and joins the chat.

**Comment by sogehige** [comment]
Yes, this can be done as widget

**Comment by sogehige** [comment]
So, do you want viewers list or something like join/part log?
```
> joined - user 2
> joined - user 1
< parted - user 2
```

**Comment by Kazanka101** [comment]
If it's one user it could be listed in the same line. 

> <user> joined the chat.
> <user>, <user> joined the chat.

and same goes for parting. I'm used to using 'Chatty' and its really good with that. :)

**Comment by Kazanka101** [comment]
It could also list what users are in chat. Not sure what trouble it would be to have both or not. Could be 2 separate widgets.

**Comment by sogehige** [comment]
This widget will not save data, so every refresh will clear widget, also, it will show only 6 join/parts events
