### ISSUE TITLE
8Ball Game

### ISSUE THREAD

**Issue by Kazanka101** [sogehige/sogeBot#449]
This is one of those old games thats always on the other bots. Would be a good edition or feature. Not sure how easy it would be to add.

**Comment by sogehige** [comment]
!8ball is simple, can do

**Comment by sogehige** [comment]
Hmm, I added (eval) filter for 5.8.0, you can create commands with javascript functions

example !8ball
command: `!8ball`
response: `(sender) asks '(param)' - (eval var sayings = ['Signs point to yes.', 'Yes.', 'Reply hazy, try again.', 'My sources say no.', 'You may rely on it.', 'Concentrate and ask again.', 'Outlook not so good.', 'It is decidedly so.', 'Better not tell you now.', 'Very doubtful.', 'Yes - definitely.', 'It is certain.', 'Cannot predict now.', 'Most likely.', 'Ask again later.', 'My reply is no.', 'Outlook good.', "Don't count on it."]; return sayings[Math.floor(Math.random() * sayings.length)];) `
