### ISSUE TITLE
/me for all or some of the commands

### ISSUE THREAD

**Issue by Kazanka101** [sogehige/sogeBot#450]
It would be nice to be able to choose commands to use /me to stand out above others of what the bot posts. Custom commands can be added manually currently for the most part.

**Comment by Satont** [comment]
I think (if it possible) better add /me toggle button here
!(img)[https://satont.ru/s/1t4b.png]

**Comment by sogehige** [comment]
Yeah, why not, can do it as settings
`!set sendWithMe true/false`
