### ISSUE TITLE
Multi Twitch Support

### ISSUE THREAD

**Issue by Kazanka101** [sogehige/sogeBot#451]
My previous bot has a command where I can use '!multi channel1 channel2, etc

It would then output with multitwitch.tv/channel1/channel2

You can multi twitch multiple channels this way.

**Comment by sogehige** [comment]
Wont do, this will be doable with `(eval)`

Example:
command: `!multi`
response: `(eval if (param.length === 0) return ''; else return 'http://multitwitch.tv/' + param.replace(/ /g, '/');)`
