### ISSUE TITLE
Dashboard blocking Stream Monitor and Chat Box over HTTPS

### ISSUE THREAD

**Issue by aramsdale** [sogehige/sogeBot#4547]
### Expected behavior
Adding the Stream Monitor widget and chat widget, I expect to see the streams as shown in the example images.

### Actual behavior
I have a blocked icon, with the following message: "www.twitch.tv refused to connect." for the chatbox and "player.twitch.tv refused to connect." for the stream monitor.

HTTPS certs are confirmed installed, and pulling over 20443, and I can inspect the page and pull the direct links and get to them independently, so the pages themselves appear to be valid.

Is this a cross-site/allowed script embed security blocker in Chrome?

### Steps to reproduce
Install in CentOS
Add Cert info in .env
Boot Soge, add broadcaster and bot keys, propagate permissions
Add Stream monitor and chat widgets to dashboard
See error
 
### Additional informations

2021-01-14T16:12:09.600 DEBUG: * ======= COPY DEBUG MESSAGE FROM HERE =======
2021-01-14T16:12:09.601 DEBUG: * GENERAL      | OS: npm/6.14.8 node/v14.15.0 linux x64

**Comment by sogehige** [comment]
you need to serve ssl on :443 port. That's Twitch policy. You can use nginx for that.

**Comment by sogehige** [comment]
We may need to mention this in docs

**Comment by aramsdale** [comment]
Ah! I'll set up a reverse proxy since I'm already using apache on that box.

Thanks for the info

**Comment by sogehige** [comment]
Yeah, Twitch is nowadays too strict :)

**Comment by sogehige** [comment]
Widgets should show now error if incorrect port or http is used https://github.com/sogehige/sogeBot/commit/378147e21d1d3df10eba58246b81f4835b3beef7

**Comment by aramsdale** [comment]
Took me a while to get reverse proxy working. At first, I had domain.com/bot reverse proxied to localhost:20000, which appears to break because of the URLs are hardcoded to root (domain.com/dest/.../main###.ts), instead of pointing to /bot.

Would this be worthwhile feature suggestion, to expand upon the [Domain] variable to include any relevant subdirectory instead of setting up a subdomain?

Thanks for your help above, btw!

**Comment by sogehige** [comment]
I believe there was some feature request for this, but I cannot find it. But -> https://community.sogebot.xyz/c/feature-requests/7
