### ISSUE TITLE
Queue Widget

### ISSUE THREAD

**Issue by Kazanka101** [sogehige/sogeBot#457]
It currently allows you to enter and show you a number of who is in the queue. 

I was thinking this would be like a queue for sort of like a 'take a number' first come first serve basis. When joining it would list who is in the queue and you can select next person in line. Unless this could be a new feature but having it so people type '!play' it adds them to the queue and you can pick them up to play with you in the order they came. 

I used the alias to change the command currently but I was hoping how that would work. If that makes sense...

**Comment by sogehige** [comment]
Not sure if I follow

Currently queue is working that viewer can `!queue join` and broadcaster can `!queue pick` viewers, which will be FIFO as you described. Also widget should do exactly same

**Comment by Kazanka101** [comment]
I guess it's more of a nit picking thing but like how the latest followers works it lists who is in the queue. It would be nice this would do the same in order. I only tested it with 2 people but I swear it was random but I don't remember.  It only has a number of who is in the queue and then when selected you move over a tab and shows the person selected. This way if need be you could click on a name and remove them from queue and what not I guess? 

Is that a little better?

**Comment by sogehige** [comment]
Well I can add _manual_ selection tab to widget.

Queue *should* not be random.
