### ISSUE TITLE
Adding HTML option to !alert

### ISSUE THREAD

**Issue by Kazanka101** [sogehige/sogeBot#465]
So in short... I have overlays HTML based that I use as a browser source. I'd like to be able to use these with the !alert system you currently have. The options are there you just need to support HTML type. This could open the doors to a lot of other types of overlays. You could have confetti, fireworks, snow, etc. The best part is having your community trigger it for you. 

See what you can do... :)

**Comment by sogehige** [comment]
added `!alert type=html url=yourpageurl`
you can use `duration`, `time`

Delay is not in, because some pages might take up some times to load, nto sure if delay is desirable

Example: `!alert type=html url=http://labs.qnimate.com/raindrop/ duration=5000 time=10000`
