### ISSUE TITLE
Problem with ru.json and timers

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#472]
### Expected behavior
Fix problem with it
### Actual behavior
On ru.json when im open webpanel/timers got 
**Uncaught TypeError: Cannot read property 'variable' of undefined**
Its from chrome console
### Steps to reproduce
try to my ru.json: https://satont.ru/s/f/ru.json
### Additional informations
Bot version: Last
Node.js version: 8.6.0
Npm version: 5.3.0

**Comment by Satont** [comment]
Nvm, close it.

**Comment by sogehige** [comment]
Also, no support for custom languages
