### ISSUE TITLE
text misalignment in OBS Websocket module settings

### ISSUE THREAD

**Issue by liadala** [sogehige/sogeBot#4724]
![Screenshot_2021-07-16_at_14-48-12_clockdroid_liadala](https://user-images.githubusercontent.com/62029150/125952996-f81500b6-8847-4ca4-b374-c95d89754958.png)

**Comment by sogehige** [comment]
https://github.com/sogebot/ui-admin/commit/38ea092f0f596e59c76c85231b4c12c6f6921551
