### ISSUE TITLE
Uncaught Error: This must be called within a setup function. NuxtJS

### ISSUE THREAD

**Issue by liadala** [sogehige/sogeBot#4726]
browser console get spamed with
Uncaught Error: This must be called within a setup function. NuxtJS

**Comment by sogehige** [comment]
Any more info when this happen?

**Comment by liadala** [comment]
as soon as ui is loaded it starts spamming this in browser console

**Comment by liadala** [comment]
currently after 3 restarts this isnt happen anymore
please mark it currently as "investigating" status if that happen again
