### ISSUE TITLE
UI toogle switch state is not shown correctly

### ISSUE THREAD

**Issue by liadala** [sogehige/sogeBot#4756]
The following video show the issue
![Video](https://cdn.discordapp.com/attachments/619437014001123338/871261606259081246/VQhplC9NxN.mp4)

**Comment by liadala** [comment]
also in Settings/Modules for ResponsiveVoice
it is enabled but shows disabled
![Screenshot 2021-08-01 at 11-15-05 clockdroid liadala](https://user-images.githubusercontent.com/62029150/127765838-8b365a67-b24a-43cb-ae94-89f338c3a219.png)

**Comment by PsychoMan470** [comment]
https://user-images.githubusercontent.com/63324380/127777961-c7abf31f-78ab-4175-bf2b-0b300013c219.mp4

video showing the same issue

**Comment by liadala** [comment]
toogle button from responsive voice fixed in
https://github.com/sogehige/sogeBot/pull/4760

toogle button in moderation is another bug
