### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#479]
### Expected behavior
fix or not
### Actual behavior
Uncaught TypeError: Cannot read property 'replace' of undefined
when open "ranks" page in webpanel
### Steps to reproduce
open "ranks" page in webpanel and check console
### Additional informations
Bot version: latest
Node.js version:
Npm version:

**Comment by sogehige** [comment]
This issues will be quite common maybe with others (users, etc) until I'll update UI for all systems
Closing as done as this is being worked on
