### ISSUE TITLE
No answer for second user

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#487]
### Expected behavior
fix
### Actual behavior
9|bogsh    | 2017-10-26T20:32:49.700 <<< !me [satontx]
9|bogsh    | 2017-10-26T20:32:50.065 >>> @satontx | 130.8h | 54 поинтов | 1008 сообщений [satontx]
9|bogsh    | 2017-10-26T20:32:58.492 <<< !me [ubiquistgg]
9|bogsh    | 2017-10-26T20:32:59.620 >>> @ubiquistgg | 144.7h | 62 поинтов | 3984 сообщений [ubiquistgg]
___
but bot no answer to **ubiquistgg**
![img](https://satont.ru/s/8i68.png)

### Additional informations
Bot version: 5.7.5
Node.js version:
Npm version:

**Comment by Satont** [comment]
Not for second, just skip sometimes
![img](https://satont.ru/s/5v78.png)

**Comment by Satont** [comment]
for duel same lol
on logs fine, points was dueled, but no message in chat

**Comment by sogehige** [comment]
Send me relevant logs

Dne 26. 10. 2017 7:52 odp. napsal uživatel "Satont" <
notifications@github.com>:

**Comment by Satont** [comment]
Bot sorry, there is russian, hope you can find commands
[sogebot-2017-10-26T20_32_07.log](https://github.com/sogehige/sogeBot/files/1419495/sogebot-2017-10-26T20_32_07.log)

**Comment by sogehige** [comment]
If message is in log, then message should be sent. Is your bot a mod of channel? If not, twitch may block some messages

**Comment by Satont** [comment]
Yea, bot is mod

**Comment by sogehige** [comment]
Strange, but I just cannot fix this issue, it is something on Twitch side, not a bot. Will think about possibility to have two bot connections to chat, so it can retry some messages
