### ISSUE TITLE
quiz system

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#493]
Add new gamble: quiz
Bot will ask question
For example
Bot: On what planet we live?
__
N secs later if noone answered
Bot: Hint: e _ _ _ _ (5 letters)
__
And this messages will repeat every N seconds with 1 more letter
Bot: Hint: e a _ _ _ 
__
Questions add in webpanel, and other things (settings, e.t.c)
Add possible disable/enable quiz from chat/webpanel, for bypass flood
When someone give answer, then after N secs ask other question

**Comment by sogehige** [comment]
https://community.sogebot.xyz/t/quiz-system/78
