### ISSUE TITLE
merge not work

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#496]
### Expected behavior
must work
### Actual behavior
not work
### Steps to reproduce
!merge
### Additional informations
Bot version:latest
Node.js version:8.6.0
Npm version:

0|bogsh    | 2017-11-03T04:58:43.391 <<< !merge satontx satontt [satontt]
0|bogsh    | 2017-11-03T04:58:43.799 !!! ERROR !!! Merge is not implemented!

**Comment by Satont** [comment]
Mongodb

**Comment by sogehige** [comment]
Yes, merge is not updated for new version yet
