### ISSUE TITLE
No system settings

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#508]
### Expected behavior
Must be
### Actual behavior
With this systems
```
"systems": {
    "timers": true,
    "customcommands": true,
    "keywords": true,
    "points": false,
    "price": false,
    "songs": false,
    "alias": true,
    "moderation": true,
    "ranks": false,
    "bets": false,
    "raffles": false,
    "queue": false,
    "cooldown": true,
    "gambling": false,
    "highlights": true,
    "commercial": true
  },
```
In webpanel absent "system" settings in webpanel
![img](https://satont.ru/s/1754.png)

### Steps to reproduce
Same settings
### Additional informations
Bot version: latest master
Node.js version: 8.6.0
Npm version:
Database engine: Mongodb

**Comment by sogehige** [comment]
Don't know what this issue is about

**Comment by Satont** [comment]
Where is "system" settings
Must be 
![img](https://satont.ru/s/3n46.png)
