### ISSUE TITLE
My api not working

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#519]
### Actual behavior
Im trying to make api, today its worked correctly, but now its not work. Nothing in chat, nothing in logs
### Steps to reproduce
(api|https://twitchbot.ga/songvkdj.php?id=9607&iv=98023283&e=https://www.youtube.com/channel/UCqaay_q0YERQBEg4o5EjvZw) (api._response)
### Additional informations
Bot version: latest master
Node.js version: 8.6.0
Npm version:
Database engine: mongodb

![img](https://satont.ru/s/5x24.png)
![img1](https://satont.ru/s/3d9a.png)

**Comment by sogehige** [comment]
No support for custom anything

also, your api's response is
`https://www.youtube.com/channel/UCqaay_q0YERQBEg4o5EjvZw`

**Comment by Satont** [comment]
Ok.. sry

**Comment by sogehige** [comment]
Hmm, this seems as actual issue, forgot that _response should return string response...sorry :)
