### ISSUE TITLE
Documentation about use of the features

### ISSUE THREAD

**Issue by cesareisma** [sogehige/SogeBot#52]
I'm currently trying your SogeBot on my RaspberryPi. All good so far, it seems to work perfect.

The only problem I have is that I don't fully understand your use of the features you're offering with this great bot. How does !alias work? Can you give me an example how I can use the command parameter?

And I tried to login to myip:20000/ytplayer but it asks for authorization. What username and password do I use there?

It would be nice to expand the README a bit about how the features work by giving some simple examples.

See this issue as a feature request. I hope you can answer my questions though!

Keep up the good work!

Cheers,
Cesar

**Comment by sogehige** [comment]
Yes, documentation is really necessary and as I am adding things to bot, it may seems more complicated. I'll work on documentation as soon as possible.

**For your questions:**
Authorization for YTPLAYER is set in config.ini.

You can also enable/disable systems in config.ini (although, this will possibly change in future), which needs a restart of bot.

_!alias_
Example of usage. Points system have !points command to show how many points user have. With alias, you can set it to !exp
!alias add points exp

_for list of aliases_
!alias list

_remove alias_
!alias remove exp

**Please, if you encounter any bug (and you will), or have any issue with bot, please, create github issue, so I can fix it**

**Comment by sogehige** [comment]
Also, feel free to ask in this issue thread until docs will be up

**Comment by cesareisma** [comment]
Thank you for your quick reply!
And my bad, I completely missed the ytplayer part in the config.ini. I can access it now, thanks!

About the !alias command:
I try what you said but it doesn't work.
The bot says it's added to the alias list and I can confirm when I do an _!alias list_.
However, when I do a _!exp_ in chat, there's no response.
The !points command works fine though.

**Comment by sogehige** [comment]
You are right, it doesn't work _sigh_, will raise an issue and fix it now

**Comment by sogehige** [comment]
Fixed - 81a16cf

**Comment by cesareisma** [comment]
Wow, that's what I call a quick fix haha. I will play around with the bot some more and report back to you if I found more bugs.

Thank you.

**Comment by sogehige** [comment]
I am glad to help, if you found more bugs, please create new issue, so we can keep this thread clean and bugs will be more visible
I will slowly update wiki with documentation https://github.com/sogehige/SogeBot/wiki

**Comment by sogehige** [comment]
Uff, took me a little bit time, I hope I didn't forget anything :)
https://github.com/sogehige/SogeBot/wiki/Command-list

**Comment by cesareisma** [comment]
Man, you're the fastest dev I've ever seen committing things. Good job!
The Wiki is really helpful! Cheers.

**Comment by sogehige** [comment]
You just created issue, when I had a time :)
