### ISSUE TITLE
Rename bug with timer

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#534]
### Expected behavior
Fix
### Actual behavior
2 different bots
on first seems like cant rename timer to name with space
on second like cant rename from "10" to "1" or other name, "qwe" for example, its give me empty timer
Like on screen i try to rename "10" to "qwe"
![img](https://satont.ru/s/8f1a.png)
### Steps to reproduce
1) for first problem rename timer from "qwe" to "qwe qwe"
2) idk
### Additional informations
Bot version: Latest master
Node.js version: 9.2.0
Npm version: 5.5.1
Database engine: Mongodb

No any errors in logs.

**Comment by sogehige** [comment]
Fixed
1. space will be changed to underscore
2. fixed issue with number rename
