### ISSUE TITLE
!points rain [amount] doesn't set points

### ISSUE THREAD

**Issue by cesareisma** [sogehige/SogeBot#54]
When trying to set points for _!makeitrain_ by using the command _!points rain 100_ it ignores the command and outputs the !points (amount of points) instead.

**Comment by sogehige** [comment]
!points rain is not correct command
https://github.com/sogehige/SogeBot/wiki/Command-list#commands--owner-5

Make it rain is used like this
!makeitrain [amount]
And it will give from 0 to [amount] of points to all online users...

**Comment by cesareisma** [comment]
Ok, but then you should change the output when I type !makeitrain.
The bot responds with:
_**Sorry, zweetbek , but this command is not correct, use !points rain [amount]**_

This can confuse people.

**Comment by sogehige** [comment]
Fixed - 9523d678b32ebcef233134bb91ebb0c54722896f
