### ISSUE TITLE
New viewers and chat message count is always 0

### ISSUE THREAD

**Issue by sogehige** [sogehige/sogeBot#551]
### Additional informations
Bot version:
Node.js version:
Npm version:
Database engine:

**Comment by tarumes** [comment]
message count is saved in DB but in /#/viewers/list still 0
bot version 9.0.3
node version v12.3.1
npm: '6.9.0'
DB engine nedb

**Comment by sogehige** [comment]
@tarumes this is not same issue, this is for stats panel also from 2017, please create new issue, thanks
