### ISSUE TITLE
(CZ) Změna velikosti velice zmenšuje chat jako kdyby byly widgety na všech místech

### ISSUE THREAD

**Issue by Bazimek** [sogehige/sogeBot#559]
### Expected behavior
Změna velikosti webpanel okna jako ve starších verzích.
### Actual behavior
Při změně velikosti webpanelu okna např. na polovinu se chat příliš zmenší jako kdyby na všech místech (vlevo|uprostřed|vpravo) widgety. Ve staré verzi se widgety posunuly a vlevo byl pouze chat a vpravo veškeré widgety, takže panel s chatem zůstal stále velká a čitelný.
### Steps to reproduce
Zmenšit chrome okno s webpanelem.
### Additional informations
Bot version: 5.8.0 - alpha 4
Node.js version: 9.0.0
Npm version: 5.5.1
Database engine: Standard

##### Attach your logs/exception.log file if bot crashes
![smrstovani novy bot vs stary bot](https://user-images.githubusercontent.com/17622398/33527016-a6ef1cec-d849-11e7-8441-136c01ecb166.jpg)

**Comment by sogehige** [comment]
Widgets width, height, position can be updated as wanted
