### ISSUE TITLE
Eval bug with (!command)

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#562]
### Actual behavior
For example try to:
Command `!b` with response `(eval var random="promotive";if(typeof param==="undefined"){if(random==="promotive"){return sender+" пытался ударить стримера, но сори , как бы отлетаешь очередняра " + '(!uptime)'}else{return sender+" попал по тупой голове "+random}};)`
It will give me error
`10|promoti | 2017-12-05T12:07:40.720 !!! ERROR !!! Possibly Unhandled Rejection
10|promoti | 2017-12-05T12:07:40.721 !!! ERROR !!! Promise {
10|promoti |   <rejected> TypeError: Cannot read property 'toLowerCase' of undefined
10|promoti |     at Users.set (/home/bots/promotive/libs/users.js:163:23)
10|promoti |     at Object.Twitch.lastseenUpdate [as lastseen] (/home/bots/promotive/libs/twitch.js:366:16)
10|promoti |     at Parser.addToQueue (/home/bots/promotive/libs/parser.js:84:39)
10|promoti |     at <anonymous>
10|promoti |     at process._tickCallback (internal/process/next_tick.js:188:7) }
`
If i delete (!uptime) it will work correctly.
Second example:
have 2 commands
1) `!bban` with response `/timeout $sender`
2) `!b` with response` (eval return sender + ' want to suicide.. And i'll help him (!bban.sender)'`
It's will give me this errors: 
`10|promoti | 2017-12-05T12:10:54.549 !!! ERROR !!! username is NULL!
10|promoti | Error
10|promoti |     at Users.set (/home/bots/promotive/libs/users.js:161:67)
10|promoti |     at Object.Twitch.lastseenUpdate [as lastseen] (/home/bots/promotive/libs/twitch.js:366:16)
10|promoti |     at Parser.addToQueue (/home/bots/promotive/libs/parser.js:84:39)
10|promoti |     at <anonymous>
10|promoti |     at process._tickCallback (internal/process/next_tick.js:188:7)
10|promoti | 2017-12-05T12:10:54.566 !!! ERROR !!! Possibly Unhandled Rejection
10|promoti | 2017-12-05T12:10:54.568 !!! ERROR !!! Promise {
10|promoti |   <rejected> TypeError: Cannot read property 'toLowerCase' of undefined
10|promoti |     at Users.set (/home/bots/promotive/libs/users.js:163:23)
10|promoti |     at Object.Twitch.lastseenUpdate [as lastseen] (/home/bots/promotive/libs/twitch.js:366:16)
10|promoti |     at Parser.addToQueue (/home/bots/promotive/libs/parser.js:84:39)
10|promoti |     at <anonymous>
10|promoti |     at process._tickCallback (internal/process/next_tick.js:188:7) }
`
### Steps to reproduce
Command in eval
### Additional informations
Bot version: Latest master
Node.js version:
Npm version:
Database engine:

**Comment by sogehige** [comment]
User get lost between those commands, will fix

**Comment by alreadylostmyself** [comment]
But first command not cotnain user, bug too?

**Comment by sogehige** [comment]
Both errors you described are
TypeError: Cannot read property 'toLowerCase' of undefined 10|promoti | at Users.set

which means, that users for set is missing
