### ISSUE TITLE
!playlist add crashes bot

### ISSUE THREAD

**Issue by dyindude** [sogehige/sogeBot#568]
### Expected behavior
Requested song added to playlist. I am trying to set up a fresh install with a new release of sogeBot.
### Actual behavior
Bot crashes:
```
2017-12-06T04:34:30.650 <w< !playlist add https://www.youtube.com/watch?v=XXXXXXXXXXXX [dyindude]
2017-12-06T04:34:31.863 !!! ERROR !!! +------------------------------------------------------------------------------+
2017-12-06T04:34:31.863 !!! ERROR !!! | BOT HAS UNEXPECTEDLY CRASHED                                                 |
2017-12-06T04:34:31.863 !!! ERROR !!! | PLEASE CHECK https://github.com/sogehige/SogeBot/wiki/How-to-report-an-issue |
2017-12-06T04:34:31.863 !!! ERROR !!! | AND ADD logs/exceptions.log file to your report                              |
2017-12-06T04:34:31.863 !!! ERROR !!! +------------------------------------------------------------------------------+
2017-12-06T04:34:31.864 !!! ERROR !!! uncaughtException: Cannot read property 'engine' of undefined
```

### Steps to reproduce
```
$ git clone https://github.com/sogehige/sogeBot.git
$ cp ~/config.json sogeBot/config.json
$ cd sogeBot
$ npm install
$ npm start
```
Wait for bot to start, send bot a message to add a song:
!playlist add https://www.youtube.com/watch?v=XXXXXXXXXXXX
### Additional informations
Bot version: 5.9.0 (also tested on master branch)
Node.js version: 8.9.2 (also tested with node 9.2.0)
Npm version: 5.5.1
Database engine: nedb

##### Attach your logs/exception.log file if bot crashes
`{"date":"Wed Dec 06 2017 04:34:31 GMT+0000 (UTC)","process":{"pid":10936,"uid":1000,"gid":1000,"cwd":"/home/ubuntu/soge/sogeBot","execPath":"/home/ubuntu/.nvm/versions/node/v8.9.2/bin/node","version":"v8.9.2","argv":["/home/ubuntu/.nvm/versions/node/v8.9.2/bin/node","/home/ubuntu/soge/sogeBot/main"],"memoryUsage":{"rss":397615104,"heapTotal":242417664,"heapUsed":205608488,"external":85103421}},"os":{"loadavg":[0.42626953125,0.22265625,0.130859375],"uptime":3084},"trace":[{"column":18,"file":"/home/ubuntu/soge/sogeBot/libs/systems/songs.js","function":null,"line":303,"method":null,"native":false},{"column":11,"file":"/home/ubuntu/soge/sogeBot/node_modules/ytdl-core/lib/info.js","function":"util.parallel","line":215,"method":"parallel","native":false},{"column":7,"file":"/home/ubuntu/soge/sogeBot/node_modules/ytdl-core/lib/util.js","function":"checkDone","line":416,"method":null,"native":false},{"column":26,"file":"/home/ubuntu/soge/sogeBot/node_modules/ytdl-core/lib/info.js","function":"SAXParser.parser.onend","line":284,"method":"onend","native":false},{"column":35,"file":"/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js","function":"emit","line":624,"method":null,"native":false},{"column":5,"file":"/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js","function":"end","line":667,"method":null,"native":false},{"column":14,"file":"/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js","function":"SAXParser.write","line":975,"method":"write","native":false},{"column":38,"file":"/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js","function":"SAXParser.close","line":157,"method":"close","native":false},{"column":20,"file":"events.js","function":"emitNone","line":111,"method":null,"native":false},{"column":7,"file":"events.js","function":"PassThrough.emit","line":208,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"endReadableNT","line":1056,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":138,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":180,"method":"_tickCallback","native":false}],"stack":["TypeError: Cannot read property 'engine' of undefined","    at /home/ubuntu/soge/sogeBot/libs/systems/songs.js:303:18","    at util.parallel (/home/ubuntu/soge/sogeBot/node_modules/ytdl-core/lib/info.js:215:11)","    at checkDone (/home/ubuntu/soge/sogeBot/node_modules/ytdl-core/lib/util.js:416:7)","    at SAXParser.parser.onend (/home/ubuntu/soge/sogeBot/node_modules/ytdl-core/lib/info.js:284:26)","    at emit (/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js:624:35)","    at end (/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js:667:5)","    at SAXParser.write (/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js:975:14)","    at SAXParser.close (/home/ubuntu/soge/sogeBot/node_modules/sax/lib/sax.js:157:38)","    at emitNone (events.js:111:20)","    at PassThrough.emit (events.js:208:7)","    at endReadableNT (_stream_readable.js:1056:12)","    at _combinedTickCallback (internal/process/next_tick.js:138:11)","    at process._tickCallback (internal/process/next_tick.js:180:9)"]}`

**Comment by sogehige** [comment]
Thats an issue format I like! :+1:
