### ISSUE TITLE
check certain user for is. in eval

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#570]
for example (eval if (random.online.viewer.is.subscriber === true) { do something};)

**Comment by sogehige** [comment]
`users` variable is exposed, you can check it in this variable

**Comment by alreadylostmyself** [comment]
Can you give example of this?
for "soge__" nickname for example

**Comment by sogehige** [comment]
`(eval if (_,find(users, (o) => o.username === 'soge__').is.follower) { return 'follower' } else { return 'not follower'})`
