### ISSUE TITLE
Same and not same random user in eval

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#571]
maybe some edit random users in eval 
want to random same and not same users
random.online.viewer[s] will same user
random.online.viewer not same

**Comment by sogehige** [comment]
What is use case? This would have performance impact. I think you should do a system if you want something more complicated...

**Comment by alreadylostmyself** [comment]
Something like !love (eval return "Cupid want to bring together (random.online.viewer[s]) and random.online.viewer[s])";)

**Comment by sogehige** [comment]
Hmm...I can add lodash `_` and `users` variables. Then you would be able to do

`_sample(_.filter(users, function(o) { return o.is.online })).username`

**Comment by sogehige** [comment]
Or let me re do variable

**Comment by sogehige** [comment]
You can do `(eval return "Cupid want to bring together " + _sample(_.filter(users, function(o) { return o.is.online })).username + " and " + _sample(_.filter(users, function(o) { return o.is.online })).username)`
