### ISSUE TITLE
Cannot read property 'online' of undefined

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#577]
### Actual behavior
My command: 
`(eval
    var a = "";
    var b;
    var c;
    var arr = _.map(_.sampleSize(_.filter(users, function(o) {
        return o.is.online
    }), 9), 'username');
    for (var i = 0; i < arr.length; i++) {
        b = '(!cban.' + arr[i] + ') ';
        a = a + b;
    };
    if (is.subscriber === false) {
        c = sender + ' тебя недостаточно знаний для использования такой сильной магии, мой друг.';
    } else {
        c = sender + ' кастует катаклизм и он оказывается настолько сильным, что убивает даже своих PogChamp . 9 человек отправляется в таймаут Keepo' + a;
    };
    return c;)`
Maybe its after X hours, of X time used this command i got this:
` 2017-12-08T14:38:25.694 !!! ERROR !!! Possibly Unhandled Rejection
 2017-12-08T14:38:25.696 !!! ERROR !!! Promise {
   <rejected> TypeError: Cannot read property 'online' of undefined
     at randomVar.online.viewer._.sample._.map._.filter (/home/bots/inv0kergirl/libs/parser.js:391:66)`
### Steps to reproduce
I don't know
### Additional informations
Bot version: 5.10.0-SNAPSHOT
Node.js version:
Npm version:
Database engine: MongoDB

**Comment by alreadylostmyself** [comment]
I can attach db, log file, or something another, if need

**Comment by sogehige** [comment]
Issue is https://github.com/sogehige/sogeBot/blob/master/libs/parser.js#L391, possibly some new user is loaded (follower cache or something like that ) and doesn't have full data, will fix
