### ISSUE TITLE
Points set to 0 if was 0 after merge

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#578]
### Actual behavior
LydiaKunoichi - 0 points
neverbethesame - 2160 points
user before merge `!merge -from LydiaKunoichi -to neverbethesame` now: `neverbethesame: !me
INV0KERBOT: @neverbethesame | 20.1h | 0 points  | 482 messages
### Steps to reproduce
merge
### Additional informations
Bot version: latest master 
Node.js version:
Npm version:
Database engine: Mongodb

**Comment by sogehige** [comment]
Actually, this is not a bug, all data from previous user will replace data on new user
