### ISSUE TITLE
"user-is-warned-about-blacklist" will contain blacklisted word

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#581]
"user-is-warned-about-blacklist": "Word $bannedword in blacklist, sry"
For example `code` in blacklist
**User: Here is my code 123HQW
Bot: Word code in blacklist, sry**
User was timeouted

**Comment by sogehige** [comment]
Not really sure if this is good idea, what if you have some swear words, personnal information, bot will just repeat what you want to hide

**Comment by alreadylostmyself** [comment]
We can use (if) filter for hide, doesnt right?

**Comment by sogehige** [comment]
sure, but common user will not do that

**Comment by alreadylostmyself** [comment]
Ok, then close issue
