### ISSUE TITLE
After delete command exists in permissions

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#584]
### Actual behavior
I delete 3 commands in permision, and after delete that still be in permissions 
![img](https://satont.ru/s/7G0c.png)
### Steps to reproduce
Maybe command with latters, or i dont know
### Additional informations
Bot version: master
Node.js version:
Npm version:
Database engine: MongoDb

**Comment by sogehige** [comment]
As workaround, restart of a bot should fix this

**Comment by sogehige** [comment]
To delete permissions, you will need to remove then from db directly, or create a same command -> delete
