### ISSUE TITLE
Aliase for points wrong permissions

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#606]
### Actual behavior
An aliase for !points runs only with owner permission
for example aliase !mana
`!mana add` will be runned as owner for all, but !points add have perrmission only for owner
### Steps to reproduce
Create alise for !points
### Additional informations
Bot version: latest master
Node.js version:
Npm version:
Database engine: MongoDB

**Comment by sogehige** [comment]
Not sure what your issue is. If you create alias of command, it will inherit command permission, you can then change that permission in permissions settings

**Comment by alreadylostmyself** [comment]
Users can abuse points with my aliase.
My permissions: ![img](https://satont.ru/s/0M65.png)
I just have 1 aliase for !Points
![img1](https://satont.ru/s/1Y76.png)
And users can run `!mana add username 99999999`, but my permission for`!points add` only for owners
It should not be like that, doesn't right?

**Comment by alreadylostmyself** [comment]
I think probles is that aliase inherit only `!points` permissions, but it not inherit for `!points add` and others

**Comment by sogehige** [comment]
Yes `!mana give` should not work or should have same permissions as corresponding command. Will check

**Comment by alreadylostmyself** [comment]
It will great if you can fix that.
More more customization :)
