### ISSUE TITLE
Input span change to "..." after disable/enable or change visible (commands page)

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#607]
### Actual behavior
On custom commands page when i disable, or change  visible, then for 1 second variables in input change to ... and page a little bit jump for 1 second
https://satont.ru/s/0N04.gif
thats what i mean
### Steps to reproduce
Disable/enable some command in webpanel
Or change visible
### Additional informations
Bot version: latest master
Node.js version:
Npm version:
Database engine: mongodb

**Comment by sogehige** [comment]
UI changed, not valid anymore
