### ISSUE TITLE
Add requested by in Music Player widget

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#610]
Add `Requested by` on next line after `Current song` in Music Player widget
Something like on screenshot
![img](https://satont.ru/s/8489.png)

**Comment by sogehige** [comment]
Changed it to 
![sogebot ui 5 11 0 snapshot](https://user-images.githubusercontent.com/19549652/34570266-75b77652-f16b-11e7-954b-59e79aff8d91.png)

Username will not be visible if its from playlist, also removed `Current Song` text so we will have more space for usernames
