### ISSUE TITLE
Add feature limit song requests by rank/role

### ISSUE THREAD

**Issue by scott-42** [sogehige/sogeBot#621]
This is a feature request to limit the number of songs that a viewer can add to the queue based on their rank/role.

Currently a user can add an unlimited number of songs to the queue. I would like the ability to limit the number of songs that a user can add to the current queue. For example:
    Viewer: 1
    Follower: 3
    Subscriber: 10
    Moderator: 100
    Owner: 100

**Comment by sogehige** [comment]
https://community.sogebot.xyz/t/add-feature-limit-song-requests-by-rank-role/68
