### ISSUE TITLE
Support of alternate video stream player

### ISSUE THREAD

**Issue by scott-42** [sogehige/sogeBot#630]
This is a feature request for providing support of alternate video stream players instead of using the embedded ytplayer in the dashboard. Alternatively figure out a way to get JACK output from the dashboard.

The problem I have is that when displaying the dashboard, the browser (Firefox or Chrome) does not support linux audio output to JACK so when the YTPlayer is streaming audio content it tries to go to ALSA/Pulseaudio only. If you are using JACK for your microphone or other audio equipment, it is very difficult to get ALSA output to play along with JACK at the same time. OBS supports JACK on linux.

The solution is to allow other audio options such as command line programs to be triggered for playback. For example you can use youtube-dl and mplayer to stream the youtube video and send the audio to JACK. An example command line would be (with small video window for monitoring output):
`youtube-dl -q -o- https://www.youtube.com/watch?v=WSUFzC6_fp8 | mplayer -cache 8192 -ao jack:port=system -endpos 3:16 -geometry 100%:100% -vf scale=270:270 -volume 10 -really-quiet -`
no video example:
`youtube-dl -q -o- https://www.youtube.com/watch?v=WSUFzC6_fp8 | mplayer -cache 8192 -ao jack:port=system -endpos 3:16 -volume 10 -really-quiet -vo null -`
This still gives you the ability to add options for trimming the video length `-endpos [mm:]ss` and using the normailized volume adjustment `-volume [-1-100]`. All of the command line parameters should be user options so that the user can select the appropriate options for them.

JACK audio [http://www.jackaudio.org/](http://www.jackaudio.org/)
youtube-dl [http://rg3.github.io/youtube-dl/](http://rg3.github.io/youtube-dl/)
mplayer [http://mplayerhq.hu/](http://mplayerhq.hu/)

**Comment by sogehige** [comment]
This is really interesting feature request. Although I don't think this is some common usecase. Possibility is to change current songs system to send socket message of videoId to sogeticker and then sogeticker can possibly start proper command. There will be need to update widget as well and not only widget. I don't think I'll do this feature, but I'll keep it open for now

**Comment by sogehige** [comment]
Btw: isn't it possible to route chrome to pulseaudio -> jack?

**Comment by scott-42** [comment]
It is possible to route all audio from pulseaudio to jack but it really sucks. For example, you have an app like FF/Chrome playing back a video and the audio is sent to the sink which goes out the system speakers. Now the browser video player has a volume control which you set (say to 10% for background music) and that affects the system speakers output. The OS has a volume control and if you change that it also affects the system speakers. The big problem is that it is not run like a real mixer in that each change you make to any volume will adjust the volume that JACK sees as the input volume for the source. So if I set my system volume to 50%, then my music is really at 5% as far as the JACK audio can tell.

Ideally you want each source (background music, microphone, desktop sounds) to have their own channel such that each sends the audio signal at 100% and then you can mix it down to the appropriate mix that you want. Then think of the system speakers as just a monitor for sounds and you can pipe whatever channel you want to the system speakers for output or send the final mix so you can hear it and monitor the output. I generally want the mic muted on the monitor as I don't want to hear myself talk so I use a slightly different mix output. And with semi-pro gear, I'm not sending the monitor mix to the system speakers but instead sending it to a special audio output channel on a digital to analog converter.

I'm not a node or JS developer so I haven't really looked at the source much. But I know how to do what I want done in other languages, I just need to figure out how to fire off commands in node and then get the mplayer in slave mode and trigger it with a play message.

**Comment by sogehige** [comment]
I am sorry...I dont have skill for this
