### ISSUE TITLE
Issue starting sogeBot

### ISSUE THREAD

**Issue by andrexsaddler** [sogehige/sogeBot#631]
latest sogebot update and latest npm

> pi@raspberrypi:~/sogeBot $ npm start
> 
> > sogebot@5.11.0-SNAPSHOT start /home/pi/sogeBot
> > node ./tools/migrate && npm-run-all --parallel build-css copy:dist && cross-env NODE_ENV=production node ./main || true
> 
> /home/pi/sogeBot/tools/migrate.js:8
> (async () => {
>        ^
> 
> SyntaxError: Unexpected token (
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:140:18)
>     at node.js:1043:3
>

**Comment by Ayysir** [comment]
@sogehige

**Comment by sogehige** [comment]
I think you don't have latest nodejs. You need version 8+

**Comment by andrexsaddler** [comment]
@sogehige using nodejs 8 worked however im getting this now: 
https://imgur.com/a/2cWRk

**Comment by sogehige** [comment]
Set your domain in config.json to that IP you are using to access dashboard

**Comment by andrexsaddler** [comment]
@sogehige that worked thanks! 

one suggestion though, lastest follower list, lists from old to new top down instead of new to old top down

**Comment by sogehige** [comment]
Please make separate issue, I can add some switch to widget to reverse order
