### ISSUE TITLE
Much api errrors

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#632]
### Actual behavior
Got much api errors and after that got disconnect from tmi server (last line in log)
### Additional informations
Bot version: latest master
Node.js version:
Npm version:
Database engine: 

##### Attach your logs/exception.log file if bot crashes
[sogebot-2017-12-28T04_42_01.log](https://github.com/sogehige/sogeBot/files/1592513/sogebot-2017-12-28T04_42_01.log)

**Comment by sogehige** [comment]
Would need API charts when this ocurred
