### ISSUE TITLE
Add ability to use a querystring response filter

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#635]
This will allow commands to use tracking sites for games.

i.e what is described by this tracker  https://2g.be/twitch/Fortnite/#start

**Comment by sogehige** [comment]
Done on master

**Usage example:**

*custom command* - somehow *&channel=yourchannel* needs to be added for this command to work
`!fortnite` ->
 `(api|https://2g.be/twitch/Fortnite/command/query=$querystring&default_platform=pc&default_playlist=solo&channel=test) (api._response)`

*chat*
`!fortnite stats xgerhard`

*bot response*
`System: [Dev] xgerhard's stats summary: [Wins: 3, Matches: 204, K/d: 1.77, Kills: 355, Kills Per Match: 1.74]`
