### ISSUE TITLE
Not able to change game title on 2nd+ in game choice carousel

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#641]
1st initial game allows for you to change title but adding another game to carousel wont allow you to change game title different from initial title. The Game and title function then does not function at all and only allows for changing game.

All other functions of the bot works fine. Bot in chat is a mod and recognized as so in Bot.
VERSION: 5.10.2

**Comment by sogehige** [comment]
Is bot set as editor as well?

**Comment by Ayysir** [comment]
@sogehige yes, I made sure of that

**Comment by sogehige** [comment]
Can you provide some more specific steps or images so I can found what your issue is? Thanks!

**Comment by Ayysir** [comment]
@sogehige

1. Go to game section and type in a game you're currently streaming.
2. Set title from that screen as well
3. Change to a different game and try to create a new stream title. It will
not save and display the new one you've made

Or

1. Choose game and make title
2. Go to title section and create another title. It will not enforce new
change.

On Jan 2, 2018 2:58 AM, "sogehige" <notifications@github.com> wrote:

Can you provide some more specific steps or images so I can found what your
issue is? Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sogehige/sogeBot/issues/641#issuecomment-354716556>,
or mute
the thread

**Comment by sogehige** [comment]
I think I reproduced it, thanks

**Comment by Ayysir** [comment]
No problem @sogehige
