### ISSUE TITLE
Can't add command or alias with Korean

### ISSUE THREAD

**Issue by xotlr43** [sogehige/sogeBot#657]
### Issue description:
well, I tried to use korean with SogeBot but it seems using Korean crash SogeBot web panel, nedb behavior.

### Expected behavior
!command add !한글 react
=> $username, command !한글 was added
             or
!alias add !한글 !command
=> $username, alias !한글 for !command was added

### Actual behavior
Sorry, $username, but this command is not correct, use !commands

### Steps to reproduce
Chat '!command add !한글 react'

### Additional informations

Bot version: 5.10.2
Node version: 9.3.0
NPM version: 5.5.1

**Comment by sogehige** [comment]
Yes, Korean chars are not supported, javascript is not much unicode friendly in some functions. Will check what I can do with it
