### ISSUE TITLE
Enable using Response filters in Event Listeners messages 

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#660]
tried to use "$game" in my tweet event listener

example: https://twitter.com/iamaleyev/status/949853593221386240

**Comment by sogehige** [comment]
Problem is, tweet doesn't go through message pipeline -> filters are ignored

**Comment by Ayysir** [comment]
Is there anyway to run a check if a filter variable used? I.e check if
variable is used, translate it then post tweet?

**Comment by sogehige** [comment]
Yes, its fixed on master, will be in next version

**Comment by Ayysir** [comment]
Thanks. Just trying to help anyway I can

**Comment by Ayysir** [comment]
I dont see change reflected in master branch @sogehige
