### ISSUE TITLE
Suggestion: exclude from !top and ignore user in bot

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#661]
Right now bot owners excluded from bot
I suggest add command and button in webpanel, what will toggle exclude user or include in top
Or maybe simble checkbox, but it will be nice.
Also make checkbox for enable ignore this user in bot (bot will ignore that user absolutely)

**Comment by Kazanka101** [comment]
Too add to this it might be better instead of a simple checkbox to have a field to list who you want to be excluded instead. Gives you more customization that way.

**Comment by sogehige** [comment]
Please split this to two separate issues

**Comment by alreadylostmyself** [comment]
exclude from top and ignore? or what?

**Comment by sogehige** [comment]
This are 2 issues, 
- bot ignore user
- exclude user from top

**Comment by sogehige** [comment]
https://github.com/sogehige/sogeBot/issues/685
