### ISSUE TITLE
Feature Request: Add a response filter variable to grab another streamer's title/game status

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#670]
### Expected behavior

Essentially if i wanted to setup a !shoutout command i can simply just use $param function. However if i want to go more indepth and add ability to display their latest game or stream title into the command.

i.e
"Please take a moment to check out some "$param.game"action with $param. Give them a follow at twitch.tv/$param and check out their amazing content!"

something amongst those lines

**Comment by sogehige** [comment]
Yes this should be possible

**Comment by sogehige** [comment]
Added this filters for 7.3.0

`(stream|#|game)`, `(stream|#|title)`, `(stream|#|viewers)` where `#` is channel name

**Comment by Ayysir** [comment]
@sogehige any example on how to implement this in a command?

**Comment by Ayysir** [comment]
any example on how this can be used in a command?

**Comment by Ayysir** [comment]
@sogehige any example on how this can be used in a command?

**Comment by Ayysir** [comment]
@sogehige tried it... only outputs: 

Shoutout to aleyev! Playing (stream|aleyev|game) - (stream|aleyev|title) for (stream|aleyev|viewers) viewers!

**Comment by sogehige** [comment]
Are you using 7.3.0-SNAPSHOT? It's not yet released

**Comment by Ayysir** [comment]
@sogehige yeap I am

**Comment by sogehige** [comment]
@Ayysir Please check latest release, it's working for me on latest 7.4.0-SNAPSHOT and on current 7.3.0 release
