### ISSUE TITLE
Suggestion: Time stamp order option

### ISSUE THREAD

**Issue by xotlr43** [sogehige/sogeBot#677]
there's no option for change time stamp order.

libs/twitch.js
Line: 787
.replace(/\$when/g, moment.unix(user.time.message / 1000).format('DD-MM-YYYY- HH:mm:ss')), sender)

have specific time stamp order that used for !lastseen command

**Comment by sogehige** [comment]
You mean be able to change format of timestamps, right?

**Comment by xotlr43** [comment]
Yes :-)

**Comment by sogehige** [comment]
I believe #676 is same issue, right?
