### ISSUE TITLE
Request: make own vars

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#687]
My future request is: make possible create own vars
it will be in settings, and will be usable everywhere
for example i want use it in (api) filter, i.e: `(api|http://mygreatapi.com/mmr?id=$id) (api_.response)`, ant that filter i like to use in lang file.
So it will be more accessibly to change `id` var from var page in webpanel, not lang

**Comment by sogehige** [comment]
You can use custom variables for this
