### ISSUE TITLE
Missed translations

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#689]
I will list missed translations here:

- When add timers there is english name, messages, seconds, and buttons: save, cancel
- When add commands same as timers
- When add keywords same as commands and timers
- When add price same as commands, timers, keywords
- When add ranks same as commands, timers, keywords, price
- "Sorry, timer name can contain only a-z, A-Z, 0-9, _" message when type incorrect name for timer
- Lang for Manage>events all placeholder inputs is on english
- Lang for "Save changes" button in viewers>ignorelist
- Lang for "loading data" in eventlist
- Lang for loading on "translations" page
- Lang for "overlay testing" and buttons for it. In Settings>overlays. Same for others tabs
___
Will post some more as comment for this issue, if i'll found

**Comment by Banonevar** [comment]
Lang for `Add response` at editing of command page

**Comment by sogehige** [comment]
please make separate issues its hard to track it

**Comment by sogehige** [comment]
Closing, not sure if this is valid anymore
