### ISSUE TITLE
Several domains in config

### ISSUE THREAD

**Issue by alreadylostmyself** [sogehige/sogeBot#703]
Different adresses for panel
make avalible to make 1,2,3,4,5 or N adresses for panel what
Change in config `"domain": "localhost"` to:
`"domains": "localhost, site1.com, site2.net",

**Comment by sogehige** [comment]
What is use case?

**Comment by alreadylostmyself** [comment]
When nginx done, or something with nginx will be possible use panel on ip adress like `127.0.0.1:20000`
It may help find issues, maybe

**Comment by alreadylostmyself** [comment]
1 more example it's i.e i have hero runned bot with cname domain, but if something will happend with this domain i'll have no access to bot webpanel until i',m not edit my config.json, so if i'll be able to make more then 1 domain i can access bot webpanel via herokuapp domain what always avalible

**Comment by sogehige** [comment]
Yes, that's nice use case
