### ISSUE TITLE
Feature Request: Ability to flip EventList Overlay horizontally or Vertically

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#720]
At the moment there is no adjustment settings to change appearance

**Comment by sogehige** [comment]
What you exactly mean?

**Comment by Ayysir** [comment]
Follow is aligned right of eventlist and list names are aligned right as
well. Wanting ability to align left and have follow/sub/bits to left side

**Comment by sogehige** [comment]
Oh I see,
you mean like

time|user|icon -> icon|user|time? This can be done, can add to next version

and change date order right? I mean newest is last, etc.

**Comment by Ayysir** [comment]
@sogehige yeap

**Comment by sogehige** [comment]
You can already use this GET params
order=asc|desc **order by time asc or desc**
ignore=subs,follow,cheer,resub **don't show events specified in ignore**
count=5 **how many events should be shown**
will add display=event,username **display event type, than username, default value will be as it is now: username,event**

example:
http://localhost:2000/overlays/eventlist?order=asc&ignore=host&count=5

FYI: I will update behavior of count when ascended order is selected as it doesn't make sense as it is now

If you have data:
1,2,3,4,5,6,7,8,9,10

current behavior when count 5:
asc - 1,2,3,4,5
desc - 10,9,8,7,6

expected: 
asc - 6,7,8,9,10
desc - 10,9,8,7,6

also need to check if this GET is in docs and add event classes for each eventline to get better css support

**Comment by sogehige** [comment]
Updated css classes are generated as:
```
<ul id="eventlist">
    <li class="event follow">
        <strong class="username">user1</strong>
        <span class="event">follow</span>
    </li>
</ul>
```

**Comment by sogehige** [comment]
Updated docs https://github.com/sogehige/sogeBot/wiki/Custom-properties-for-eventlist
