### ISSUE TITLE
Request: send something as channel owner

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#740]
If broadcaster oauth passed then make possible send command in irc as owner
For example for timeout mods

**Comment by sogehige** [comment]
I don't see additional value of this as it will complicate some stuff, would be enough to force timeout by owner if user is mod?

**Comment by sogehige** [comment]
Also how do you want to timeout mods? Basically mods are not persecuted by moderation system and sending messages as channel owner is security risk
