### ISSUE TITLE
[Issue] StreamLabs API OAuth Password Generator

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#795]
### Actual behavior
StreamLabs API OAuth Password Generator returning `"User not in whitelist."`

**Comment by sogehige** [comment]
Yes waiting for app approval from streamlabs

Dne 6. 3. 2018 4:16 dop. napsal uživatel "Andre Saddler" <
notifications@github.com>:

**Comment by sogehige** [comment]
Will close this when approved

**Comment by sogehige** [comment]
But, if you are interested, I can manually whitelist users

**Comment by Ayysir** [comment]
I'm interested @sogehige

**Comment by sogehige** [comment]
PM me usernames you want to add on discord

**Comment by Ayysir** [comment]
@sogehige i dont see your discord so i emailed you
