### ISSUE TITLE
Feature Request: Go Live Notification

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#821]
Allow creating a live notification text field similarly how it is in twitch dashboard

**Comment by sogehelper** [comment]
Notification where?

**Comment by Ayysir** [comment]
@sogehelper @sogehige https://help.twitch.tv/customer/portal/articles/2899785-how-to-use-go-live-notifications

**Comment by sogehelper** [comment]
You must setup it in your twitch dashboard i think
They not provide api for change this message 
Correct me it's not right
