### ISSUE TITLE
Issue: Using Herokuapp with spotify integration

### ISSUE THREAD

**Issue by Ayysir** [sogehige/sogeBot#834]
in file instructions was the explicit enough, though this may be the wrong place to ask but having issues after i make spotify application
i do 
<herokuapp domain>/oauth/spotify in spotify settings dev dashboard but i get `Cannot GET /null` after entering clientid and clientsecret with the uri

**Comment by sogehige** [comment]
you need to do
http://yoururloriptoaccessdashboard.com/oauth/spotify

**Comment by sogehige** [comment]
I will do docs tomorrow if I have time

**Comment by Ayysir** [comment]
Unfortunately that's what I did with same result

**Comment by sogehige** [comment]
Can you describe your issue step by step? Also, what is your callback uri in spotify apps?

**Comment by Ayysir** [comment]
I did:

https://<name>.herokuapp.com/oauth/Spotify and
https://<name>.herokuapp.com/callback

In Spotify
(<name> just a place holder in this example)

And added it to the dashboard in sogeBot


On Mar 11, 2018 6:42 PM, "sogehige" <notifications@github.com> wrote:

Can you describe your issue step by step? Also, what is your callback uri
in spotify apps?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sogehige/sogeBot/issues/834#issuecomment-372156389>,
or mute
the thread

**Comment by sogehige** [comment]
in spotify you need
https://<name>.herokuapp.com/oauth/spotify

**Comment by Ayysir** [comment]
That's interesting. Research didn't denote that. If that's correct then
what do I add to sogeBot integration tabs

**Comment by sogehige** [comment]
oauth/spotify link should be same in spotify and a bot

**Comment by Ayysir** [comment]
Must be something I am doing. Receiving same result. I'll just forego using
the integration I guess

**Comment by sogehige** [comment]
When do you have null issue?

**Comment by Ayysir** [comment]
When pressing authorize

**Comment by sogehige** [comment]
Can you try latest master and https://github.com/sogehige/sogeBot/wiki/Spotify

**Comment by Ayysir** [comment]
@sogehige did exactly as wiki demonstrated, hitting disable button to
enable results all fields to clear. Could be heroku issue. I tried on 3
different browser. Same results

**Comment by sogehige** [comment]
Did you click save button or enter when saving id, token, url?

**Comment by Ayysir** [comment]
Uri in Spotify dashboard is full. Issue is when entering information into
bot dashboard then pressing disable button to enable, this causes all text
fields to clear hence not allowing auth

**Comment by sogehige** [comment]
Yes, and did you click save buttons in bot? They appear when you change anything beside changed field

**Comment by Ayysir** [comment]
Wiki didn't specify that as when copy and pasting IDs there is a leading
space/padding in front. For save icon to prompt I have to backspace in
front of IDs. Works as intended now after those adjustments

On Mar 12, 2018 8:02 AM, "sogehige" <notifications@github.com> wrote:

Yes, and did you click save buttons in bot? They appear when you change
anything beside changed field

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sogehige/sogeBot/issues/834#issuecomment-372286866>,
or mute
the thread

**Comment by sogehige** [comment]
Good point, will fix that. Good we find an issue :)

**Comment by Ayysir** [comment]
After all that lol..
