### ISSUE TITLE
Bug: (!) filter not working

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#908]
### Actual behavior
when try to use (!permit $sender) got this in console:
`2018-04-13T17:38:07.062Z !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'toLowerCase' of undefined
    at Users.get (libs\users.js:341:23)
    at Object.participate [as fnc] (libs\systems\raffles.js:274:115)
    at Parser.process (libs\parser.js:57:35)
    at <anonymous> } reason: TypeError: Cannot read property 'toLowerCase' of undefined
`

**Comment by sogehige** [comment]
This is raffles issue

Dne pá 13. 4. 2018 19:51 uživatel sogehelper <notifications@github.com>
napsal:

**Comment by sogehelper** [comment]
Without raffles it will work?
Does you will fix that?
