### ISSUE TITLE
I not see viewers list in dashboard

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#909]
### Actual behavior
I open viewers page, and got it in console
Uncaught TypeError: Cannot read property 'toLowerCase' of null
On 121 `return o.username.toLowerCase().indexOf(viewers.toSearch.toLowerCase()) >= 0;`
![img](https://i.imgur.com/pk0VBsd.png)

**Comment by sogehelper** [comment]
Also when try to cleanup

**Comment by sogehige** [comment]
Cannot reproduce

**Comment by sogehelper** [comment]
Now it's without any errors, all my bots can't load viewers.
I open viewers page, a little bit later appears page paginator where only 1 page, but users still not visible

**Comment by sogehelper** [comment]
Now it's working
