### ISSUE TITLE
Bug: command with custom variable not work

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#910]
### Actual behavior
I have command with some variable, and when try to use this command it's not send message in chat.
No errors in bot console.
### Steps to reproduce
!command add viewer !test $_test
!test
### Additional informations

Latest master of bot

**Comment by sogehige** [comment]
Working without issue, cannot reproduce

**Comment by sogehelper** [comment]
This variable was increased by event.
maybe it will help reproduce
Also it's text variable not number, maybe it's affect

**Comment by sogehelper** [comment]
Changed this variable from text to number and it's still not working
But i created new variable and new variable working
So maybe issue with icreased by event variable?
