### ISSUE TITLE
Bug: bot in !top time

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#911]
### Actual behavior
my bot in !top time, but it not must be here

**Comment by sogehige** [comment]
Cannot reproduce, bot username is properly filtered out

**Comment by sogehelper** [comment]
Can you link me string where it filtered? Maybe i have old version or something like that

**Comment by sogehige** [comment]
https://github.com/sogehige/sogeBot/blob/master/libs/twitch.js#L308

**Comment by sogehelper** [comment]
My string exactly same in my twitch.js

**Comment by sogehelper** [comment]
Hm, maybe i know what's wrong.
In my config.json bot_username in uppercase
But in !top time bot username in in lowercase
Maybe something related to this?
