### ISSUE TITLE
Duels working not correctly

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#914]
### Actual behavior
Things i noticed:
1) user started duel, but if he will be more points after some time this will break his old bet, old+new, will be juts new
2) some users not lost points after bet
3) some bets wasn't added to bank, but message about it in chat
And maybe more and more.. can't find it all, but there is much bugs

**Comment by sogehelper** [comment]
user: !duel 5
Bot: @user want start duel!  duel [points], for join, you have 1 minutes.
Bot: @user good luck. You bet 5 points!
user2: !duel 5
Bot: @user2 good luck. You bet 5 points!
->>> 1 minute left
Bot: Only @user2 have balls for duel. Your bet will return to you (5 points)

**Comment by sogehelper** [comment]
and **user** lost points after that

**Comment by sogehige** [comment]
Reproduced
