### ISSUE TITLE
!gamble can make user points to -

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#928]
### Actual behavior
user have 10 points, he wil !gamble 10, and after that if he lose it will -10

**Comment by sogehige** [comment]
Points from gamble is removed only once on start and returned on win....user could've lose points other way

**Comment by sogehelper** [comment]
nope. i tryed it by myself

**Comment by sogehelper** [comment]
<w< !me [user]
>w> @user| 240.4h | 10 points| 585 messages [user]
<w< !gamble 10 [user]
>>> @user, you won. Now you have 20  points [user]
<w< !gamble 20 [user]
>>> @user, you lost. Now you have  -20  points [user]

**Comment by sogehige** [comment]
Right, message is incorrect, actual points is ok
