### ISSUE TITLE
!fightme doesn't timeout

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#929]
When fighting someone it no longer times the person outlasted normal user vs mod. Mod won obviously but user wasn't timed out for 1 second.

**Comment by sogehige** [comment]
Message after command is correct?

**Comment by sogehige** [comment]
There should be an error in logs I believe

**Comment by ic3dr460n** [comment]
Yes, it replies with under divine protection or the normal response but nothing else happens.
