### ISSUE TITLE
!top tips not send message in chat

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#931]
### Actual behavior
!top tips
Message in logs but not in chat

**Comment by sogehelper** [comment]
Maybe message to long?? Thats why it can me not in chat

**Comment by sogehige** [comment]
Possible, will add some message split

**Comment by sogehelper** [comment]
In whispers i can see 9 users in top, so guess it's just chat symbols limit

**Comment by sogehige** [comment]
Can you share string what is not being sent?

**Comment by sogehelper** [comment]
You still cannot reproduce? So it's just when message to long. Thats why i not see bot response. Because message to long. Maybe make this like !set list, it's just will 2-3-4 e.t.c messages in chat

**Comment by sogehige** [comment]
I cannot reproduce with message you sent me not going through, that message is far before char or byte limit
