### ISSUE TITLE
Command Permissions Bug

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#943]
Command Permissions doesn't seem to list certain custom commands. I added !shoutout command and anyone can use it and not able to set permission to only mods in the bot.

Bot Version 7.3.1

**Comment by sogehige** [comment]
Permissions for command are setable in custom commands page (or by !command command)

![sogebot ui 7 4 0 snapshot](https://user-images.githubusercontent.com/19549652/39217292-a2f3b648-481f-11e8-96c8-c65a916e2885.png)
