### ISSUE TITLE
Bets no longer work

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#944]
Bot Version 7.3.1

Error below
1|ICEBOT   | 2018-04-25T11:32:24.766Z <<< !bet open [ic3dr460n]
1|ICEBOT   | 2018-04-25T11:32:24.870Z |! TypeError: Cannot read property 'length' of null
1|ICEBOT   |     at Object.open [as fnc] (/home/bots/icebot/libs/systems/bets.js:100:18)
1|ICEBOT   |     at <anonymous>
1|ICEBOT   |     at process._tickCallback (internal/process/next_tick.js:182:7)

![image](https://user-images.githubusercontent.com/32691495/39243308-043a3108-485b-11e8-935e-a7c171a8e4f0.png)

Also not sure if that should read like that either.

**Comment by sogehige** [comment]
Yes, this is incorrect check on `!bet open` without options. To open bet `!bet open option1 option2`

**Comment by sogehige** [comment]
Widget issue is only after closed bet, this is minor issue
