### ISSUE TITLE
1000 messages was sended

### ISSUE THREAD

**Issue by portovayashlyha** [sogehige/sogeBot#953]
### Actual behavior
 2018-04-27T14:12:49.329Z !!! ERROR !!! Possibly Unhandled Rejection at: Promise { <rejected> 'Not connected to server.' } reason: Not connected to server.
0|sadrusty | 2018-04-27T14:12:49.442Z >>> @p0ooo0h | 56.4h | 5970 mp | 1477 сообщений [p0ooo0h]
0|sadrusty | 2018-04-27T14:12:49.444Z !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
0|sadrusty |   <rejected> Error: not opened
0|sadrusty |     at WebSocket.send (/home/sadrusty/node_modules/twitch-js/node_modules/ws/lib/WebSocket.js:218:16)
0|sadrusty |     at /home/sadrusty/node_modules/twitch-js/lib/client.js:1134:17
0|sadrusty |     at new Promise (<anonymous>)
0|sadrusty |     at client._sendMessage (/home/sadrusty/node_modules/twitch-js/lib/client.js:1117:10)
0|sadrusty |     at client.say (/home/sadrusty/node_modules/twitch-js/lib/commands.js:443:17)
0|sadrusty |     at Worker.worker.on (/home/sadrusty/main.js:142:21)
0|sadrusty |     at Worker.emit (events.js:185:15)
0|sadrusty |     at ChildProcess.Worker.process.on (internal/cluster/worker.js:28:12)
0|sadrusty |     at ChildProcess.emit (events.js:180:13)
0|sadrusty |     at emit (internal/child_process.js:783:12) } reason: Error: not opened

**Comment by sogehige** [comment]
Thanks for an issue! Will be fixed in **7.4.0**
