### ISSUE TITLE
Bank Hesists Problem

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#954]
Version 7.3.1

When opening the bank heists page the webpage crashes browser and also crashes bot 30-1min later. 

https://cdn.discordapp.com/attachments/417079241163931665/439560542173134860/unknown.png

https://cdn.discordapp.com/attachments/417079241163931665/439561089286668293/unknown.png

Not sure how to explain but no error in logs either. The same text blocks are repeated over and over and over again.

**Comment by sogehige** [comment]
That's strange behavior indeed, although I cannot reproduce on `nedb` or `mongodb` can you provide your `games.heist*` collections?

**Comment by sogehige** [comment]
Also information about your browser

**Comment by sogehelper** [comment]
I have same problem.
Mine browser is chrome

**Comment by sogehelper** [comment]
I open heist page, and after this this tab not resposible anymore

**Comment by sogehige** [comment]
This issue is caused by recursive saving into db, added unique indexes.

If bot refuses to start, remove games.heist.levels, games.heist.results collections
