### ISSUE TITLE
Need code help with my own system

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#959]
### Actual behavior
I create own sytem, and i have no idea how i can realize it in your bot
i need something like
1) when user iniciate this by command
then next 20 seconds catch messages in chat, and need catch emotes in this messages
but it's must be only 20 seconds
2) catch every message in chat for 40 seconds (after 40s stop doing this)

**Comment by sogehige** [comment]
Use discord for helping building your own systems
https://discordapp.com/invite/52KpmuH
