### ISSUE TITLE
Add possible revert changes for user

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#966]
### Actual behavior
Add possible revert followage,subage,e.t.c for user (from dashboard)

**Comment by sogehige** [comment]
Revert from, to? Not sure what revert you mean, if you change some value, and you don't want to save it, pres cancel :)

**Comment by sogehelper** [comment]
It's part of that
https://ideas.sogehige.tv/ideas/37/make-possible-set-user-stats-force
If it will in bit, then will be good possible revert to "real" followage

**Comment by sogehige** [comment]
ok, so its same as #994 , closing
