### ISSUE TITLE
Stream monitor wont load

### ISSUE THREAD

**Issue by th0rtz** [sogehige/sogeBot#973]
### Expected behavior
Loading stream monitor

### Actual behavior
The stream monitor don't load

### Steps to reproduce
Get a reverse proxy and serve the sogebot webUI with "HTTPS".

### Additional informations
Got : jquery.min.js:2 Mixed Content: The page at 'https://stream.acme.lan/' was loaded over HTTPS, but requested an insecure resource 'http://player.twitch.tv/?channel=acme&autoplay=true&muted=true'. This request has been blocked; the content must be served over HTTPS.

**Comment by th0rtz** [comment]
I think just replace the "http" by "https" on [public/widget/twitch.html](https://github.com/sogehige/sogeBot/blob/3f0efac32dfd583a14ef5ee64335d97fef09749d/public/widgets/twitch.html#L29)
>       src="http://player.twitch.tv/?channel=${room}&autoplay=true&muted=true"
by 
>       src="https://player.twitch.tv/?channel=${room}&autoplay=true&muted=true"

If you use the web UI only on HTTP, this will not affect the behavior, and this will work for webUI on HTTPS.

**Comment by sogehige** [comment]
Thanks for issue!
