### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by LARPOffical** [sogehige/sogeBot#982]
twitch-bot\public\dist\css\light.css'

**Comment by sogehige** [comment]
This file should be generated, when you are running bot through
`npm start`

**Comment by LARPOffical** [comment]
https://pastebin.com/eJ0Naknd

**Comment by sogehige** [comment]
`'node-sass' is not recognized as an internal or external command,`

you should do `npm install`

**Comment by LARPOffical** [comment]
I just did twice and had to reinstall all of the modules I will try again.

**Comment by sogehige** [comment]
you can try `node install node-sass` after it just to be sure
