### ISSUE TITLE
When i click save button in custom varibale widget nothing happens

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#986]
### Actual behavior
When i click save button in custom varibale widget nothing happens
In chrome console i have `Uncaught TypeError: Assignment to constant variable.
    at Object.save (<anonymous>:10:12)
    at HTMLButtonElement.onclick` error
what link to `name = $(el).data('name')` string

**Comment by sogehige** [comment]
Steps to reproduce? What are you saving?

**Comment by sogehelper** [comment]
I have $_mmr variable what is number.
When i change it from 4000 to any other number i got this error.
