### ISSUE TITLE
Check token expirations (refreshing access tokens)

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#987]
### Actual behavior
Token have experations
So i asked at twitch dev forum and they linked me this https://dev.twitch.tv/docs/authentication/#refreshing-access-tokens|
Can you check that?

**Comment by sogehelper** [comment]
Some discuss on twitch forum
https://discuss.dev.twitch.tv/t/oauth-implicit-code-flow-user-access-tokens-expiration/11662/

**Comment by sogehige** [comment]
Closed in favor of #1107
