### ISSUE TITLE
Twitch API v5 going away

### ISSUE THREAD

**Issue by draconicfae** [sogehige/sogeBot#988]
### Expected behavior
Exclusive use of api.twitch.tv/helix (the new Twitch API)
### Actual behavior
api.twitch.tv/kraken (Twitch API v5) is still used in a bunch of places

### Additional informations

v5 disappears at end of 2018 so any remaining krakens at that point will be broken

**Comment by sogehelper** [comment]
Yea man we are know.
Much things in helix still not avalible, but when twitch add futures @sogehige update our best bot for new api.
Much things already on new api

**Comment by sogehige** [comment]
Actually I would like to use new API exclusively, but now new API doesn't
have every endpoint needed

Dne ne 20. 5. 2018 19:15 uživatel draconicfae <notifications@github.com>
napsal:

**Comment by sogehige** [comment]
Closing as we are fully on new API (or at least should be next version)
