### ISSUE TITLE
Replace function not works in eval with url()

### ISSUE THREAD

**Issue by sogehelper** [sogehige/sogeBot#995]
### Actual behavior
In eval i have some code, and replace function not working
For example url return `@System: Username stats summary: [Wins: 182, Matches: 877, K/d: 8.26, Kills: 5738, Win %: 20.8] [Solo] [Fortnitetracker.com 🖤]`
and i want to replace some text. I tryed use lodash function, and javascript, but both not working for me.
` let str = url('https://2g.be/twitch/Fortnite/command/query=solo%20Ninja&default_platform=pc&default_playlist=solo&channel=soge__'); str=str.replace('[Fortnitetracker.com 🖤]','');str=str.replace('Solo','(Solo)');str=str.replace('Duo','(Duo)');str=str.replace('Squad','(Squad)');str=str.replace(' stats summary','');str=str.replace('@System: ','');return str;`
### Steps to reproduce
You can just use same eval code like mine
### Additional informations

Latest master, MongoDB

**Comment by sogehige** [comment]
That command is returning me
`Ninja's: [Wins: 1215, Matches: 3523, K/d: 11.75, Kills: 27124, Win %: 34.5] [(Solo)]`

Use latest master
